<?php # 2024-02-06 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
$_item = $this->getItem();
$this->setPriceDataObject($_item) ?>
<tr class="border">
    <td><?php echo $this->getColumnHtml($_item, 'downloadable') ?></td>
    <td class="a-right">
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
            <span class="price-excl-tax">
				<?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
					<span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
				<?php endif ?>
				<?php echo $this->displayPrices($_item->getBasePrice(), $_item->getPrice()) ?>
			</span>
            <br/>
        <?php endif ?>
        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <span class="price-incl-tax">
				<?php if ($this->helper('tax')->displayCartBothPrices()): ?>
					<span class="label"><?php echo $this->helper('tax')->__('Incl. Tax'); ?>:</span>
				<?php endif ?>
				<?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getPriceInclTax($_item)); ?>
            </span>
        <?php endif ?>
    </td>
    <td class="a-center"><?php echo $_item->getQty() * 1 ?></td>
    <td class="a-right">
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
            <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                <?php endif ?>
				<?php echo $this->displayPrices($_item->getBaseRowTotal(), $_item->getRowTotal()) ?>
            </span>
            <br/>
        <?php endif ?>

        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax'); ?>:</span>
                <?php endif ?>
				<?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($_item)); ?>
            </span>
        <?php endif ?>
    </td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('tax_amount') ?></td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
    <td class="a-right last">
        <?= $this->displayPrices(
				$_item->getBaseRowTotal()
				+ $_item->getBaseTaxAmount()
				- $_item->getBaseDiscountAmount()
				+ $_item->getBaseHiddenTaxAmount()
			,
            	$_item->getRowTotal()
				+ $_item->getTaxAmount()
				- $_item->getDiscountAmount()
				+ $_item->getHiddenTaxAmount()
        ) ?>
    </td>
</tr>
