<?php # 2024-01-28 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `Mage_Customer_Block_Form_Register`'s `persistent/customer/form/register.phtml` template
# 1.9.1.0 → 1.9.4.5 changes to `customfield/customfields.phtml`": https://github.com/thehcginstitute-com/m1/issues/315
# 2) "Port the `Mage_Customer_Block_Form_Register`'s `persistent/customer/form/register.phtml` template
# 1.9.1.0 → 1.9.4.5 changes to `magepsycho/customerregfields/customer/form/register.phtml`
# (`magepsycho_customerregfields/switchCustomerFormRegisterTemplateIf`)":
# https://github.com/thehcginstitute-com/m1/issues/316
/** @var Mage_Customer_Block_Form_Register $this */ ?>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
<!-- 2023-01-16 Dmitrii Fediuk https://www.upwork.com/fl/mage2pro
"Make the `Webkul_CustomField` module compatible with the `MagePsycho_Customerregfields` module":
https://github.com/thehcginstitute-com/m1/issues/8 -->
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <ul class="form-list">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Email Address')) ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
<!-- 2023-01-16 Dmitrii Fediuk https://www.upwork.com/fl/mage2pro
1) "Make the `Webkul_CustomField` module compatible with the `MagePsycho_Customerregfields` module":
https://github.com/thehcginstitute-com/m1/issues/8
2) `MagePsycho_Customerregfields`
2.1)
https://github.com/thehcginstitute-com/m1/blob/2023-01-16-1/app/design/frontend/default/mobileshoppe/template/magepsycho/customerregfields/customer/form/register.phtml#L58-L77
2.2) @see MagePsycho_Customerregfields_Helper_Data::switchCustomerFormRegisterTemplateIf():
	if ($this->enabled()) {
		return 'magepsycho/customerregfields/customer/form/register.phtml';
	}
	else {
		return 'persistent/customer/form/register.phtml';
	}
https://github.com/thehcginstitute-com/m1/blob/2023-01-16-1/app/code/local/MagePsycho/Customerregfields/Helper/Data.php#L206-L213
2.3)
<customer_account_create>
	<reference name="customer_form_register">
		<action method="setTemplate" ifconfig="magepsycho_customerregfields/option/active">
			<template helper="magepsycho_customerregfields/switchCustomerFormRegisterTemplateIf" />
		</action>
	</reference>
</customer_account_create>
https://github.com/thehcginstitute-com/m1/blob/2023-01-16-1/app/design/frontend/default/mobileshoppe/layout/magepsycho_customerregfields.xml#L12-L18
3) `Webkul_CustomField`:
	<customer_account_create>
        <reference name="customer_form_register">
            <action method="setTemplate"><template>customfield/customfields.phtml</template></action>
        </reference>
https://github.com/thehcginstitute-com/m1/blob/2023-01-16-1/app/design/frontend/base/default/layout/customfield.xml#L11-L14
2024-01-28
"The template `customfield/customfields.phtml` of `Webkul_CustomField`
conflicts with the template `magepsycho/customerregfields/customer/form/register.phtml` of `MagePsycho_Customerregfields`":
https://github.com/thehcginstitute-com/m1/issues/333 -->
			<?php if(hcg_mp_hc()->enabled()) { ?>
				<li>
					<?=
						$this->getLayout()
							->createBlock('magepsycho_customerregfields/customer_widget_type')
							->setObject($this->getFormData())
							->setIsEditPage(false)
							->toHtml()
					?>
				</li>
				<li>
					<label for="telephone" class="required"><em>*</em><?= $this->__('Telephone') ?></label>
					<div class="input-box">
						<input
							type="text"
							name="telephone"
							id="telephone"
							value="<?= $this->escapeHtml($this->getFormData()->getTelephone()) ?>"
							title="<?= Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>"
							class="input-text <?= $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>"
						/>
					</div>
				</li>
			<?php } ?>
			<?php if ($this->isNewsletterEnabled()): ?>
				<li class="control">
					<div class="input-box">
						<input type="checkbox" name="is_subscribed" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"<?php if ($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif ?> class="checkbox" />
					</div>
					<label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
				</li>
			<?php endif ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>

            <?php if ($this->getShowAddressFields()): ?>
                <li class="hidden">
                    <input type="hidden" name="create_address" value="1" />
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="tel" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                        </div>
                    </div>
                </li>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <label for="billing:street<?php echo $_i ?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i - 1)) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php endfor ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
                <li class="hidden">
                    <input type="hidden" name="default_billing" value="1" />
                    <input type="hidden" name="default_shipping" value="1" />
                </li>
            <?php endif ?>
			</ul>
		</div>
<!-- 2023-01-16 Dmitrii Fediuk https://www.upwork.com/fl/mage2pro
"Make the `Webkul_CustomField` module compatible with the `MagePsycho_Customerregfields` module":
https://github.com/thehcginstitute-com/m1/issues/8 -->
		<div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
			<?= $this->getLayout()->createBlock('cms/block')->setBlockId('confirm_message')->toHtml() ?>
			<ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
							<?php # 2024-01-28 Dmitrii Fediuk https://upwork.com/fl/mage2pro
							# 1) "Port the `Mage_Customer_Block_Form_Register`'s
							# `persistent/customer/form/register.phtml` template 1.9.1.0 → 1.9.4.5 changes
							# to `customfield/customfields.phtml`": https://github.com/thehcginstitute-com/m1/issues/315
							# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/persistent/customer/form/register.phtml#L161-L169 ?>
                            <?php $minPasswordLength = $this->getMinPasswordLength(); ?>
                            <input
								type="password"
								name="password"
								id="password"
								title="<?= Mage::helper('core')->quoteEscape($this->__('Password')) ?>"
								class="input-text required-entry validate-password min-pass-length-<?= $minPasswordLength ?>"
							/>
                            <p class="form-instructions"><?= Mage::helper('customer')->__('The minimum password length is %s', $minPasswordLength) ?></p>
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
			</ul>
		</div>
		<div class="fieldset">
			<ul class="form-list">
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>
			<div class="buttons-set">
	            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	            <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Register')) ?>" class="button"><span><span><?php echo $this->__('Register') ?></span></span></button>
	        </div>
	        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
	            <input name="context" type="hidden" value="checkout" />
	        <?php endif ?>
			</form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if ($this->getShowAddressFields()) {
			# 2024-02-14 Dmitrii Fediuk https://upwork.com/fl/mage2pro
			# "Upgrade Magento 1.9.4.5 to OpenMage LTS 19.5.2": https://github.com/thehcginstitute-com/m1/issues/34
		?>
			new RegionUpdater(
				'country'
				,'region'
				,'region_id'
				,<?= Mage::helper('directory')->getRegionJsonByStore() ?>
				,undefined
				,'zip'
			);
        <?php } ?>
    //]]>
    </script>
</div>
