<?php # 2024-02-06 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
$_item = $this->getItem();
$_order = $this->getItem()->getOrderItem()->getOrder() ?>
<tr class="border" id="order-item-row-<?php echo $_item->getId() ?>">
<td><h4 class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></h4>
    <?php if ($_options = $this->getItemOptions()): ?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                <?php if (!$this->getPrintStatus()): ?>
                    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                    <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                            <div class="truncated_full_value">
                                <dl class="item-options">
                                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                    <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                                </dl>
                            </div>
                        <?php endif; ?>
                    </dd>
                <?php else: ?>
                    <dd><?php echo $this->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                <?php endif; ?>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
    <?php if ($addInfoBlock) : ?>
        <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
    <?php endif; ?>
    <?php echo $this->escapeHtml($_item->getDescription()) ?>
    <?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item->getOrderItem()) && $_item->getGiftMessageId()): ?>
        <a href="#" id="order-item-gift-message-link-<?php echo $_item->getId() ?>" class="gift-message-link"
           onclick="return giftMessageToogle('<?php echo $_item->getId() ?>')"><?php echo $this->__('Gift Message') ?></a>
    <?php endif; ?>
</td>
<td><?php echo $this->escapeHtml(Mage::helper('core/string')->splitInjection($this->getSku())) ?></td>
<td class="a-right">
    <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
    <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                <?php endif; ?>
				<span class="cart-price">
					<?php echo $this->getOrder()->formatPrice($this->getItem()->getPrice()) ?>
                </span>
            </span>
            <br/>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
        <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                <?php endif; ?>
            	<?php $_incl = $this->helper('checkout')->getPriceInclTax($this->getItem()); ?>
				<span class="cart-price">
					<?php echo $this->getOrder()->formatPrice($_incl) ?>
                </span>
            </span>
            <?php endif; ?>
</td>
<td class="a-center"><?php echo $_item->getQty() * 1 ?></td>
<td class="a-right">
    <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
    <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                <?php endif; ?>
				<span class="cart-price">
					<?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()) ?>
                </span>
            </span>
            <br/>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
        <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                <?php endif; ?>
            <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($this->getItem()); ?>
			<span class="cart-price">
				<?php echo $this->getOrder()->formatPrice($_incl) ?>
			</span>
		</span>
            <?php endif; ?>
</td>
<td class="a-right"><?php echo $_order->formatPrice(-$_item->getDiscountAmount()) ?></td>
<td class="last a-right">
    <?php echo $_order->formatPrice($_item->getRowTotal() - $_item->getDiscountAmount() + $_item->getTaxAmount() + $_item->getWeeeTaxAppliedRowAmount()) ?>
</td>
</tr>
