<?php
# 2024-09-01 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Improve the «Yaay! Recovered by Mailchimp's campaign» block of the backend order screen":
# https://github.com/thehcginstitute-com/m1/issues/668
# 2) "Refactor `app/design/adminhtml/default/default/template/sales/order/view/info.phtml`":
# https://github.com/thehcginstitute-com/m1/issues/669
use Mage_Adminhtml_Block_Sales_Order_View_Info as B;
use Mage_Sales_Model_Order as O;
/** @var B $this */ $b = $this; /** @var B $b */
$o = $b->getOrder(); /** @var O $o */
?>
<script type="text/javascript">
	var ORDER_ID = <?= $o->getId(); ?>;
</script>
<?php
$canEdit = Mage::getModel('iwd_ordermanager/order_edit')->checkOrderStatusForUpdate($o);
$echo = df_block_echo('hcg/sales/order/view/info', ['b' => $b, 'canEdit' => $canEdit, 'o' => $o]);
$echo('primary');
?>
<div class="box-right">
	<!--Account Information-->
	<div class="entry-edit">

		<div class="entry-edit-head order-account">
			<h4 class="icon-head head-account"><?= Mage::helper('sales')->__('Account Information') ?></h4>

			<div class="tools" style="float:right">
				<?php $isAllow = Mage::getSingleton('admin/session')->isAllowed('iwd_ordermanager/order/actions/edit_account_information'); ?>
				<?php if ($isAllow): ?>
					<?php if ($canEdit) : ?>
						<a id="account_information_edit_<?= $o->getEntityId(); ?>"
						   class="account_information_edit" href="#"
						   title="<?= Mage::helper('sales')->__('Edit account information for order only'); ?>">
							<?= Mage::helper('sales')->__('Edit'); ?>
						</a>
					<?php else : ?>
						<a href="#"
						   onclick="alert('Sorry, You can not update account information for order with this status. Check configuration by module IWD_OrderManager.'); return false;"
						   title="You can not edit account information!">
							<?= Mage::helper('sales')->__("Edit"); ?>
						</a>
					<?php endif ?>
				<?php endif ?>
			</div>
		</div>
		<div class="fieldset">
			<div class="hor-scroll">
				<div class="hor-scroll" id="account_information_<?= $o->getEntityId(); ?>">
					<table cellspacing="0" class="form-list">
						<tr>
							<td class="label"><label><?= Mage::helper('sales')->__('Customer Name') ?></label></td>
							<td class="value">
								<?php if ($_customerUrl = $b->getCustomerViewUrl()) : ?>
									<a href="<?= $_customerUrl ?>"
									   target="_blank"><strong><?= $b->htmlEscape($o->getCustomerName()) ?></strong></a>
								<?php else: ?>
									<strong><?= $b->htmlEscape($o->getCustomerName()) ?></strong>
								<?php endif ?>
							</td>
						</tr>
						<tr>
							<td class="label"><label><?= Mage::helper('sales')->__('Email') ?></label></td>
							<td class="value"><a
										href="mailto:<?= $o->getCustomerEmail() ?>"><strong><?= $o->getCustomerEmail() ?></strong></a>
							</td>
						</tr>
						<?php if ($_groupName = $b->getCustomerGroupName()) : ?>
							<tr>
								<td class="label"><label><?= Mage::helper('sales')->__('Customer Group') ?></label>
								</td>
								<td class="value"><strong><?= $_groupName ?></strong></td>
							</tr>
						<?php endif ?>
						<?php foreach ($b->getCustomerAccountData() as $data): ?>
							<tr>
								<td class="label"><label><?= $data['label'] ?></label></td>
								<td class="value"><strong><?= $data['value'] ?></strong></td>
							</tr>
						<?php endforeach;
							# 2024-01-26 Dmitrii Fediuk https://upwork.com/fl/mage2pro
							# "The template `opcsignature/sales/order/view/info.phtml`
							# of `IWD_OnepageCheckoutSignature_Block_Sales_Order_View_Info`
							# conflicts with the template `customfield/sales/order/view/info.phtml` of `Webkul_CustomField`,
							# the template `iwd/ordermanager/order/view/info.phtml` of `IWD_OrderManager`,
							# and the template `iwd/orderflags/order/view/info.phtml` of `IWD_OrderFlags`,
							# because they are all override the template `sales/order/view/info.phtml`
							# of `Mage_Adminhtml_Block_Sales_Order_View_Info`":
							# https://github.com/thehcginstitute-com/m1/issues/327
							$echo('IWD_OnepageCheckoutSignature');
							# 2024-02-18 Dmitrii Fediuk https://upwork.com/fl/mage2pro
							# "Delete the unused `Webkul_CustomField` module":
							# https://github.com/thehcginstitute-com/m1/issues/382
						?>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="clear"></div>

<div class="box-left">
	<!--Billing Address-->
	<div class="entry-edit">
		<div class="hor-scroll">
			<div class="entry-edit-head billing-address">
				<h4 class="icon-head head-billing-address"><?= Mage::helper('sales')->__('Billing Address') ?></h4>

				<div class="tools" style="float:right">
					<?php $isAllow = Mage::getModel('iwd_ordermanager/address')->isAllowEditAddress(); ?>
					<?php if ($isAllow): ?>
						<?php if ($canEdit) : ?>
							<a id="billing_address_edit_<?= $o->getBillingAddress()->getId() ?>"
							   class="order_address_edit" href="#"
							   title="<?= Mage::helper('sales')->__('Edit billing address for order only'); ?>">
								<?= Mage::helper('sales')->__('Edit'); ?>
							</a>
						<?php else : ?>
							<a href="#"
							   onclick="alert('Sorry, You can not update billing address for order with this status. Check configuration by module IWD_OrderManager.'); return false;"
							   title="You can not edit billing address!">
								<?= Mage::helper('sales')->__("Edit"); ?>
							</a>
						<?php endif ?>
					<?php endif ?>
				</div>
			</div>
			<fieldset>
				<address id="order_address_<?= $o->getBillingAddress()->getId() ?>"><?= $o->getBillingAddress()->getFormated(true) ?></address>
			</fieldset>
		</div>
	</div>
</div>
<?php if (!$b->getOrder()->getIsVirtual()): ?>
	<div class="box-right">
		<!--Shipping Address-->
		<div class="hor-scroll">
			<div class="entry-edit">
				<div class="entry-edit-head order-shipping">
					<h4 class="icon-head head-shipping-address"><?= Mage::helper('sales')->__('Shipping Address') ?></h4>
					<div class="tools" style="float:right">
						<?php if ($isAllow): ?>
							<?php if ($canEdit) : ?>
								<a id="shipping_address_edit_<?= $o->getShippingAddress()->getId() ?>"
								   class="order_address_edit" href="#"
								   title="<?= Mage::helper('sales')->__('Edit shipping address for order only') ?>">
									<?= Mage::helper('sales')->__('Edit'); ?>
								</a>
							<?php else : ?>
								<a href="#"
								   onclick="alert('Sorry, You can not update shipping address for order with this status. Check configuration by module IWD_OrderManager.'); return false;"
								   title="You can not edit shipping address!">
									<?= Mage::helper('sales')->__("Edit"); ?>
								</a>
							<?php endif ?>
						<?php endif ?>
					</div>
				</div>
				<fieldset>
					<address id="order_address_<?= $o->getShippingAddress()->getId() ?>"><?= $b->maliciousCodeFilter($o->getShippingAddress()->getFormated(true)) ?></address>
				</fieldset>
			</div>
		</div>
	</div>
	<div class="clear"></div>
<?php endif ?>