<?php
# 2024-09-01 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Improve the «Yaay! Recovered by Mailchimp's campaign» block of the backend order screen":
# https://github.com/thehcginstitute-com/m1/issues/668
# 2) "Refactor `app/design/adminhtml/default/default/template/sales/order/view/info.phtml`":
# https://github.com/thehcginstitute-com/m1/issues/669
use Mage_Adminhtml_Block_Sales_Order_View_Info as B;
use Mage_Sales_Model_Order as O;
/** @var B $this */ $b = $this; /** @var B $b */
$o = $b->getOrder(); /** @var O $o */
?>
<script type="text/javascript">
	var ORDER_ID = <?= $o->getId(); ?>;
</script>
<?php
$canEdit = Mage::getModel('iwd_ordermanager/order_edit')->checkOrderStatusForUpdate($o);
$echo = df_block_echo('hcg/sales/order/view/info', ['b' => $b, 'canEdit' => $canEdit, 'o' => $o]);
$echo('primary', 'account');
?><div class="clear"></div><?php
$echo('address/billing', 'address/shipping');