<?php # 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
$_item = $this->getItem();
$_order = $this->getItem()->getOrderItem()->getOrder(); ?>
<tr class="border" id="order-item-row-<?php echo $_item->getId() ?>">
<td><h4 class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></h4>
    <?php if ($_options = $this->getItemOptions()): ?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                <?php if (!$this->getPrintStatus()): ?>
                    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                    <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
                        <?php echo $_formatedOptionValue['value'] ?>
                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                            <div class="truncated_full_value">
                                <dl class="item-options">
                                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                    <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                                </dl>
                            </div>
                        <?php endif; ?>
                    </dd>
                <?php else: ?>
                    <dd><?php echo $this->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                <?php endif; ?>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>

    <!-- downloadable -->
    <?php if ($links = $this->getLinks()): ?>
        <dl class="item-options">
            <dt><?php echo $this->escapeHtml($this->getLinksTitle()); ?></dt>
            <?php foreach ($links->getPurchasedItems() as $link): ?>
                <dd><?php echo $this->escapeHtml($link->getLinkTitle()); ?></dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
    <!-- EOF downloadable -->

    <?php echo $this->escapeHtml($_item->getDescription()) ?>
    <?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $_item->getOrderItem()) && $_item->getGiftMessageId()): ?>
        <br/><a href="#" id="order-item-gift-message-link-<?php echo $_item->getId() ?>"
                class="giftmessage-preview-link expand"
                onclick="return giftMessageToogle('<?php echo $_item->getId() ?>')"><?php echo $this->__('Gift Message') ?></a>
    <?php endif; ?>
</td>
<td><?php echo $this->escapeHtml(Mage::helper('core/string')->splitInjection($this->getSku())) ?></td>
<td class="a-right nowrap">
    <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceExclTax()): ?>
    <span class="price-excl-tax">
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
            <?php endif; ?>
			<span class="cart-price">
				<?php echo $this->getOrder()->formatPrice($this->getItem()->getPrice()) ?>
			</span>
        </span>
        <br/>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceInclTax()): ?>
        <span class="price-incl-tax">
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php $_incl = $this->helper('checkout')->getPriceInclTax($this->getItem()); ?>

            <span class="cart-price">
				<?php echo $this->getOrder()->formatPrice($_incl) ?>
			</span>
        </span>
            <?php endif; ?>
</td>
<td class="a-center"><?php echo $_item->getQty() * 1 ?> </td>
<td class="a-right nowrap">
    <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceExclTax()): ?>
    <span class="price-excl-tax">
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
            <?php endif; ?>
			<span class="cart-price">
				<?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()) ?>
			</span>
        </span>
        <br/>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceInclTax()): ?>
        <span class="price-incl-tax">
            <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
            <?php endif; ?>
            <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($this->getItem()); ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
            <span class="cart-tax-total"
                  onclick="taxToggle('subtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
            <?php else: ?>
                <span class="cart-price">
            <?php endif; ?>
            <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), array(0, 1, 4), 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                <?php echo $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?>
            <?php else: ?>
                <?php echo $this->getOrder()->formatPrice($_incl - $this->getItem()->getWeeeTaxRowDisposition()) ?>
            <?php endif; ?>
                </span>

                <?php if (Mage::helper('weee')->getApplied($this->getItem())): ?>
                    <span class="cart-tax-info" id="subtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>"
                          style="display:none;">
                    <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 1, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>
                                    : <?php echo $this->getOrder()->formatPrice($tax['row_amount_incl_tax']); ?></span>
                            <?php endforeach; ?>
                        </small>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                            <span class="nobr"><small><?php echo $tax['title']; ?>
                                    : <?php echo $this->getOrder()->formatPrice($tax['row_amount_incl_tax']); ?></small></span>
                        <?php endforeach; ?>
                    <?php elseif (Mage::helper('weee')->typeOfDisplay($this->getItem(), 4, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <small>
                            <?php foreach (Mage::helper('weee')->getApplied($this->getItem()) as $tax): ?>
                                <span class="nobr"><?php echo $tax['title']; ?>
                                    : <?php echo $this->getOrder()->formatPrice($tax['row_amount_incl_tax']); ?></span>
                            <?php endforeach; ?>
                        </small>
                    <?php endif; ?>
                </span>

                <?php if (Mage::helper('weee')->typeOfDisplay($this->getItem(), 2, 'sales') && (float)$this->getItem()->getWeeeTaxAppliedAmount()): ?>
                        <span class="cart-tax-total"
                              onclick="taxToggle('subtotal-item-tax-details<?php echo $this->getItem()->getId(); ?>', this, 'cart-tax-total-expanded');">
                        <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>
                            :<br/> <?php echo $this->getOrder()->formatPrice($_incl + Mage::helper('weee')->getRowWeeeTaxInclTax($_item)); ?></span>
                    </span>
                    <?php endif; ?>
                <?php endif; ?>
        </span>
            <?php endif; ?>
</td>
</tr>
