<?php /* @var  Mage_Catalog_Block_Product_Compare_Sidebar $this */
$_helper = $this->helper('catalog/product_compare');
$_items = $_helper->getItemCount() > 0 ? $_helper->getItemCollection() : null;
# 2024-01-15 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) We can use `Mage::getSingleton('customer/session')->getCustomerGroupId()` here,
# because the template is cached in the current visitor's session, not in the Magento's cache:
# https://github.com/thehcginstitute-com/m1/issues/239#issuecomment-1891306046
# 2) https://github.com/thehcginstitute-com/m1/issues/239
# 3) https://github.com/thehcginstitute-com/m1/issues/238
$customerGroupId = (int)Mage::getSingleton('customer/session')->getCustomerGroupId();
# 2024-01-15 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Port the `app/design/frontend/base/default/template/catalog/product/compare/sidebar.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/206
if ($_items && 4 !== $customerGroupId) {  ?>
<div class="block block-list block-compare">
	<div class="block-title">
        <strong><span><?php echo $this->__('Compare Products') ?>
            <?php if($_helper->getItemCount() > 0): ?> 
                <small><?php echo $this->__('(%d)', $_helper->getItemCount()) ?></small>
            <?php endif; ?>
        </span></strong>
    </div>
    <div class="block-content">
    <?php if($_helper->getItemCount() > 0): ?>
        <ol id="compare-items">
        <?php foreach($_items as $_index => $_item): ?>
            <li class="item">
                <input type="hidden" class="compare-item-id" value="<?php echo $_item->getId() ?>" />
                <a href="<?php echo $_helper->getRemoveUrl($_item) ?>" title="<?php echo $this->__('Remove This Item') ?>" class="btn-remove" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove this item from the compare products?') ?>');"><?php echo $this->__('Remove This Item') ?></a>
                <p class="product-name"><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName(), 'name') ?></a></p>
            </li>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('compare-items')</script>
        <div class="actions">
            <a href="<?php echo $_helper->getClearListUrl() ?>" onclick="return confirm('<?php echo $this->__('Are you sure you would like to remove all products from your comparison?') ?>');"><?php echo $this->__('Clear All') ?></a>
            <button type="button" title="<?php echo $this->__('Compare') ?>" class="button" onclick="popWin('<?php echo $_helper->getListUrl() ?>','compare','top:0,left:0,width=820,height=600,resizable=yes,scrollbars=yes')"><span><span><?php echo $this->__('Compare') ?></span></span></button>
        </div>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items to compare.') ?></p>
    <?php endif; ?>
    </div>
</div>
<?php } ?>
