<?php
# 2024-01-09 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Port the modifications of `app/design/frontend/base/default/template/review/helper/summary.phtml`
# to Magento 1.9.4.5": https://github.com/thehcginstitute-com/m1/issues/103
if ($this->getReviewsCount()): ?>
	<div class="ratings">
		<?php if ($this->getRatingSummary()):?>
			<div class="rating-box">
				<div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
			</div>
		<?php endif;?>
		<p class="rating-links">
<!-- 2024-01-09 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Hide reviews counts": https://github.com/thehcginstitute-com/m1/issues/145 -->
			<span class="separator">|</span>
			<a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Add Your Review') ?></a>
		</p>
	</div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
	<p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>
