<?php
# 2024-01-09 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Port the modifications of `app/design/frontend/base/default/template/review/helper/summary_short.phtml`
# to Magento 1.9.4.5": https://github.com/thehcginstitute-com/m1/issues/113
if ($this->getReviewsCount()): ?>
	<div class="ratings">
		<?php if ($this->getRatingSummary()):?>
			<div class="rating-box">
				<div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
			</div>
		<?php endif;?>
		<span class="amount"><a
				href="#"
				onclick="var t = opener ? opener.window : window; t.location.href='<?php echo $this->getReviewsUrl() ?>'; return false;"
		><!-- 2024-01-09 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Hide reviews counts": https://github.com/thehcginstitute-com/m1/issues/145 --></span>
	</div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
	<p class="no-rating"><a href="<?php echo $this->getReviewsUrl() ?>#review-form"><?php echo $this->__('Be the first to review this product') ?></a></p>
<?php endif; ?>