<?php
# 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
/** @var Mage_Catalog_Block_Product_View $this */
$_product = $this->getProduct();
$_tierPrices = $this->getTierPrices();
$_finalPriceInclTax = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice(), true);

/** @var $_catalogHelper Mage_Catalog_Helper_Data */
$_catalogHelper = Mage::helper('catalog');
if (count($_tierPrices) > 0): ?>
    <ul class="<?php echo ($this->getInGrouped() ? 'tier-prices-grouped product-pricing-grouped' : 'tier-prices product-pricing'); ?>">
    <?php if ($this->getInGrouped()): ?>
        <?php $_tierPrices = $this->getTierPrices($_product); ?>
    <?php endif ?>
    <?php foreach ($_tierPrices as $_index => $_price): ?>
        <li class="tier-price tier-<?php echo $_index; ?>">
        <?php if ($_catalogHelper->canApplyMsrp($_product)): ?>
            <?php if ($this->getInGrouped()): ?>
                <?php echo $this->__('Buy %1$s for', $_price['price_qty']) ?>:
            <?php else: ?>
                <?php echo $this->__('Buy %1$s', $_price['price_qty']) ?>
            <?php endif ?>
        <?php else: ?>

        <?php if ($this->helper('tax')->displayBothPrices()): ?>
			<?php echo $this->__('Buy %1$s for %2$s (%3$s incl. tax) each', $_price['price_qty'], $_price['formated_price'], $_price['formated_price_incl_tax']) ?>
        <?php else: ?>
            <?php if ($this->helper('tax')->displayPriceIncludingTax()): ?>
				<?php echo $this->__('Buy %1$s for %2$s each', $_price['price_qty'], $_price['formated_price_incl_tax']) ?>
            <?php else: ?>
				<?php echo $this->__('Buy %1$s for %2$s each', $_price['price_qty'], $_price['formated_price']) ?>
            <?php endif ?>
        <?php endif ?>

        <?php endif; // Can apply MSRP ?>

        <?php if (!$this->getInGrouped()): ?>
            <?php if(($_product->getPrice() == $_product->getFinalPrice() && $_product->getPrice() > $_price['price'])
            || ($_product->getPrice() != $_product->getFinalPrice() &&  $_product->getFinalPrice() > $_price['price'])): ?>
                <?php echo $this->__('and') ?>&nbsp;<strong class="benefit"><?php echo $this->__('save')?>&nbsp;<span class="percent tier-<?php echo $_index;?>"><?php echo $_price['savePercent']?></span>%
            <?php endif ?></strong>
        <?php endif ?>

        <?php if ($_catalogHelper->isShowPriceOnGesture($_product)): ?>
            <?php $popupId = 'msrp-popup-' . $_product->getId() . $this->helper('core')->getRandomString(20); ?>
            <a href="#" id="<?php echo($popupId);?>"><?php echo $this->__('Click for price'); ?></a>
            <script type="text/javascript">
            <?php
                    $addToCartUrl = $this->getProduct()->isSalable()
                        ? $this->getAddToCartUrlCustom($_product, array('qty' => $_price['price_qty']), false)
                        : '';
            ?>
            <?php if (!$this->getInGrouped()): ?>
                var newLink = {
                    url: "<?php echo $addToCartUrl; ?>",
                    qty: "<?php echo $_price['price_qty']?>"
                };
            <?php else: ?>
                var newLink = {
                    url: "<?php echo $addToCartUrl; ?>",
                    notUseForm: true
                };
            <?php endif ?>
                Catalog.Map.addHelpLink(
                    $('<?php echo $popupId ?>'),
                    "<?php echo $_product->getName() ?>",
                    <?php echo json_encode($_price['real_price_html']) ?>,
                    "<?php echo $this->helper('core')->currency($_product->getMsrp(),true,false) ?>",
                    newLink
                );
            </script>
        <?php else: ?>
            <span class="msrp-price-hide-message">
                <?php echo $_catalogHelper->getMsrpPriceMessage($_product) ?>
            </span>
        <?php endif ?>


        </li>

    <?php endforeach ?>
    </ul>
<?php endif ?>
