<?php /* @var $this Mage_Captcha_Block_Captcha_Zend */ ?>

<?php /* @var $captcha Mage_Captcha_Model_Zend */ ?>
<?php $captcha = $this->getCaptchaModel() ?>
<li id="captcha-input-box-<?= $this->getFormId()?>">
	<label for="captcha_<?= $this->getFormId() ?>" class="required"><em>*</em><?= $this->__('Please type the letters below')?></label>
	<div class="input-box captcha">
		<input name="<?= Mage_Captcha_Helper_Data::INPUT_NAME_FIELD_VALUE ?>[<?= $this->getFormId()?>]" type="text" class="input-text required-entry" id="captcha_<?= $this->getFormId() ?>" />
	</div>
</li>
<li>
	<div class="captcha-image" id="captcha-image-box-<?= $this->getFormId()?>">
		<img id="captcha-reload" class="captcha-reload" src="<?= $this->getSkinUrl('images/reload.png') ?>" alt="<?= $this->__('Reload captcha') ?>" onclick="$('<?= $this->getFormId()?>').captcha.refresh(this)">
		<img id="<?= $this->getFormId() ?>" class="captcha-img" height="<?= $this->getImgHeight() ?>" src="<?= $captcha->getImgSrc() ?>"/>
		<?php if ($captcha->isCaseSensitive()) :?>
		<div class="captcha-note">
			<?= $this->__('<strong>Attention</strong>: Captcha is case sensitive.') ?>
		</div>
		<?php endif ?>
	</div>
	<script type="text/javascript">//<![CDATA[
		$('<?= $this->getFormId() ?>').captcha = new Captcha('<?= $this->getRefreshUrl() ?>', '<?= $this->getFormId() ?>');
	//]]></script>
</li>

