<?php # 2024-02-06 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
$_item = $this->getItem()?>
<tbody>
    <tr>
        <td colspan="2">
            <h3 class="product-name"><?php echo $this->escapeHtml($this->getProductName()) ?></h3>

            <?php if ($_options = $this->getOptionList()):?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                    <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                    <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
                        <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <div class="truncated_full_value">
                            <dl class="item-options">
                                <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                            </dl>
                        </div>
                        <?php endif; ?>
                    </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>

            <?php if ($addtInfoBlock = $this->getProductAdditionalInformationBlock()):?>
                <?php echo $addtInfoBlock->setItem($_item)->toHtml() ?>
            <?php endif;?>

        </td>
    </tr>
    <tr>
        <td class="a-left">
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
				<span class="cart-price">
					<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
                </span>
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartPriceInclTax()): ?>
                <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
				<span class="cart-price">
					<?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxDisposition()) ?>
                </span>
            <?php endif; ?>
        </td>
        <td class="a-right">
            <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
				<span class="cart-price">
					<?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
                </span>
            <?php endif; ?>

            <?php if ($this->helper('tax')->displayCartPriceInclTax()): ?>

                <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
				<span class="cart-price">
					<?php echo $this->helper('checkout')->formatPrice($_incl) ?>
                </span>
            <?php endif; ?>
        </td>
    </tr>
</tbody>
