<?php # 2024-02-14 Dmitrii Fediuk https://upwork.com/fl/mage2pro
/** @var Mage_Checkout_Block_Cart_Totals $this  */ ?>
<?php if ($this->getTotals()): ?>
<tfoot>
    <?php $_colspan = 0; ?>
    <?php echo $this->renderTotals(null, $_colspan); ?>
    <?php echo $this->renderTotals('footer', $_colspan); ?>
    <?php if ($this->needDisplayBaseGrandtotal()): ?>
    <tr>
        <td class="a-right" colspan="<?php echo $_colspan; ?>">
<!-- 2024-02-14 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Upgrade Magento 1.9.4.5 to OpenMage LTS 19.5.2": https://github.com/thehcginstitute-com/m1/issues/34 -->
            <small><?php echo $this->helper('sales')->__('Grand Total to be Charged') ?></small>
        </td>
        <td class="a-right nonecell">
            <small><?php echo $this->displayBaseGrandtotal() ?></small>
        </td>
    </tr>
    <?php endif?>
</tfoot>
<?php endif ?>