<?php
# 2024-01-10 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Port the modifications of `app/design/frontend/base/default/template/checkout/onepage/payment.phtml`
# to Magento 1.9.4.5": https://github.com/thehcginstitute-com/m1/issues/112
?>
<script type="text/javascript">

//<![CDATA[
	var quoteBaseGrandTotal = <?php echo (float)$this->getQuoteBaseGrandTotal(); ?>;
	var checkQuoteBaseGrandTotal = quoteBaseGrandTotal;
	var quoteGrandTotalClean = quoteBaseGrandTotal;
	var payment = new Payment('co-payment-form', '<?php echo $this->getUrl('checkout/onepage/savePayment') ?>');
	var lastPrice;
//]]>
</script>
<?php
# 2024-01-10 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the modifications of `app/design/frontend/base/default/template/checkout/onepage/payment.phtml`
# to Magento 1.9.4.5": https://github.com/thehcginstitute-com/m1/issues/112
# 2) https://github.com/thehcginstitute-com/m1/blob/2023-12-24/app/design/frontend/base/default/template/checkout/onepage/payment.phtml#L35-L39
# 2024-01-15 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) The template is not cached, so we can use `Mage::getSingleton('customer/session')->getCustomerGroupId()` here.
# 2) "Delete the `Mage::getSingleton('customer/session')->getCustomerGroupId()` call from cached `*.phtml` files":
# https://github.com/thehcginstitute-com/m1/issues/238
if (hcg_customer_is_new()) {
	echo $this->getLayout()->createBlock('cms/block')->setBlockId('checkout-page')->toHtml();
} ?>
<form action="" id="co-payment-form">
<!-- 2024-01-10 Dmitrii Fediuk https://upwork.com/fl/mage2pro
1) "Port the modifications of `app/design/frontend/base/default/template/checkout/onepage/payment.phtml`
to Magento 1.9.4.5": https://github.com/thehcginstitute-com/m1/issues/112
2) https://github.com/thehcginstitute-com/m1/blob/2023-12-24/app/design/frontend/base/default/template/checkout/onepage/payment.phtml#L41 -->
	<fieldset id='checkout-payment-method-load'>
		<?php echo $this->getChildHtml('methods') ?>
	</fieldset>
	<?php echo $this->getBlockHtml('formkey') ?>
</form>
<div class="tool-tip" id="payment-tool-tip" style="display:none;">
	<div class="btn-close"><a href="#" id="payment-tool-tip-close" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Close')) ?>"><?php echo $this->__('Close') ?></a></div>
	<div class="tool-tip-content"><img src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Card Verification Number Visual Reference')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Card Verification Number Visual Reference')) ?>" /></div>
</div>
<div class="buttons-set" id="payment-buttons-container">
	<p class="required"><?php echo $this->__('* Required Fields') ?></p>
	<p class="back-link"><a href="#" onclick="checkout.back(); return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	<button type="button" class="button" onclick="payment.save()"><span><span><?php echo $this->__('Continue') ?></span></span></button>
	<span class="please-wait" id="payment-please-wait" style="display:none;">
		<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Loading next step...')) ?>" class="v-middle" /> <?php echo $this->__('Loading next step...') ?>
	</span>
</div>
<script type="text/javascript">
//<![CDATA[
	function toggleToolTip(event){
		if($('payment-tool-tip')){
			$('payment-tool-tip').setStyle({
				top: (Event.pointerY(event)-560)+'px'//,
				//left: (Event.pointerX(event)+100)+'px'
			})
			$('payment-tool-tip').toggle();
		}
		Event.stop(event);
	}
	if($('payment-tool-tip-close')){
		Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
	}
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
	payment.currentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
//]]>
</script>
