<form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail">
    <div class="form-subscribe">
    <div class="form-subscribe-header"><?php echo $this->__('Join our newsletter for lots of great offers and information about our products and services') ?></div>
        <label for="newsletter"><?php echo $this->__('Newsletter Sign-up:') ?></label>
        <div class="input-box">
           <input
			   class="input-text required-entry validate-email"
			   id="newsletter"
			   name="email"
<?php # 2024-01-21 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `app/design/frontend/base/default/template/newsletter/subscribe.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/227
# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/newsletter/subscribe.phtml#L37
?>
			   title="<?= Mage::helper('core')->quoteEscape($this->__('Sign up for our newsletter')) ?>"
			   type="text"
		   />
        </div>
        <button
			class="button"
<?php # 2024-01-21 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `app/design/frontend/base/default/template/newsletter/subscribe.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/227
# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/newsletter/subscribe.phtml#L40
?>
			title="<?= Mage::helper('core')->quoteEscape($this->__('Submit')) ?>"
			type="submit"
		><span><span><?= $this->__('Submit') ?></span></span></button>
    </div>
</form>
<script type="text/javascript">
//<![CDATA[
    var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
    new Varien.searchForm('newsletter-validate-detail', 'newsletter', '<?php echo $this->helper('newsletter')->__('Enter your email address') ?>');
//]]>
</script>
