<?php /** @var Mage_Page_Block_Html_Head $this */ ?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->
<style>
#nav iframe {
    visibility: hidden;
    display: none;
}

</style>
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
<script type="text/javascript" src="<?=$this->getSkinUrl('js/ddaccordion.js');?>" defer="defer"></script>
<script type="text/javascript" src="<?=$this->getSkinUrl('js/accordion.js');?>" defer="defer"></script>

<link href="<?=$this->getSkinUrl('font/stylesheet.css');?>" rel="stylesheet">
<link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css' rel="stylesheet" type="text/css">
<!-- 2023-01-14 Dmitrii Fediuk https://www.upwork.com/fl/mage2pro
"Refactor hardcoded base URLs": https://github.com/thehcginstitute-com/m1/issues/2 -->
<link
	as="font"
	crossorigin
	href="<?= $this->getSkinUrl('font/lato-regular-webfont.woff2') ?>"
	rel='preload'
	type="font/woff2"
>
<link
	as="font"
	crossorigin
	href="<?= $this->getSkinUrl('font/raleway-regular-webfont.woff2') ?>"
	rel='preload'
	type="font/woff2"
>
<link
	as="font"
	crossorigin
	href="<?= $this->getSkinUrl('font/lato-bold-webfont.woff2') ?>"
	rel='preload'
	type="font/woff2"
>
