<?php /**  @var Mage_Page_Block_Html_Header $this */
# 2023-12-24 "The main logo link address should not be hardcoded": https://github.com/thehcginstitute-com/m1/issues/72
$url = HCG_WP_Settings::url(); /** @var string $url */
?>

<div class="top_block">
	<?= $this->getChildHtml('topLinks') ?>
	<div class="clear"></div>
	<?= $this->getChildHtml('topContainer'); ?>
</div>
<div class="header-container">
	<div class="header">
		<?php if ($this->getIsHomePage()): ?>
			<h1 class="logo">
				<strong><?= $this->getLogoAlt() ?></strong>
				<a class="logo" href="<?= $url;?>" title="<?= $this->getLogoAlt() ?>"
				><img alt="<?= $this->getLogoAlt() ?>" src="<?= $this->getLogoSrc() ?>"/></a>
			</h1>
		<?php else:?>
			<div class="logo">
				<strong><?= $this->getLogoAlt() ?></strong>
				<a class="logo" href="<?= $url;?>" title="<?= $this->getLogoAlt() ?>"
				><img alt="<?= $this->getLogoAlt() ?>" src="<?= $this->getLogoSrc() ?>"/></a>
			</div>
		<?php endif?>
		<?= $this->getChildHtml('topMenu') ?>
	</div>
</div>
<?= $this->getChildHtml('topBar') ?>