<?php
/**
 * @var $this IWD_OrderManager_Block_Adminhtml_Sales_Order_Payment_Form
 */
$helper = Mage::helper('iwd_ordermanager');
?>

<form id="iwd_payment_edit_form" method="post">
    <div id="order-billing_method" class="payments">
        <script type="text/javascript">
            var order = new AdminOrder(<?php echo $this->getOrderDataJson() ?>);
            order.setLoadBaseUrl('<?php echo $this->getLoadBlockUrl() ?>');
            var payment = {};
            payment.switchMethod = order.switchPaymentMethod.bind(order);

            <?php /* IWD Stripe */ ?>
            <?php if(Mage::getConfig()->getModuleConfig('IWD_Stripe')->is('active', 'true')): ?>
                IWD.Stripe.init();
            <?php endif; ?>
            <?php /* IWD Stripe */ ?>
        </script>

        <fieldset>
            <?php if ($this->hasMethods()): ?>
                <div id="order-billing_method_form">
                    <dl class="payment-methods">
                        <?php
                        $methods = $this->getMethods();
                        $methodsCount = count($methods);
                        $counter = 0;
                        ?>
                        <?php foreach ($methods as $method): $code = $method->getCode(); $counter++; ?>
                            <dt>
                                <?php if ($methodsCount > 1): ?>
                                    <input id="p_method_<?php echo $code ?>" value="<?php echo $code ?>" type="radio"
                                           name="payment[method]"
                                           title="<?php echo $this->htmlEscape($method->getTitle()) ?>"
                                           onclick="payment.switchMethod('<?php echo $code ?>')"<?php if ($this->getSelectedMethodCode() == $code): ?> checked="checked"<?php endif; ?>
                                           <?php if ($counter == $methodsCount) : ?>class="validate-one-required-by-name"<?php endif; ?>/>
                                <?php else : ?>
                                    <span class="no-display">
                                        <input id="p_method_<?php echo $code ?>"
                                            value="<?php echo $code ?>" type="radio"
                                            name="payment[method]" checked="checked"/>
                                    </span>
                                <?php endif; ?>

                                <label for="p_method_<?php echo $code ?>"><?php echo $method->getTitle() ?></label>
                            </dt>
                            <dd>
                                <?php echo $this->getChildHtml('payment.method.' . $code) ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                </div>
                <script type="text/javascript">order.setPaymentMethod('<?php echo $this->getSelectedMethodCode() ?>')</script>
            <?php else: ?>
                <div><?php echo $helper->__('No Payment Methods') ?></div>
            <?php endif; ?>

            <?php
                echo Mage::app()->getLayout()->createBlock('adminhtml/template')
                    ->setTemplate("iwd/ordermanager/controls.phtml")
                    ->setData("button_onclick_update", "IWD.OrderManager.Payment.editPaymentSubmit()")
                    ->setData("button_onclick_cancel", "IWD.OrderManager.Payment.editPaymentCancel()")
                    ->setData('recalculate', false)
# 2024-02-04 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused «Reauthorize» feature from IWD Order Manager": https://github.com/thehcginstitute-com/m1/issues/362
                    ->setData('block', 'payment')
                    ->toHtml();
            ?>
        </fieldset>
    </div>
</form>
