<?php
	# 2024-01-15 Dmitrii Fediuk https://upwork.com/fl/mage2pro
	# 1) The template is not cached, so we can use `Mage::getSingleton('customer/session')->getCustomerGroupId()` here.
	# 2) "Delete the `Mage::getSingleton('customer/session')->getCustomerGroupId()` call from cached `*.phtml` files":
	# https://github.com/thehcginstitute-com/m1/issues/238
    $customerGroupId = Mage::getSingleton('customer/session')->getCustomerGroupId();    
?>
<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('My Account'); ?></span></strong>
    </div>
    <div class="block-content">
	
        <ul>
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php $_count = count($_links); ?>
            <?php foreach ($_links as $_link): ?>
			    <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>" <?php if($customerGroupId =='4' && ($_link->getLabel() =='Orders & Refills' || $_link->getLabel() == 'Wishlist' ) ){ echo "id=hideme";} ?>><strong>
					<?php echo $_link->getLabel() ?></strong></li>
                <?php else: ?>
                    <li<?php echo ($_last ? ' class="last "' : '') ?> <?php if($customerGroupId =='4' && ($_link->getLabel() =='Orders & Refills' || $_link->getLabel() == 'Wishlist' )){ echo "id=hideme";} ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
