<?php
# 2024-03-03 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Refactor the `app/design/frontend/default/mobileshoppe/template/customer/account/navigation.phtml` template":
# https://github.com/thehcginstitute-com/m1/issues/441
use Varien_Object as O;
/** @var HetNieuweWeb_CustomerNavigation_Block_Customer_Account_Navigation $this */
# 2024-01-15 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) The template is not cached, so we can use `Mage::getSingleton('customer/session')->getCustomerGroupId()` here.
# 2) "Delete the `Mage::getSingleton('customer/session')->getCustomerGroupId()` call from cached `*.phtml` files":
# https://github.com/thehcginstitute-com/m1/issues/238
$isCustomerNew = hcg_customer_is_new(); /** @var bool $isCustomerNew */
?>
<div class="block block-account">
	<div class="block-title">
		<strong><span><?= $this->__('My Account'); ?></span></strong>
	</div>
	<div class="block-content">
		<ul>
			<?php
				$ll = $this->getLinks(); /** @var O[] $ll */
				$count = count($ll); /** @var int $count */
				$_index = 1;
				foreach ($ll as $l) { /** @var O $l */
					$_last = ($_index++ >= $count);
					if ($this->isActive($l)) { ?>
						<li
							class="current<?= ($_last ? ' last' : '') ?>"
							<?php
								if (
									$isCustomerNew
									&& ($l->getLabel() =='Orders & Refills' || $l->getLabel() == 'Wishlist' )) {
										echo "id=hideme";
								}
							?>
						><strong><?= $l->getLabel() ?></strong></li>
					<?php } else { ?>
						<li<?= ($_last ? ' class="last "' : '') ?>
							<?php if (
								$isCustomerNew
								&& ($l->getLabel() =='Orders & Refills' || $l->getLabel() == 'Wishlist' )) {
									echo "id=hideme";
							} ?>
						><a href="<?= $l->getUrl() ?>"><?= $l->getLabel() ?></a></li>
				<?php } ?>
			<?php } ?>
		</ul>
	</div>
</div>