<?php
	# 2024-01-15 Dmitrii Fediuk https://upwork.com/fl/mage2pro
	# 1) The template is not cached, so we can use `Mage::getSingleton('customer/session')->getCustomerGroupId()` here.
	# 2) "Delete the `Mage::getSingleton('customer/session')->getCustomerGroupId()` call from cached `*.phtml` files":
	# https://github.com/thehcginstitute-com/m1/issues/238
	# 2024-03-03 Dmitrii Fediuk https://upwork.com/fl/mage2pro
	# "Refactor the `app/design/frontend/default/mobileshoppe/template/customer/account/navigation.phtml` template":
	# https://github.com/thehcginstitute-com/m1/issues/441
	$isCustomerNew = hcg_customer_is_new(); /** @var bool $isCustomerNew */
?>
<div class="block block-account">
	<div class="block-title">
		<strong><span><?= $this->__('My Account'); ?></span></strong>
	</div>
	<div class="block-content">
		<ul>
			<?php
				$_links = $this->getLinks();
				$_index = 1;
				$_count = count($_links);
				foreach ($_links as $_link) {
					$_last = ($_index++ >= $_count);
					if ($this->isActive($_link)) { ?>
						<li
							class="current<?= ($_last ? ' last' : '') ?>"
							<?php
								if (
									$isCustomerNew
									&& ($_link->getLabel() =='Orders & Refills' || $_link->getLabel() == 'Wishlist' )) {
										echo "id=hideme";
								}
							?>
						><strong><?= $_link->getLabel() ?></strong></li>
					<?php } else { ?>
						<li<?= ($_last ? ' class="last "' : '') ?>
							<?php if (
								$isCustomerNew
								&& ($_link->getLabel() =='Orders & Refills' || $_link->getLabel() == 'Wishlist' )) {
									echo "id=hideme";
							} ?>
						><a href="<?= $_link->getUrl() ?>"><?= $_link->getLabel() ?></a></li>
				<?php } ?>
			<?php } ?>
		</ul>
	</div>
</div>