<?php
# 2024-01-15 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) The template is not cached, so we can use `Mage::getSingleton('customer/session')->getCustomerGroupId()` here.
# 2) "Delete the `Mage::getSingleton('customer/session')->getCustomerGroupId()` call from cached `*.phtml` files":
# https://github.com/thehcginstitute-com/m1/issues/238
$customerGroupId = Mage::getSingleton('customer/session')->getCustomerGroupId();
?>
<div class="welcome-msg">
    <p class="hello"><strong><?php echo $this->__('Hello, %s!', $this->escapeHtml($this->getCustomerName())) ?></strong></p>
	<?php if($customerGroupId==4): ?>
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('patient')->toHtml() ?>
    <p><?php //echo $this->__('From your My Account Dashboard you have the ability to view a snapshot of your recent account activity and update your account information. Select a link below to view or edit information.') ?></p>
	<?php else: ?>
	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('new-health-profile')->toHtml() ?>
	<?php endif; ?>
</div>