<?php
# 2024-01-15 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) The template is not cached, so we can use `Mage::getSingleton('customer/session')->getCustomerGroupId()` here.
# 2) "Delete the `Mage::getSingleton('customer/session')->getCustomerGroupId()` call from cached `*.phtml` files":
# https://github.com/thehcginstitute-com/m1/issues/238
?>
<div class="welcome-msg">
    <p class="hello"><strong><?php echo $this->__('Hello, %s!', $this->escapeHtml($this->getCustomerName())) ?></strong></p>
	<?php if(hcg_is_patient()): ?>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('patient')->toHtml() ?>
	<?php else: ?>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('new-health-profile')->toHtml() ?>
	<?php endif ?>
</div>