<?php $_code=$this->getMethodCode() ?>


<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">   
 
	 <li>
        <label for="<?php echo $_code ?>_check_no" class="required"><em><img style="width:25px" src="<?php echo $this->getSkinUrl('images/redmanu.png') ?>" alt=""/></em><?php echo $this->__('Routing Number') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Routing Number') ?>" class="input-text required-entry" id="<?php echo $_code ?>_check_no" name="payment[check_no]" value="<?php echo $this->htmlEscape($this->getInfoData('check_no')) ?>" />
        </span>
    </li> 
    <li>
        <label for="<?php echo $_code ?>_check_date" class="required"><em><img style="width:25px" src="<?php echo $this->getSkinUrl('images/blue1.png') ?>" alt=""/></em><?php echo $this->__('Account Number') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Account Number') ?>" class="input-text required-entry" id="<?php echo $_code ?>_check_date" name="payment[check_date]" value="<?php echo $this->htmlEscape($this->getInfoData('check_date')) ?>" />
        </span>
    </li>
	<li>
        <label for="<?php echo $_code ?>_check_no" class="required"><em>*</em><?php echo $this->__('Bank Name') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Bank Name') ?>" class="input-text required-entry" id="<?php echo $_code ?>_check_no" name="payment[bank_name]" value="<?php echo $this->htmlEscape($this->getInfoData('bank_name')) ?>" />
        </span>
    </li> 
	 <li>
        <label for="<?php echo $_code ?>_check_no" class="required"><em>*</em><?php echo $this->__('Account Holder Name') ?></label>
        <span class="input-box">
            <input type="text" title="<?php echo $this->__('Account Holder Name') ?>" class="input-text required-entry" id="<?php echo $_code ?>_check_no" name="payment[account_holder_name]" value="<?php echo $this->htmlEscape($this->getInfoData('account_holder_name')) ?>" />
        </span>
    </li> 
	
	<li><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('checkout-image')->toHtml(); ?><li>
	 
</ul>
<div>
	<?php echo $this->getMethod()->getConfigData('message');?>
</div>

