<?php
# 2024-01-09 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# Port the modifications of `app/design/frontend/base/default/template/payment/info/default.phtml` to Magento 1.9.4.5
# https://github.com/thehcginstitute-com/m1/issues/102
use Mage_Payment_Block_Info as B; /** @var B $this */
?>
<p><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>
<!-- 2024-01-09 Dmitrii Fediuk https://upwork.com/fl/mage2pro
 "Hide bank card credentials from its owner on order information screens":
 https://github.com/thehcginstitute-com/m1/issues/143 -->
<?php echo $this->getChildHtml()?>