<?php
# 2024-01-09 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# Port the modifications of `app/design/frontend/base/default/template/payment/info/default.phtml` to Magento 1.9.4.5
# https://github.com/thehcginstitute-com/m1/issues/102
use Mage_Payment_Block_Info as B; /** @var B $this */
?>
<p><strong><?php echo $this->escapeHtml($this->getMethod()->getTitle()) ?></strong></p>

<?php if ($_specificInfo = $this->getSpecificInformation()):?>
<table>
	<tbody>
	<?php foreach ($_specificInfo as $_label => $_value):?>
		<tr>
			<th><strong><?php echo $this->escapeHtml($_label)?>:</strong></th>
		</tr>
		<tr>
			<td><?php echo nl2br(implode($this->getValueAsArray($_value, true), "\n"))?></td>
		</tr>
	<?php endforeach; ?>
	</tbody>
</table>
<?php endif;?>

<?php echo $this->getChildHtml()?>
