<?php
use Mage_Catalog_Block_Seo_Sitemap_Abstract as SA;
use Mage_Catalog_Block_Seo_Sitemap_Category as SC;
use Mage_Catalog_Block_Seo_Sitemap_Product as SP;
/** @var SA|SC|SP $this */ $b = $this; /** @var SA|SC|SP $b */
?>
<?php $_items = $b->getCollection(); ?>
<?php if($_items->getSize()): ?>
	<ul class="sitemap">
		<?php foreach ($_items as $_item): ?>
			<li><a href="<?= $b->getItemUrl($_item) ?>"><?= $b->escapeHtml($_item->name) ?></a></li>
		<?php endforeach ?>
	</ul>
<?php else: ?>
	<p class="note-msg">
		<?= $b->__('There are no %s available.', $this->getItemsTitle()); ?>
	</p>
	<script type="text/javascript">
		if ($('sitemap_top_links') != undefined) {
			$('sitemap_top_links').hide();
		}
	</script>
<?php endif ?>