<?php
use Mage_Catalog_Block_Seo_Sitemap_Tree_Category as B;
/** @var B $this */ $b = $this; /** @var B $b */
?>
<?php $_items = $b->getCollection(); ?>
<?php if($_items->getSize()): ?>
	<ul class="sitemap">
		<?php foreach ($_items as $_item): ?>
			<?php if ($_item->getIsActive()): ?>
				<li class="level-<?= $b->getLevel($_item) ?>" <?= $b->getLevel($_item)?'style="padding-left:' . $b->getLevel($_item, 2) . '0px;"':'' ?>><a href="<?= $b->getItemUrl($_item) ?>"><?= $_item->name ?></a></li>
			<?php endif ?>
		<?php endforeach ?>
	</ul>
<?php else: ?>
	<p class="note-msg">
		<?= $b->__('There are no %s available.', $this->getItemsTitle()); ?>
	</p>
<?php endif ?>