<?php /** @var Mage_Catalog_Block_Product_View_Media $this */
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<div id="galleria">
	<?php
		$_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(500).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
		echo $_helper->productAttribute($_product, $_img, 'image');
	?>
	<?php foreach ($this->getGalleryImages() as $_image): ?>
		   <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(500); ?>" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
	<?php endforeach; ?>
</div>
<script type="text/javascript">
//<![CDATA[
	   // Initialize Galleria
jQuery('#galleria').galleria({
	responsive: true,
	lightbox: true,
	swipe: true
});
//]]>
</script>
<?php endif; ?>