<?php # 2024-02-06 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
use Mage_Tax_Block_Sales_Order_Tax as B; /** @var B $this */ $b = $this; /** @var B $b */
$_order  = $b->getOrder();
$_source = $b->getSource();
$_fullInfo = $_order->getFullTaxInfo();
global $taxIter; $taxIter++;
$hasItemsInTaxSection = 0;
if ($b->displayFullSummary()): ?>
<?php $isTop = 1; ?>
	<?php if ($_fullInfo) foreach ($_fullInfo as $info): ?>
		<?php if (isset($info['hidden']) && $info['hidden']) continue; ?>
		<?php
			$percent    = $info['percent'];
			$amount     = $info['amount'];
			$rates      = $info['rates'];
			$isFirst    = 1;
		?>
		<?php foreach ($rates as $rate): ?>
		<tr class="summary-details-<?= $taxIter; ?> summary-details<?php if ($isTop): echo ' summary-details-first'; endif ?>"<?php if (!$b->getIsPlaneMode()): ?> style="display:none;"<?php endif ?>>
			<td <?= $b->getLabelProperties()?>>
				<?= $b->escapeHtml($rate['title']); ?>
				<?php if (!is_null($rate['percent'])): ?>
					(<?= (float)$rate['percent']; ?>%)
				<?php endif ?>
				<br />
			</td>
			<?php if ($isFirst): ?>
				<td <?= $b->getValueProperties()?> rowspan="<?= count($rates); ?>">
					<?= $_order->formatPrice($amount); ?>
				</td>
			<?php endif ?>
		</tr>
		<?php $isFirst = 0; ?>
		<?php $isTop = 0; ?>
		<?php $hasItemsInTaxSection = 1 ?>
		<?php endforeach ?>
	<?php endforeach ?>
<?php endif;
if ($b->displayFullSummary() && $hasItemsInTaxSection && !$b->getIsPlaneMode()): ?>
<tr class="summary-total" onclick="expandDetails(this, '.summary-details-<?= $taxIter;?>')">
<?php elseif ($b->displayFullSummary() && $hasItemsInTaxSection && $b->getIsPlaneMode()): ?>
<tr class="show-details">
<?php else: ?>
<tr>
<?php endif ?>
	<td <?= $b->getLabelProperties()?>>
		<?php if ($b->displayFullSummary() && !$b->getIsPlaneMode()): ?>
			<div class="summary-collapse"><?= $b->__('Tax'); ?></div>
		<?php else: ?>
			<?= $b->__('Tax'); ?>
		<?php endif ?>
	</td>
	<td <?= $b->getValueProperties()?>><?= $_order->formatPrice($_source->getTaxAmount()) ?></td>
</tr>
