<label for="<?php echo $this->getFieldId('group_id')?>"<?php if ($this->isRequired()) echo ' class="required"' ?>><?php if ($this->isRequired()) echo '<em>*</em>' ?><?php echo $this->getGroupLabel() ?></label>
<div class="input-box">
	<?php
	$helper				        = Mage::helper('magepsycho_customerregfields');
	$isGroupEditable	        = $helper->cfgH()->isGroupSelectionEditable();
	$isValidCustomerForEdit     = $helper->isValidCustomerForEdit();
	?>
	<?php if ( ($this->getIsEditPage() && ! $isGroupEditable) || ($this->getIsEditPage() && ! $isValidCustomerForEdit) ) : ?>
		<?php
		$groupId    = $this->getObject()->getGroupId();
		$group      = Mage::getModel('customer/group')->load($groupId);
		echo $group->getCustomerGroupCode();
		?>
	<?php else : ?>
		<select id="<?php echo $this->getFieldId('group_id')?>" name="<?php echo $this->getFieldName('group_id')?>" title="<?php echo Mage::helper('core')->quoteEscape($this->getGroupLabel()) ?>"<?php if ($this->isRequired()): ?> class="validate-select"<?php endif; ?> <?php echo $this->getFieldParams() ?>>
			<?php $options  = $this->getGroupSelectOptions(); ?>
			<?php $value    = $this->getObject()->getGroupId(); ?>
			<?php foreach ($options as $option): ?>
				<option value="<?php echo $option['value'] ?>"<?php if ($option['value'] == $value) echo ' selected="selected"' ?>><?php echo $option['label'] ?></option>
			<?php endforeach;?>
		</select>
	<?php endif ?>

</div>