<?php if ($this->isShow()): ?>
    <label for="store_switcher"><?php echo Mage::helper('sales')->__('Store View') ?>:</label>
    <select name="store_switcher" id="store_switcher" onchange="return switchStore(this);">
        <?php foreach ($this->getWebsiteCollection() as $website): ?>
            <optgroup label="<?php echo $website->getName() ?>">
            <?php foreach ($this->getGroupCollection($website) as $group): ?>
                <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $group->getName() ?>">
                <?php foreach ($this->getStoreCollection($group) as $_store): ?>
                    <option value="<?php echo $_store->getId() ?>"
                        <?php if($this->getStoreId() == $_store->getId()): ?> selected<?php endif ?>>
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $_store->getName() ?>
                    </option>
                <?php endforeach ?>
                </optgroup>
            <?php endforeach ?>
            </optgroup>
        <?php endforeach ?>
    </select>
    <script type="text/javascript">
        function switchStore(obj) {
            order.setStoreId(obj.value);
        }
        AdminOrder.updateStoreUrl = '<?php echo Mage::getUrl('*/sales_create/updateStore') ?>';
    </script>
<?php endif ?>
