<?php
# 2024-09-16 Dmitrii Fediuk https://upwork.com/fl/mage2pro
use Mage_Sales_Block_Order_Totals as B;
/** @var B $this */ $b = $this; /** @var B $b */
foreach ($b->getTotals() as $_code => $_total) {
	if ($_total->getBlockName()): ?>
		<?= $b->getChildHtml($_total->getBlockName(), false); ?>
	<?php else: ?>
	<tr class="<?= $_code?>">
		<td <?= $b->getLabelProperties()?>>
			<?php if ($_total->getStrong()):?>
			<strong><?= $b->escapeHtml($_total->getLabel());?></strong>
			<?php else: ?>
			<?= $b->escapeHtml($_total->getLabel());?>
			<?php endif ?>
		</td>
		<td <?= $b->getValueProperties()?>>
			<?php if ($_total->getStrong()):?>
			<strong><?= $b->formatValue($_total) ?></strong>
			<?php else: ?>
			<?= $b->formatValue($_total) ?>
			<?php endif ?>
		</td>
	</tr>
	<?php endif;
}