<?php
# 2024-01-09 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Port the modifications of `app/design/frontend/base/default/template/catalog/category/view.phtml` to Magento 1.9.4.5":
# https://github.com/thehcginstitute-com/m1/issues/100
use Mage_Catalog_Block_Category_View as B; /** @var B $this */
	$_helper    = $this->helper('catalog/output');
	$_category  = $this->getCurrentCategory();
	$_imgHtml   = '';
	if ($_imgUrl = $_category->getImageUrl()) {
		$_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
		$_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
	}
?>
<div class="page-title category-title">
	<?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
		<a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
	<?php endif; ?>
	<h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php if($_imgUrl): ?>
	<?php echo $_imgHtml ?>
<?php endif; ?>

<?php if ($_description=$this->getCurrentCategory()->getDescription()) { ?>
	<div class="category-description std">
		<?=
			# 2024-01-09 Dmitrii Fediuk https://upwork.com/fl/mage2pro
			# 1) "Port the modifications of `app/design/frontend/base/default/template/catalog/category/view.phtml` to Magento 1.9.4.5":
			# https://github.com/thehcginstitute-com/m1/issues/100
			# 2) https://github.com/thehcginstitute-com/m1/blob/2023-12-24/app/design/frontend/base/default/template/catalog/category/view.phtml#L57-L75
			# 2024-01-15 Dmitrii Fediuk https://upwork.com/fl/mage2pro
			# @todo "Checking for the customer group via a PHP code
			# in `app/design/frontend/default/mobileshoppe/template/catalog/category/view.phtml` is wrong
			# because the file is cached": https://github.com/thehcginstitute-com/m1/issues/240
			/** @var int  $gid */
			!($gid = (int)Mage::getSingleton('customer/session')->getCustomerGroupId())
			? $_helper->categoryAttribute($_category, $_description, 'description')
			: $this->getLayout()->createBlock('cms/block')
				->setBlockId(1 === $gid ? 'patient-message' : 'nhp-message')
				->toHtml()
		?>
	</div>
<?php } ?>

<?php if($this->isContentMode()): ?>
	<?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
	<?php echo $this->getCmsBlockHtml() ?>
	<?php echo $this->getProductListHtml() ?>

<?php else: ?>
	<?php echo $this->getProductListHtml() ?>
<?php endif; ?>
