<?php /**@var Mage_Adminhtml_Block_Catalog_Product_Price $this */
# 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro 
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
$_coreHelper = $this->helper('core'); /** @var Mage_Core_Helper_Data $_coreHelper */
$_taxHelpern = $this->helper('tax');  /** @var $_taxHelper Mage_Tax_Helper_Data */
$_product = $this->getProduct();
$_id = $_product->getId();
$_storeId = $_product->getStoreId();
$_website = Mage::app()->getStore($_storeId)->getWebsite();
$_simplePricesTax   = ($_taxHelper->displayPriceIncludingTax() || $_taxHelper->displayBothPrices());
$_minimalPriceValue = $_product->getMinimalPrice();
$_minimalPrice      = $_taxHelper->getPrice($_product, $_minimalPriceValue, $_simplePricesTax);
$_exclTax = $_taxHelper->getPrice($_product, $_minimalPriceValue, $includingTax = null);
$_inclTax = $_taxHelper->getPrice($_product, $_minimalPriceValue, $includingTax = true);
?>
<div class="price-box">
	<?php 
		$_price = $_taxHelper->getPrice($_product, $_product->getPrice());
		$_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice(), $_simplePricesTax);
		$_finalPrice = $_taxHelper->getPrice($_product, $_product->getFinalPrice()); 
		$_finalPriceInclTax = $_taxHelper->getPrice($_product, $_product->getFinalPrice(), true);
		if ($_finalPrice == $_price) { 
			if ($_taxHelper->displayBothPrices()) { ?>
				<span class="price-excluding-tax">
					<span class="label"><?= $this->helper('tax')->__('Excl. Tax:') ?></span>
					<span class="price" id="price-excluding-tax-<?= $_id ?><?= $this->getIdSuffix() ?>">
						<?= $_coreHelper->currencyByStore($_price, $_storeId, true, false) ?>
					</span>
				</span>
				<span class="price-including-tax">
					<span class="label"><?= $this->helper('tax')->__('Incl. Tax:') ?></span>
					<span class="price" id="price-including-tax-<?= $_id ?><?= $this->getIdSuffix() ?>">
						<?= $_coreHelper->currencyByStore($_finalPriceInclTax, $_storeId, true, false) ?>
					</span>
				</span>
			<?php } else { ?>
				<span class="regular-price" id="product-price-<?= $_id ?><?= $this->getIdSuffix() ?>">
					<?= $_coreHelper->currencyByStore($_price, $_storeId, true, true) ?>
				</span>
		<?php } ?>
	<?php } else { ?>
		<p class="old-price">
			<span class="price-label"><?= $this->__('Regular Price:') ?></span>
			<span class="price" id="old-price-<?= $_id ?><?= $this->getIdSuffix() ?>">
				<?= $_coreHelper->currencyByStore($_regularPrice, $_storeId, true, false) ?>
			</span>
		</p>
		<?php if ($_taxHelper->displayBothPrices()) { ?>
			<p class="special-price">
				<span class="price-label"><?= $this->__('Special Price:') ?></span>
				<span class="price-excluding-tax">
					<span class="label"><?= $this->helper('tax')->__('Excl. Tax:') ?></span>
					<span class="price" id="price-excluding-tax-<?= $_id ?><?= $this->getIdSuffix() ?>">
						<?= $_coreHelper->currencyByStore($_finalPrice, $_storeId, true, false) ?>
					</span>
				</span>
				<span class="price-including-tax">
					<span class="label"><?= $this->helper('tax')->__('Incl. Tax:') ?></span>
					<span class="price" id="price-including-tax-<?= $_id ?><?= $this->getIdSuffix() ?>">
						<?= $_coreHelper->currencyByStore($_finalPriceInclTax, $_storeId, true, false) ?>
					</span>
				</span>
			</p>
		<?php } else { ?>
			<p class="special-price">
				<span class="price-label"><?= $this->__('Special Price:') ?></span>
				<span class="price" id="product-price-<?= $_id ?><?= $this->getIdSuffix() ?>">
					<?= $_coreHelper->currencyByStore($_finalPrice, $_storeId, true, false) ?>
				</span>
			</p>
		<?php 
		}
	}
	if ($this->getDisplayMinimalPrice() && $_minimalPriceValue && $_minimalPriceValue < $_product->getFinalPrice()) {		$_minimalPriceDisplayValue = $_minimalPrice;
		if ($this->getUseLinkForAsLowAs()) { ?>
			<a href="<?= $_product->getProductUrl(); ?>" class="minimal-price-link">
		<?php } else { ?>
			<span class="minimal-price-link">
		<?php } ?>
			<span class="label"><?= $this->__('As low as:') ?></span>
			<span class="price" id="product-minimal-price-<?= $_id ?><?= $this->getIdSuffix() ?>">
				<?= $_coreHelper->currencyByStore($_minimalPriceDisplayValue, $_storeId, true, false) ?>
			</span>
		<?php if ($this->getUseLinkForAsLowAs()) { ?> </a> <?php } else { ?> </span> <?php }
	} ?>
</div>