<?php
# 2024-09-01 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Refactor the `Ebizmarts_MailChimp` module": https://github.com/cabinetsbay/site/issues/524
# 2) "Improve the «Yaay! Recovered by Mailchimp's campaign» block of the backend order screen":
# https://github.com/thehcginstitute-com/m1/issues/668
use Ebizmarts_MailChimp_Block_Adminhtml_Sales_Order_View_Info_Monkey as B; /** @var B $this */
if($this->isReferred()) :
?>
<div class="entry-edit box-right">
	<div class="entry-edit-head">
		<h4 class="icon-head"><?= $this->escapeQuote($this->__('MailChimp')) ?></h4>
	</div>
	<fieldset>
		<div id="mailchimp_monkey">
			<table class="form-list" cellspacing="0">
				<tr>
					<td class="label">
						<img src="<?= $this->escapeHtml(
							$this->getSkinUrl('ebizmarts/mailchimp/images/logo-freddie-monocolor-200.png')
						) ?>"
							 width="40"
							 title="hep hep thanks Mailchimp" />
					</td>
					<td class="value">
						<?php if ($this->isDataAvailable()): ?>
							<strong><?= (
								$this->__("Yaay! Recovered by Mailchimp's campaign.") .
									"<br />" .
									$this->__("Name") .
									": " .
									$this->getCampaignName() .
									"<br />" .
								$this->__("Id") . ": " . $this->getCampaignId()
							) ?>
							</strong>
						<?php else: ?>
							<strong><?= $this->escapeQuote(
								$this->__("The campaign does not belong to the audience configured for ") .
									$this->getStoreCodeFromOrder() .
								$this->__(" view.")
							); ?>
							</strong>
						<?php endif; ?>
					</td>
				</tr>
			</table>
		</div>
	</fieldset>
</div>
<div class="clear"></div>
<?php endif; ?>