<?php if ($this->buttonEnabled()): ?>
    <?php $import = $this->getImport(); ?>
    <?php $storeId = $import->getStoreId(); ?>

    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
    <script type="text/javascript">
        jQuery.noConflict();

        function import_richpanel() {
            var store_id     = <?php echo $storeId; ?>;
            var total_chunks = <?php echo $import->getChunks($storeId); ?>;
            var chunk_percentage = 100;
            if(total_chunks > 0){
                var chunk_percentage = (100 / total_chunks);
            }
            // Update button state and text
            jQuery('#richpanel_button').addClass('disabled').attr('disabled', 'disabled').text('Importing orders');

            var sync_chunk = function(chunk_id){
                progress_percents = Math.round(chunk_id * chunk_percentage);
                update_importing_message('Please wait... '+progress_percents+'% done', true);

                // add form_key for magento controller check
                data = {'store_id': store_id, 'chunk_id': chunk_id, 'form_key': window.FORM_KEY};
                jQuery.post('<?php echo $this->getAjaxUrl(); ?>', data, function(response) {
                    new_chunk_id = chunk_id + 1;
                    if(new_chunk_id < total_chunks){
                        setTimeout(function() {
                            sync_chunk(new_chunk_id);
                        }, 100);
                    }else{
                        update_importing_message("<span style='color: green;'>Done! Please expect up to 30 minutes for your historical data to appear in Richpanel.</span>", false);
                        jQuery('#richpanel_button').removeClass('disabled').addClass('success').text('Orders imported');
                    }

                });

            }

            var update_importing_message = function(message, show_loader){
                if (show_loader)
                    message = '<img src="<?php echo $this->getSkinUrl("richpanel/loader.gif"); ?>" />' + message;
                jQuery('#richpanel_import_status').html(message);
            }
            sync_chunk(0);
        }
    </script>

    <?php if ($this->showInStore()): ?>
        <div style="float: left;">
            <h3>Importing your orders and customers</h3>
            <p>
                This tool helps you sync all your orders and customers to Richpanel and can take <strong>up to 20 minutes</strong> to complete. <br />
                It will not affect your website's performance at all since it sends your orders to your Richpanel account in small chunks.  <br /><br />
                Make sure to <strong>not close this page</strong> while importing. Coffee, maybe?
            </p>
        </div>
        <div style="clear:both"></div>
        <?php echo $this->getButtonHtml() ?>
        <div style="clear:both"></div>
        <div id="richpanel_import_status"></div>
        <div style="clear:both"></div>
    <?php else: ?>
        <div style="float: left;">
            <p>
                In order to import your orders, please pick a store from
                <strong>Current Configuration Scope</strong> on the top left
                to make the import for the selected store.
            </p>
        </div>
        <div style="clear:both"></div>
    <?php endif; ?>
<?php endif; ?>
