<?php # 2024-02-14 Dmitrii Fediuk https://upwork.com/fl/mage2pro
/** @var Mage_Catalog_Block_Layer_Filter_Abstract $this */ ?>
<ul class="categoryitems" contentindex="0c" style="display: block;">
<?php foreach ($this->getItems() as $_item): ?>
    <li>
        <?php if ($_item->getCount() > 0): ?>
		<?php # 2024-02-14 Dmitrii Fediuk https://upwork.com/fl/mage2pro
		# "Upgrade Magento 1.9.4.5 to OpenMage LTS 19.5.2": https://github.com/thehcginstitute-com/m1/issues/34 ?>
        <a href="<?php echo $this->escapeUrl($_item->getUrl()) ?>"><?php echo $_item->getLabel() ?></a>
        <?php else: echo $_item->getLabel() ?>
        <?php endif ?>
        <?php if ($this->shouldDisplayProductCount()): ?>
        (<?php echo $_item->getCount() ?>)
        <?php endif ?>
    </li>
<?php endforeach ?>
</ul>