<!-- 2024-02-19 Dmitrii Fediuk https://upwork.com/fl/mage2pro
«Warning: include(app/design/adminhtml/base/default/template/Mlx/Mlx/page/menu.phtml):
failed to open stream: No such file or directory»": https://github.com/thehcginstitute-com/m1/issues/392 -->
<div class="nav-bar">
<!-- menu start -->
<?php echo $this->getMenuLevel($this->getMenuArray()); ?>
<!-- menu end -->

    <a id="page-help-link" href="<?php echo Mage::helper('adminhtml')->getPageHelpUrl() ?>"><?php echo $this->__('Get help for this page') ?></a>
    <script type="text/javascript">$('page-help-link').target = 'magento_page_help'</script>

</div>
