<?php
/**
 * Currency switcher
 *
 * @see Mage_Directory_Block_Currency
 */
?>
<?php if($this->getCurrencyCount()>1): ?>
<div class="block">
	<div class="block-title">
        <strong><span><?php echo $this->__('Your Currency') ?></span></strong>
    </div>
    <div class="block-content">
    <div class="top-currency show-on-phones">
    		<label for="currency"><?php echo $this->__('Currency:') ?></label>

        <select id="currency" title="<?php echo $this->__('Select Your Currency') ?>" onchange="setLocation(this.value)">
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>>
                <?php echo $_name ?> - <?php echo $_code ?>
            </option>
        <?php endforeach; ?>
        </select>
    </div>
    </div>
</div>    
<?php endif; ?>
