<?php /** @var Mage_Directory_Block_Currency $this */
if($this->getCurrencyCount()>1): ?>
<div class="block">
	<div class="block-title">
        <strong><span><?php echo $this->__('Your Currency') ?></span></strong>
    </div>
    <div class="block-content">
    <div class="top-currency show-on-phones">
    		<label for="currency"><?php echo $this->__('Currency:') ?></label>

        <select
			id="currency"
			onchange="setLocation(this.value)"
<?php # 2024-01-21 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `app/design/frontend/base/default/template/directory/currency.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/226
# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/directory/currency.phtml#L40 ?>
			title="<?= Mage::helper('core')->quoteEscape($this->__('Select Your Currency')) ?>"
		>
        <?php foreach ($this->getCurrencies() as $_code => $_name): ?>
            <option value="<?php echo $this->getSwitchCurrencyUrl($_code) ?>"<?php if($_code==$this->getCurrentCurrencyCode()): ?> selected="selected"<?php endif; ?>>
                <?php echo $_name ?> - <?php echo $_code ?>
            </option>
        <?php endforeach; ?>
        </select>
    </div>
    </div>
</div>    
<?php endif; ?>
