<?php
# 2024-09-06 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Replace the contents of unused (overridden) core backend template `sales/order/view/tab/info.phtml`
# with the contents of the really used corresponding custom template `iwd/ordermanager/order/view/tab/info.phtml`
# from `IWD_OrderManager`, and then delete the custom template file": https://github.com/cabinetsbay/site/issues/672
/**
 * @var $this Mage_Adminhtml_Block_Sales_Order_View_Tab_Info
 */
$order = $this->getOrder();
$helper = Mage::helper('iwd_ordermanager');
$isAllowEdit = Mage::getModel('iwd_ordermanager/order_edit')->checkOrderStatusForUpdate($order);
?>

<script type="text/javascript">
    var ORDER_ID = <?php echo $this->getOrder()->getId(); ?>;
</script>

<div>
    <div id="order-messages">
        <?php echo $this->getChildHtml('order_messages') ?>
    </div>
    <?php echo $this->getChildHtml('order_info') ?>
    <input type="hidden" name="order_id" value="<?php echo $order->getId() ?>"/>
    <?php if ($order->getIsVirtual()): ?>
    <div class="box-right">
        <?php else: ?>
        <div class="box-left">
            <?php endif ?>
            <!--Payment Method-->
            <div class="entry-edit">
                <div class="entry-edit-head">
                    <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('Payment Information') ?></h4>
                    <?php /*** BEGIN: add link "EDIT" ***/?>
                    <?php $isAllow = Mage::getSingleton('admin/session')->isAllowed('iwd_ordermanager/order/actions/edit_payment'); ?>
                    <?php if($isAllow): ?>
                        <div class="tools" style="float:right">
                            <?php if ($isAllowEdit && Mage::getModel('iwd_ordermanager/payment_payment')->canUpdatePaymentMethod($order->getId())) : ?>
                                <a id="order_payment_edit_<?php echo $order->getEntityId(); ?>"
                                   class="order_payment_edit" href="#"
                                   title="<?php echo $helper->__("Edit payment method"); ?>">
                                    <?php echo Mage::helper('sales')->__("Edit"); ?>
                                </a>
                            <?php else : ?>
                                <?php
                                $message = $isAllowEdit
                                    ? $helper->__("Sorry, but order has invoice(s). You can not edit payment method.")
                                    : $helper->__("Sorry, You can not update payment for order with this status. Check configuration by module IWD_OrderManager.");
                                ?>
                                <a href="#"
                                   onclick="alert('<?php echo $message ?>'); return false;"
                                   title="<?php echo $helper->__("You can not edit payment method!"); ?>">
                                    <?php echo Mage::helper('sales')->__("Edit"); ?>
                                </a>
                            <?php endif ?>
                        </div>
                    <?php endif ?>
                    <?php /*** END: add link "EDIT" ***/?>
                </div>
                <div class="hor-scroll">
                    <fieldset id="order_payment">
                        <?php echo $this->getPaymentHtml() ?>
                        <div><?php echo Mage::helper('sales')->__('Order was placed using %s', $order->getOrderCurrencyCode()) ?></div>
                    </fieldset>
                </div>
            </div>
        </div>
        <?php if (!$order->getIsVirtual()): ?>
            <div class="box-right">
                <!--Shipping Method-->
                <div class="entry-edit">
                    <div class="entry-edit-head">
                        <h4 class="icon-head head-shipping-method"><?php echo Mage::helper('sales')->__('Shipping &amp; Handling Information') ?></h4>
                        <?php /*** BEGIN: add link "EDIT" ***/?>
                        <?php $isAllow = Mage::getSingleton('admin/session')->isAllowed('iwd_ordermanager/order/actions/edit_shipping'); ?>
                        <?php if($isAllow): ?>
                            <div class="tools" style="float:right">
                                <?php if ($isAllowEdit): ?>
                                    <a id="order_shipping_edit_<?php echo $order->getEntityId(); ?>"
                                       class="order_shipping_edit" href="#"
                                       title="<?php echo Mage::helper('sales')->__('Edit shipping information'); ?>">
                                        <?php echo Mage::helper('sales')->__('Edit'); ?>
                                    </a>
                                <?php else: ?>
                                    <a href="#"
                                       onclick="alert('<?php echo $helper->__("Sorry, You can not update shipping information for order with this status. Check configuration by module IWD_OrderManager.") ?>'); return false;"
                                       title="<?php echo $helper->__("You can't edit shipping information!"); ?>">
                                        <?php echo Mage::helper('sales')->__("Edit"); ?>
                                    </a>
                                <?php endif ?>
                            </div>
                        <?php endif ?>
                        <?php /*** END: add link "EDIT" ***/?>
                    </div>
                    <div class="hor-scroll">
                        <fieldset id="order_shipping">
                            <?php if ($order->getTracksCollection()->count()) : ?>
                                <a
									href="#"
									id="linkId"
									onclick="popWin('<?= $this->helper('shipping')->getTrackingPopupUrlBySalesModel($order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')"
									<?php # 2024-01-29 Dmitrii Fediuk https://upwork.com/fl/mage2pro
									# "Port the `Mage_Adminhtml_Block_Sales_Order_View_Tab_Info`'s
									# `sales/order/view/tab/info.phtml` template 1.9.1.0 → 1.9.4.5 changes
									# to `iwd/ordermanager/order/view/tab/info.phtml`":
									# https://github.com/thehcginstitute-com/m1/issues/317 ?>
									title="<?= $this->quoteEscape($this->__('Track Order')) ?>"
								><?= $this->__('Track Order') ?></a>
                                <br/>
                            <?php endif ?>
                            <?php if ($order->getShippingDescription()): ?>
                                <strong><?php echo $this->escapeHtml($order->getShippingDescription()) ?></strong>

                                <?php if ($this->helper('tax')->displayShippingPriceIncludingTax()): ?>
                                    <?php $_excl = $this->displayShippingPriceInclTax($order); ?>
                                <?php else: ?>
                                    <?php $_excl = $this->displayPriceAttribute('shipping_amount', false, ' '); ?>
                                <?php endif ?>
                                <?php $_incl = $this->displayShippingPriceInclTax($order); ?>

                                <?php echo $_excl; ?>
                                <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                    (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                <?php endif ?>
                            <?php else: ?>
                                <?php echo $this->helper('sales')->__('No shipping information available'); ?>
                            <?php endif ?>
                        </fieldset>
                    </div>
                </div>
            </div>
        <?php endif ?>
        <div class="clear"></div>

        <?php echo $this->getGiftOptionsHtml() ?>
        <div class="clear"></div>
        <div class="entry-edit">
            <div class="entry-edit-head item-ordered">
                <h4 class="icon-head head-products"><?php echo Mage::helper('sales')->__('Items Ordered') ?></h4>

                <?php /*** BEGIN: add link "EDIT" ***/?>
                <?php $isAllow = Mage::getSingleton('admin/session')->isAllowed('iwd_ordermanager/order/actions/edit_order_items'); ?>
                <?php if ($isAllow) : ?>
                    <div class="tools">
                        <?php if ($isAllowEdit): ?>
                            <a href="#"id="ordered_items_edit" class="ordered_items_edit"
                               title="<?php echo $helper->__("Edit ordered items"); ?>">
                                <?php echo Mage::helper('sales')->__("Edit"); ?>
                            </a>
                        <?php else: ?>
                            <a href="#"
                               onclick="alert('<?php echo $helper->__("Sorry, You can not update ordered items for order with this status. Check configuration by module IWD_OrderManager.") ?>'); return false;"
                               title="<?php echo $helper->__("You can't edit ordered items!"); ?>">
                                <?php echo Mage::helper('sales')->__("Edit"); ?>
                            </a>
                        <?php endif ?>
                    </div>
                <?php endif ?>
                <?php /*** END: add link "EDIT" ***/?>
            </div>
        </div>
        <div id="ordered_items_box">
            <div id="ordered_items_table">
                <?php echo $this->getItemsHtml() ?>
            </div>
        </div>
        <div class="clear"></div>

        <!--Coupon Code & Custom Amount-->
        <?php echo $this->getChildHtml('coupon_code_custom_amount') ?>

        <div class="box-left">
            <div class="entry-edit comment-edit">
                <div class="entry-edit-head">
                    <h4><?php echo Mage::helper('sales')->__('Comments History') ?></h4>
                </div>
                <fieldset><?php echo $this->getChildHtml('order_history') ?></fieldset>
            </div>
        </div>
        <div class="box-right entry-edit">
            <div class="entry-edit-head"><h4><?php echo Mage::helper('sales')->__('Order Totals') ?></h4></div>
            <div class="order-totals"><?php echo $this->getChildHtml('order_totals') ?></div>
        </div>
        <div class="clear"></div>
    </div>

    <?php echo $this->getChildHtml('popup_window'); ?>
    <script type="text/javascript">
        //<![CDATA[
        /**
         * Retrieve gift options tooltip content
         */
        function getGiftOptionsTooltipContent(itemId) {
            var contentLines = [];
            var headerLine = null;
            var contentLine = null;

            $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
                if (element.down(0)) {
                    headerLine = element.down(0).innerHTML;
                    contentLine = element.down(0).next().innerHTML;
                    if (contentLine.length > 30) {
                        contentLine = contentLine.slice(0, 30) + '...';
                    }
                    contentLines.push(headerLine + ' ' + contentLine);
                }
            });
            return contentLines.join('<br/>');
        }
        giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
        //]]>
    </script>
