<?php
# 2024-09-21 Dmitrii Fediuk https://upwork.com/fl/mage2pro
use Mage_Page_Block_Template_Container as B; /** @var B $this */ $b = $this; /** @var B $b */
?>
<div class="page-sitemap">
	<div class="page-title"><h1><?= $b->getTitle() ?></h1></div>
	<div id="sitemap_top_links">
		<?= $b->getChildHtml('links') ?>
	</div>
	<?= df_cc_n(
		$b->getChildHtml('pager_top'), $b->getChildHtml('sitemap'), $b->getChildHtml('links'), $b->getChildHtml('pager_bottom')
	); ?>
</div>