<?php
# 2024-09-21 Dmitrii Fediuk https://upwork.com/fl/mage2pro
use Mage_Page_Block_Template_Container as B; /** @var B $this */ $b = $this; /** @var B $b */
?>
<div class="page-sitemap">
	<div class="page-title">
		<h1><?php echo $this->getTitle() ?></h1>
	</div>
	<div id="sitemap_top_links">
		<?php echo $this->getChildHtml('links') ?>
	</div>
	<?php echo $this->getChildHtml('pager_top') ?>
	<?php echo $this->getChildHtml('sitemap') ?>
	<?php echo $this->getChildHtml('links') ?>
	<?php echo $this->getChildHtml('pager_bottom') ?>
</div>
