<?php # 2024-02-06 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
/** @var Mage_Bundle_Block_Adminhtml_Sales_Order_View_Items_Renderer $this */
$imageHelper = Mage::helper('iwd_ordermanager/image');
$_item = $this->getItem();
$items = array_merge(array($_item), $_item->getChildrenItems());
$_count = count($items);
$_index = 0;
$_prevOptionId = '';
$_showlastRow = ($this->getOrderOptions() || $_item->getDescription() || $this->canDisplayGiftmessage());
$params = array();
foreach ($items as $_item): ?>
    <?php $this->setPriceDataObject($_item) ?>
    <?php $attributes = $this->getSelectionAttributes($_item) ?>
    <?php if ($_item->getParentItem()): ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <tr>
                <td>
                    <div class="option-label"><?php echo $attributes['option_label'] ?></div>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <?php if (Mage::helper('iwd_ordermanager')->isMultiInventoryEnable()): ?>
                    <td>&nbsp;</td>
                <?php endif; ?>
                <?php if(Mage::getConfig()->getModuleConfig('IWD_Downloadable')->is('active', 'true')): ?>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                <?php endif; ?>
                <td class="last">&nbsp;</td>
            </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr<?php echo (++$_index == $_count && !$_showlastRow) ? ' class="border"' : '' ?>>
        <?php if (!$_item->getParentItem()): ?>
            <td>
                <?php
                if (Mage::helper('iwd_ordermanager')->isShowItemImage()) {
                    try {
                        $image = (string)$imageHelper->init($_item->getProduct(), 'image')->resize(75);
                    } catch (Exception $e) {
                        $image = Mage::getDesign()->getSkinUrl($imageHelper->getPlaceholder(), array('_area' => 'frontend'));
                    }
                }
                ?>
                <img src="<?php echo $image ?>" class="order_item_image" />

                <h5 class="title">
                <span id="order_item_<?php echo $_item->getId() ?>_title">
                    <?php echo $this->htmlEscape($_item->getName()) ?>
                </span>
                </h5>

                <div>
                    <strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong>
                    <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->htmlEscape($_item->getSku()))); ?>
                </div>

                <i title="<?php echo $this->helper('sales')->__('Description'); ?>"><?php echo $this->htmlEscape($_item->getDescription()) ?></i>
            </td>
        <?php else: ?>
            <td>
                <?php
                if (Mage::helper('iwd_ordermanager')->isShowItemImage()) {
                    try {
                        $image = (string)$imageHelper->init($_item->getProduct(), 'image')->resize(75);
                    } catch (Exception $e) {
                        $image = Mage::getDesign()->getSkinUrl($imageHelper->getPlaceholder(), array('_area' => 'frontend'));
                    }
                }
                ?>
                <img src="<?php echo $image ?>" class="order_item_image" />
                <div class="option-value"><?php echo $this->getValueHtml($_item) ?></div>

                <i title="<?php echo $this->helper('sales')->__('Description'); ?>"><?php echo $this->htmlEscape($_item->getDescription()) ?></i>
            </td>
        <?php endif; ?>
        <?php if (Mage::helper('iwd_ordermanager')->isMultiInventoryEnable()): ?>
            <td class="a-left">
                <?php echo Mage::getBlockSingleton('iwd_multiinventory/adminhtml_order_render_inventory')->getStockMessageForOrderItem($_item); ?>
            </td>
        <?php endif; ?>
        <td class="a-center">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $_item->getStatus() ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="a-right">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayPriceAttribute('original_price') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="a-right">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
                    <span class="price-excl-tax">
                        <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                            <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                        <?php endif; ?>
						<?php echo $this->displayPrices($_item->getBasePrice(), $_item->getPrice()) ?>
                    </span>
                    <br/>
                <?php endif; ?>
                <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
                    <span class="price-incl-tax">
                        <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                            <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                        <?php endif; ?>
                        <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
                        <?php $_baseIncl = $this->helper('checkout')->getBasePriceInclTax($_item); ?>
						<?= $this->displayPrices($_baseIncl, $_incl) ?>
                    </span>
                <?php endif; ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td>
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <table cellspacing="0" class="qty-table">
                    <tr>
                        <td><?php echo Mage::helper('sales')->__('Ordered') ?></td>
                        <td><strong><?php echo $_item->getQtyOrdered() * 1 ?></strong></td>
                    </tr>
                    <?php if ((float)$_item->getQtyInvoiced()): ?>
                        <tr>
                            <td><?php echo Mage::helper('sales')->__('Invoiced') ?></td>
                            <td><strong><?php echo $_item->getQtyInvoiced() * 1 ?></strong></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ((float)$_item->getQtyShipped() && $this->isShipmentSeparately($_item)): ?>
                        <tr>
                            <td><?php echo Mage::helper('sales')->__('Shipped') ?></td>
                            <td><strong><?php echo $_item->getQtyShipped() * 1 ?></strong></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ((float)$_item->getQtyRefunded()): ?>
                        <tr>
                            <td><?php echo Mage::helper('sales')->__('Refunded') ?></td>
                            <td><strong><?php echo $_item->getQtyRefunded() * 1 ?></strong></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ((float)$_item->getQtyCanceled()): ?>
                        <tr>
                            <td><?php echo Mage::helper('sales')->__('Canceled') ?></td>
                            <td><strong><?php echo $_item->getQtyCanceled() * 1 ?></strong></td>
                        </tr>
                    <?php endif; ?>
                </table>
            <?php elseif ($this->isShipmentSeparately($_item)): ?>
                <table cellspacing="0" class="qty-table">
                    <tr>
                        <td><?php echo Mage::helper('sales')->__('Ordered') ?></td>
                        <td><strong><?php echo $_item->getQtyOrdered() * 1 ?></strong></td>
                    </tr>
                    <?php if ((float)$_item->getQtyShipped()): ?>
                        <tr>
                            <td><?php echo Mage::helper('sales')->__('Shipped') ?></td>
                            <td><strong><?php echo $_item->getQtyShipped() * 1 ?></strong></td>
                        </tr>
                    <?php endif; ?>
                </table>
                <?php
            else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="a-right">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
                    <span class="price-excl-tax">
                        <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                            <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                        <?php endif; ?>
						<?php echo $this->displayPrices($_item->getBaseRowTotal(), $_item->getRowTotal()) ?>
                    </span>
                    <br/>
                <?php endif; ?>
                <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
                    <span class="price-incl-tax">
                        <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                            <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                        <?php endif; ?>
                        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
                        <?php $_baseIncl = $this->helper('checkout')->getBaseSubtotalInclTax($_item); ?>
						<?php echo $this->displayPrices($_baseIncl, $_incl ) ?>
                    </span>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <td class="a-right">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayPriceAttribute('tax_amount') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>

        <td class="a-right">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayTaxPercent($_item) ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="a-right">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayPriceAttribute('discount_amount') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="a-right">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php
# 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
				echo $this->displayPrices(
                    $_item->getBaseRowTotal() - $_item->getBaseDiscountAmount() + $_item->getBaseTaxAmount(),
                    $_item->getRowTotal() - $_item->getDiscountAmount() + $_item->getTaxAmount()
                ); ?>
            <?php endif; ?>
        </td>
        <?php if(Mage::getConfig()->getModuleConfig('IWD_Downloadable')->is('active', 'true')): ?>
            <td class="a-right">&nbsp;</td>
            <td class="a-right last">&nbsp;</td>
        <?php endif; ?>
    </tr>

    <?php
    $product = $_item->getProduct();
    $productInfo = array(
        'Sku' => $product->getSku(),
        'Title' => $product->getName(),
        'Type' => $product->getTypeId(),
        'Price' => $_item->getOrder()->getStore()->formatPrice($product->getPrice()),
        'Qty' => (string)$product->getStockItem()->getQty() * 1,
        'Visible' => Mage_Catalog_Model_Product_Visibility::getOptionText($product->getVisibility()),
        'In Stock' => $product->getStockItem()->getIsInStock() ? 'Yes' : 'No'
    );

    if (!$_item->getParentItem()) {
        $params = $productInfo;
        $params['frontUrl'] = $product->isVisibleInSiteVisibility()
            ? sprintf('<a href="%s" target="_blank">%s</a>', $product->getProductUrl(), 'Go to product')
            : '';

        try {
            $params['productImage'] = (string)$imageHelper->init($_item->getProduct(), 'image')->resize(200);
        } catch (Exception $e) {
            $params['productImage'] = Mage::getDesign()->getSkinUrl($imageHelper->getPlaceholder(), array('_area' => 'frontend'));
        }

        $adminUrl = Mage::helper('adminhtml')->getUrl('*/catalog_product/edit', array('id' => $product->getId()));
        $params['adminUrl'] = sprintf('<a href="%s" target="_blank">%s</a>', $adminUrl, 'Edit product');
    } else {
        $adminUrl = Mage::helper('adminhtml')->getUrl('*/catalog_product/edit', array('id' => $product->getId()));
        $frontUrl = $product->isVisibleInSiteVisibility()
            ? sprintf('<a href="%s" target="_blank">%s</a>', $product->getProductUrl(), $productInfo['Title'])
            : $productInfo['Title'];

        $productInfo['Title'] = sprintf('%s (<a href="%s" target="_blank">%s</a>)', $frontUrl, $adminUrl, 'edit product');

        $attributes = $this->getSelectionAttributes($_item);
        $key = isset($attributes['option_label']) ? $attributes['option_label'] : $product->getName();
        $params['children'][$key] = $productInfo;
    }
    ?>
<?php endforeach; ?>
<?php if ($_showlastRow): ?>
    <tr<?php if (!$this->canDisplayGiftmessage()) echo ' class="border"' ?>>
        <td>
            <?php if ($this->getOrderOptions()): ?>
                <dl class="item-options">
                    <?php foreach ($this->getOrderOptions() as $option): ?>
                        <dt><?php echo $option['label'] ?>:</dt>
                        <dd>
                            <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                                <?php echo $option['value']; ?>
                            <?php else: ?>
                                <?php echo Mage::helper('core/string')->truncate($option['value'], 55, '', $_remainder); ?>
                                <?php if ($_remainder): ?>
                                    ... <span id="<?php echo $_id = 'id' . uniqid() ?>"><?php echo $_remainder ?></span>
                                    <script type="text/javascript">
                                        $('<?php echo $_id ?>').hide();
                                        $('<?php echo $_id ?>').up().observe('mouseover', function () {
                                            $('<?php echo $_id ?>').show();
                                        });
                                        $('<?php echo $_id ?>').up().observe('mouseout', function () {
                                            $('<?php echo $_id ?>').hide();
                                        });
                                    </script>
                                <?php endif; ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <?php if (Mage::helper('iwd_ordermanager')->isMultiInventoryEnable()): ?>
            <td>&nbsp;</td>
        <?php endif; ?>
        <?php if(Mage::getConfig()->getModuleConfig('IWD_Downloadable')->is('active', 'true')): ?>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
        <?php endif; ?>

        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>

<script type="text/javascript">
    IWD.OrderManager.OrderedItemProductInfo = IWD.OrderManager.OrderedItemProductInfo || {};
    IWD.OrderManager.OrderedItemProductInfo.addItem(
        'order_item_<?php echo $this->getItem()->getId() ?>_title',
        <?php echo json_encode($params); ?>
    );
</script>
