<?php # 2024-02-06 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
/** @var Mage_Adminhtml_Block_Sales_Order_View_Items_Renderer_Default $this */
 $item = $this->getItem();
 $this->setPriceDataObject($item); ?>
<tr <?php if (!$this->canDisplayGiftmessage()): ?> class="border"<?php endif; ?>>
    <td>
        <?php
            if (Mage::helper('iwd_ordermanager')->isShowItemImage()) {
                try {
                    $image = (string)Mage::helper('iwd_ordermanager/image')->init($item->getProduct(), 'image')->resize(75);
                } catch (Exception $e) {
                    $image = Mage::getDesign()->getSkinUrl(Mage::helper('iwd_ordermanager/image')->getPlaceholder(), array('_area' => 'frontend'));
                }
            }
        ?>
        <img src="<?php echo $image ?>" class="order_item_image" />

        <?php if ($this->canDisplayContainer()): ?>
            <div id="<?php echo $this->getHtmlId() ?>" class="item-container">
        <?php endif; ?>
            <div class="item-text">
                <?php echo $this->getColumnHtml($item, 'name') ?>
            </div>
        <?php if ($this->canDisplayContainer()): ?>
            </div>
        <?php endif ?>
    </td>
    <?php if (Mage::helper('iwd_ordermanager')->isMultiInventoryEnable()): ?>
        <td class="a-left">
            <?php echo Mage::getBlockSingleton('iwd_multiinventory/adminhtml_order_render_inventory')->getStockMessageForOrderItem($item); ?>
        </td>
    <?php endif; ?>
    <td class="a-center"><?php echo $item->getStatus() ?></td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('original_price') ?></td>
    <td class="a-right">
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
            <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                <?php endif; ?>
				<?php echo $this->displayPrices($item->getBasePrice(), $item->getPrice()) ?>
            </span>
            <br/>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                <?php endif; ?>
                <?php $_incl = $this->helper('checkout')->getPriceInclTax($item); ?>
                <?php $_baseIncl = $this->helper('checkout')->getBasePriceInclTax($item); ?>
				<?php echo $this->displayPrices($_baseIncl, $_incl) ?>
            </span>
        <?php endif; ?>

    </td>
    <td><?php echo $this->getColumnHtml($item, 'qty') ?></td>
    <td class="a-right">
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
            <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                <?php endif; ?>
				<?php echo $this->displayPrices($item->getBaseRowTotal(), $item->getRowTotal()) ?>
            </span>
            <br/>
        <?php endif; ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                <?php endif; ?>
                <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($item); ?>
                <?php $_baseIncl = $this->helper('checkout')->getBaseSubtotalInclTax($item); ?>
				<?php echo $this->displayPrices($_baseIncl , $_incl) ?>
            </span>
        <?php endif; ?>
    </td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('tax_amount') ?></td>
    <td class="a-right"><?php echo $this->displayTaxPercent($item) ?></td>
    <td class="a-right"><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
    <td class="a-right">
        <?php
			# 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
			# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
			echo $this->displayPrices(
            $item->getBaseRowTotal() + $item->getBaseTaxAmount() + $item->getBaseHiddenTaxAmount()
			- $item->getBaseDiscountAmount(),
            $item->getRowTotal() + $item->getTaxAmount() + $item->getHiddenTaxAmount() - $item->getDiscountAmount()
        ); ?>
    </td>

    <?php if(Mage::getConfig()->getModuleConfig('IWD_Downloadable')->is('active', 'true')): ?>
        <td class="a-right"> <?php echo Mage::helper("iwd_ordermanager/downloadable")->getSupportPeriod($item); ?> </td>
        <td class="a-right last"> <?php echo Mage::helper("iwd_ordermanager/downloadable")->getCountOfDownloads($item); ?> </td>
    <?php endif; ?>
</tr>