<?php # 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
/** @var Mage_Checkout_Block_Cart_Item_Renderer $this */
$_item = $this->getItem() ?>
<tr>
    <td><?php echo $this->getRenderedBlock()->getItemHtml($_item) ?></td>

    <!--- Excluding Tax -->
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
		<div class="cart-price">
			<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
        </div>
    </td>
    <?php endif ?>
    <!--- // Excluding Tax -->

    <!--- Including Tax -->
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
		<div class="cart-price">
			<?php echo $this->helper('checkout')->formatPrice($_incl) ?>
        </div>
    </td>
    <?php endif ?>
    <!--- // Including Tax -->

    <td class="a-center"><?php echo $_item->getQty()*1 ?></td>

    <!--- Excluding Tax Subtotal -->
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
        <div class="cart-price">
			<?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
        </div>
    </td>
    <?php endif ?>
    <!--- //Excluding Tax Subtotal -->

    <!--- Including Tax Subtotal -->
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
		<div class="cart-price">
			<?php echo $this->helper('checkout')->formatPrice($_incl) ?>
        </div>
    </td>
    <?php endif ?>
    <!--- //Including Tax Subtotal -->
</tr>
