<?php $helper = Mage::helper('richpanel_analytics'); ?>
<?php $request = Mage::app()->getRequest(); ?>
<?php $storeId = $helper->getStoreId($request); ?>
<?php $events = $this->getEvents(); ?>
<script type="text/javascript">
window.richpanel||(window.richpanel=[]),window.richpanel.queue=[],window.richpanel.methods=["track","debug","atr"],
window.richpanel.skelet=function(e){return function(){a=Array.prototype.slice.call(arguments);a.unshift(e);window.richpanel.queue.push(a)}};
for(var i=0;window.richpanel.methods.length>i;i++){var mthd=window.richpanel.methods[i];window.richpanel[mthd]=window.richpanel.skelet(mthd)}
window.richpanel.load=function(e){var t=document,n=t.getElementsByTagName("script")[0],r=t.createElement("script");
r.type="text/javascript";r.async=true;r.src="//<?php echo $helper->api_url ?>/j/"+e;n.parentNode.insertBefore(r,n)};
richpanel.load("<?php echo $helper->getApiToken($storeId); ?>");
<?php
# 2019-03-20 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# I have fixed the issues:
# 1) «Notice: Undefined index: userProperties»
# 2) «Notice: Undefined index: properties»
foreach ($events as $event) { ?>
    richpanel.track(
		"<?= $event['type']; ?>"
		,<?= json_encode(@$event['properties']); ?>
		,<?= json_encode(@$event['userProperties']); ?>
	);
<?php } ?>
</script>