<?php
# 2024-03-31 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Refactor the `IWD_OrderManager` module": https://github.com/thehcginstitute-com/m1/issues/533
use IWD_OrderManager_Block_Adminhtml_Sales_Order_Address_Text as B; /** @var B $this */
$a = function(string $k):string {return dfa($this->address(), $k, '');};
echo df_cc_br(
	df_cc_s($a('firstname'), $a('lastname'))
	,$a('company')
	,df_cc_br($a('street'))
	,$a('company')
	,df_region_name($this->address())
);
