<div class="page-title">
    <h1><?php echo Mage::helper('customer')->__('You are now logged out') ?></h1>
</div>
<p><?php echo Mage::helper('customer')->__($this->getCustomMessage(), $this->getDelayTime()) ?></p>
<script type="text/javascript">
    //<![CDATA[
    setTimeout(function(){ location.href = '<?php echo $this->getRedirectionUrl() ?>'}, <?php echo $this->getDelayTime(true); ?>);
    //]]>
</script>