<?php # 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
$parentItem = $this->getItem() ?>

<?php $items = $this->getChilds($parentItem) ?>
<?php $_order = $this->getItem()->getOrderItem()->getOrder() ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>

<?php $_prevOptionId = '' ?>

<?php foreach ($items as $_item): ?>

    <?php if ($this->getItemOptions() || $parentItem->getDescription() || $this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
        <?php $_showlastRow = true ?>
    <?php else: ?>
        <?php $_showlastRow = false ?>
    <?php endif; ?>

    <?php if ($_item->getOrderItem()->getParentItem()): ?>
        <?php $attributes = $this->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
            <tr>
                <td>
                    <div class="option-label"><?php echo $this->escapeHtml($attributes['option_label']); ?></div>
                </td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr<?php echo (++$_index == $_count && !$_showlastRow) ? ' class="border"' : '' ?>
        id="order-item-row-<?php echo $_item->getId() ?>">
    <?php if (!$_item->getOrderItem()->getParentItem()): ?>
        <td><h4 class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></h4>
        </td>
    <?php else: ?>
        <td>
            <div class="option-value"><?php echo $this->getValueHtml($_item) ?></div>
        </td>
    <?php endif; ?>
    <td><?php echo $this->escapeHtml($_item->getSku()) ?></td>
    <td class="a-right">
        <?php if ($this->canShowPriceInfo($_item)): ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
        <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                <?php endif; ?>
           		<span class="cart-price">
					<?php echo $this->getOrder()->formatPrice($this->getItem()->getPrice()) ?>
                </span>
            </span>
            <br/>
            <?php endif; ?>
            <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
            <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                <?php endif; ?>
                <?php $_incl = $this->helper('checkout')->getPriceInclTax($this->getItem()); ?>
				<span class="cart-price">
					<?php echo $this->getOrder()->formatPrice($_incl) ?>
                </span>
            </span>
                <?php endif; ?>
                <?php else: ?>
                    &nbsp;
                <?php
                endif;
                ?>
    </td>
    <td class="a-center">
        <?php if ($this->canShowPriceInfo($_item)): ?>
            <?php echo $_item->getQty() * 1 ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
    <td class="a-right">
        <?php if ($this->canShowPriceInfo($_item)): ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
        <span class="price-excl-tax">
                    <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                        <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                    <?php endif; ?>
					<span class="cart-price">
						<?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()) ?>
                    </span>
                </span>
                <br/>
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceInclTax()): ?>
            <span class="price-incl-tax">
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                    <?php endif; ?>

                <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($this->getItem()); ?>
					<span class="cart-price">
						<?php echo $this->getOrder()->formatPrice($_incl) ?>
					</span>
                </span>
                <?php else: ?>
                    &nbsp;
                <?php
                endif;
                ?>
                <?php else: ?>
                    &nbsp;
                <?php
                endif;
                ?>
    </td>
    <td class="a-right">
        <?php if ($this->canShowPriceInfo($_item)): ?>
            <?php echo $this->getOrder()->formatPrice(-$_item->getDiscountAmount()) ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
    <td class="last a-right">
        <?php if ($this->canShowPriceInfo($_item)): ?>
            <?php echo $this->getOrder()->formatPrice($_item->getRowTotal() - $_item->getDiscountAmount() + $_item->getTaxAmount()) ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
    </tr>
<?php endforeach; ?>

<?php if ($_showlastRow): ?>
    <tr class="border">
        <td>
            <?php if ($_options = $this->getItemOptions()): ?>
                <dl class="item-options">
                    <?php foreach ($_options as $_option) : ?>
                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                        <?php if (!$this->getPrintStatus()): ?>
                            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
                            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>>
                                <?php echo $_formatedOptionValue['value'] ?>
                                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                                    <div class="truncated_full_value">
                                        <dl class="item-options">
                                            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                                            <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                                        </dl>
                                    </div>
                                <?php endif; ?>
                            </dd>
                        <?php else: ?>
                            <dd><?php echo $this->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value'])) ?></dd>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php echo $this->escapeHtml($_item->getDescription()) ?>
            <?php if ($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
                <a href="#" id="order-item-gift-message-link-<?php echo $parentItem->getId() ?>"
                   class="gift-message-link"
                   onclick="return giftMessageToogle('<?php echo $parentItem->getId() ?>')"><?php echo Mage::helper('sales')->__('Gift Message') ?></a>
            <?php endif; ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
<?php endif; ?>
