<?php
/**
 * 2024-01-26
 * "The template `opcsignature/sales/order/view/info.phtml` of `IWD_OnepageCheckoutSignature_Block_Sales_Order_View_Info`
 * conflicts with the template `customfield/sales/order/view/info.phtml` of `Webkul_CustomField`,
 * the template `iwd/ordermanager/order/view/info.phtml` of `IWD_OrderManager`,
 * and the template `iwd/orderflags/order/view/info.phtml` of `IWD_OrderFlags`, because they are all override
 * the template `sales/order/view/info.phtml` of `Mage_Adminhtml_Block_Sales_Order_View_Info`":
 * @var Mage_Core_Block_Template $this
 * @var Mage_Adminhtml_Block_Sales_Order_View_Info $b
 */
$_order = $b->getOrder();
$customerid=$_order->getCustomerId();
$customer = Mage::getModel('customer/customer')->load($customerid);
$model = 'customer/attribute_collection';
$type='customer';
$collection = Mage::getResourceModel($model)
				->setEntityTypeFilter(Mage::getModel('eav/entity')->setType($type)->getTypeId())
				// ->addVisibleFilter()
				->addFilter('is_user_defined', 1)->setOrder('sort_order', 'ASC');
$collection->join(
				array('customfields' => "customfield/customfields"),
				'main_table.attribute_id=customfields.customer_attribute_id',
				array('status','is_in_saif','dependable_inputname','dependent_on')
			)->addFilter('status', 1)
			->addFilter('is_in_saif',1);
$store_id = Mage::app()->getStore()->getId();
if (count($collection)) {
	foreach ($collection as $attribute) {
		$attr = $attribute->toArray();
		$attr['is_required']=$attr['note'];
		if ($attr['is_required']) {
			$var_attrs[] = $attr['attribute_code'];
		}
		if($attr['dependable_inputname']!="" && $attr['frontend_input']=="select"){
			$attr['frontend_input']="dependable";
		}
		$store_labels = $attribute->getStoreLabels();
		$label = $store_labels[$store_id] ? $store_labels[$store_id] : $attr['frontend_label'];
		echo '<tr>';

		switch ($attr['frontend_input']) {
			case 'text':
				$vall="";
				?>
				<?php foreach ($customer as $val) {
					foreach ($val as $key=>$vl) {
						if ($attr['attribute_code']==$key) {
							$vall= $val[$key]; ?>
						<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
						<td class="value"><strong><?php echo $vall; ?></strong></td><?php

						}
					}
					break;
				}
				break;

			case 'radio':
				$valls="";
				?>
				<?php foreach ($customer as $val) {
					foreach ($val as $key=>$vl) {
						if ($attr['attribute_code']==$key) {
							$valls= $val[$key];
						}
					}
					break;
				} ?>

			<?php   foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
					?>
			<?php
			if ($instance['value']==$valls) {
				?>
				<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
				<td class="value"><strong><?php echo $instance['label']; ?></strong></td>
			<?php
			}
				}
				break;
			case 'select':
				$valls="";
				?>
				<?php foreach ($customer as $val) {
					foreach ($val as $key=>$vl) {
						if ($attr['attribute_code']==$key) {
							$valls= $val[$key];
						}
					}
					break;
				} ?>

			<?php   foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
					if ($instance['value']==$valls) {
						?>
					<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
					<td class="value"><strong><?php echo $instance['label']; ?></strong></td>

			<?php
					}
				}
				break;

			case 'multiselect':
				$vallm="";
				foreach ($customer as $val) {
					foreach ($val as $key=>$vl) {
						if ($attr['attribute_code']==$key) {
							$vallm= $val[$key];
						}
					}
					break;
				}
					if ($vallm) {
						$multi_values = explode(',', $vallm); ?>
					<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
						<td class="value"><strong>
						<?php   $multiselectval="";
								foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
									if (in_array($instance['value'],$multi_values)) {
										?>
									<?php $multiselectval.= $instance['label'].", "; ?>
							<?php
									}
								}
								$multiselectval=substr($multiselectval,0,strlen($multiselectval)-2);
								echo $multiselectval;
						?>
						</strong></td>
						<?php
					}
				break;

			case 'textarea':
				$valla="";
				foreach ($customer as $val) {
					foreach ($val as $key=>$vl) {
						if ($attr['attribute_code']==$key) {
							$valla= trim($val[$key]); ?>
							<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
							<td class="value"><strong><?php echo $valla; ?></strong></td>
						<?php
						}
					}
					break;
				}

				break;

			case 'date':
				$valld="";
				foreach ($customer as $val) {
					foreach ($val as $key=>$vl) {
						if ($attr['attribute_code']==$key) {
							$dformat=str_replace('yyyy', 'Y', strtolower(Mage::app()->getLocale()->getDateFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT)));
							$valld=new DateTime($val[$key]);
							echo $valld=$valld->format($dformat) ;
						}
					}
					break;
				}
					if ($valld) {
						?>
					<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
					<td class="value"><strong><?php echo $valld; ?></strong></td>
				<?php
					}
				break;

			case 'file':
				echo '
				<div class="input-box">';
				?>
				<?php
				$val_file= $customer[$attr['attribute_code']];
				$val_file_encode = Mage::helper('core')->urlEncode($val_file);

				$flag = 0;?>
				<?php
				if (file_exists(Mage::getBaseDir("media")."/customer".$val_file) && $val_file != "") {
					?>
				<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
					<td class="value"><strong>
					<a href="<?php echo $this->getUrl('customfield/index/viewfile', array('file'=>$val_file_encode)) ?>"><img alt="Download" title="Download" src="<?php echo $this->getSkinUrl('images/customfield/fam_bullet_disk.gif')?>" class="v-middle wk_download_link" style="float: left;width: 22px;"></a>
					<a href="<?php echo $this->getUrl('customfield/index/viewfile/', array('file'=>$val_file_encode))?>"><?php echo $this->__('Download') ?></a>

				<?php
				}
				echo '</strong></td>';
				break;

			case 'image':
				echo '
				<div class="input-box">';
				$val_file= $customer[$attr['attribute_code']];
				$val_file_encode = Mage::helper('core')->urlEncode($val_file);
				$flag = 0;
				if (file_exists(Mage::getBaseDir("media")."/customer".$val_file) && $val_file != "") {
					$path=Mage::getBaseDir("media")."/customer".$val_file;
					if (is_array(getimagesize($path))) {
						?>
					<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
					<td class="value"><strong>
						<a href="<?php echo $this->getUrl('customfield/index/viewfile', array('file'=>$val_file_encode)) ?>" style="display: inline-block;margin-bottom: 2px;text-decoration: none;vertical-align: middle;" target="_blank" >
							<img width="22" height="22" id="_accountimgs_image" class="small-image-preview v-middle" src="<?php echo Mage::getBaseUrl()?>customfield/index/viewfile/file/<?php echo $val_file_encode  ?>" title="View Full Size" alt="View Full Size">
						</a>
					<?php
					} else {
						?>
					<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
					<td class="value"><strong>
						<a href="<?php echo $this->getUrl('customfield/index/viewfile', array('file'=>$val_file_encode)) ?>" target="_blank"><img alt="Download" title="Download" src="<?php echo $this->getSkinUrl('images/customfield/fam_bullet_disk.gif')?>" class="v-middle wk_download_link" style="float: left;width: 22px;"></a>
						<a href="<?php echo $this->getUrl('customfield/index/viewfile/', array('file'=>$val_file_encode))?>" target="_blank"><?php echo $this->__('Download') ?></a>
					<?php
					}
				} ?>
				<?php
				echo '</strong></td>';
				break;
			case 'dependable':
				$valls="";
				?>
				<?php foreach ($customer as $val) {
					foreach ($val as $key=>$vl) {
						if ($attr['attribute_code']==$key) {
							$valls= $val[$key];
						}
					}
					break;
				} ?>

			<?php   foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
					if ($instance['value']==$valls) {
						?>
					<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
					<td class="value"><strong><?php echo $instance['label']; ?></strong></td>

			<?php
					}
				}
				echo'</tr>';
				//dependable next
				$model = 'customer/attribute_collection';
				$dependentCollection = Mage::getResourceModel($model)
							->setEntityTypeFilter(Mage::getModel('eav/entity')->setType($type)->getTypeId())
							->addFilter('is_user_defined', 1)->setOrder('sort_order', 'ASC');
				$dependentCollection->join(
								array('customfields' => "customfield/customfields"),
								'main_table.attribute_id=customfields.customer_attribute_id',
								array('status','dependable_inputname','dependent_on')
							)->addFieldToFilter('dependent_on',array("notnull" => true));
				$dependentCollection->addFieldToFilter('attribute_code', $attr['dependable_inputname']);

				$attribute=$dependentCollection->getFirstItem();
				$attr = $attribute->toArray();

				$store_labels = $attribute->getStoreLabels();
				$label = $store_labels[$store_id] ? $store_labels[$store_id] : $attr['frontend_label'];
				echo '<tr>';

				switch ($attr['frontend_input']) {
					case 'text':
						$vall="";
						?>
						<?php foreach ($customer as $val) {
							foreach ($val as $key=>$vl) {
								if ($attr['attribute_code']==$key) {
									$vall= $val[$key]; ?>
								<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
								<td class="value"><strong><?php echo $vall; ?></strong></td><?php

								}
							}
							break;
						}
						break;

					case 'radio':
						$valls="";
						?>
						<?php foreach ($customer as $val) {
							foreach ($val as $key=>$vl) {
								if ($attr['attribute_code']==$key) {
									$valls= $val[$key];
								}
							}
							break;
						} ?>

					<?php   foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
							?>
					<?php
					if ($instance['value']==$valls) {
						?>
						<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
						<td class="value"><strong><?php echo $instance['label']; ?></strong></td>
					<?php
					}
						}
						break;
					case 'select':
						$valls="";
						?>
						<?php foreach ($customer as $val) {
							foreach ($val as $key=>$vl) {
								if ($attr['attribute_code']==$key) {
									$valls= $val[$key];
								}
							}
							break;
						} ?>

					<?php   foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
							if ($instance['value']==$valls) {
								?>
							<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
							<td class="value"><strong><?php echo $instance['label']; ?></strong></td>

					<?php
							}
						}
						break;

					case 'multiselect':
						$vallm="";
						foreach ($customer as $val) {
							foreach ($val as $key=>$vl) {
								if ($attr['attribute_code']==$key) {
									$vallm= $val[$key];
								}
							}
							break;
						}
							if ($vallm) {
								$multi_values = explode(',', $vallm); ?>
							<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
								<td class="value"><strong>
								<?php   $multiselectval="";
								foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
									if (in_array($instance['value'], $multi_values)) {
										?>
											<?php $multiselectval.= $instance['label'].", "; ?>
									<?php
									}
								}
								$multiselectval=substr($multiselectval, 0, strlen($multiselectval)-2);
								echo $multiselectval; ?>
								</strong></td>
								<?php

							}
						break;

					case 'textarea':
						$valla="";
						foreach ($customer as $val) {
							foreach ($val as $key=>$vl) {
								if ($attr['attribute_code']==$key) {
									$valla= trim($val[$key]); ?>
									<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
									<td class="value"><strong><?php echo $valla; ?></strong></td>
								<?php
								}
							}
							break;
						}

						break;

					case 'date':
						$valld="";
						foreach ($customer as $val) {
							foreach ($val as $key=>$vl) {
								if ($attr['attribute_code']==$key) {
									$dformat=str_replace('yyyy', 'Y', strtolower(Mage::app()->getLocale()->getDateFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT)));
									$valld=new DateTime($val[$key]);
									echo $valld=$valld->format($dformat) ;
								}
							}
							break;
						}
							if ($valld) {
								?>
							<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
							<td class="value"><strong><?php echo $valld; ?></strong></td>
						<?php
							}
						break;

					case 'file':
						echo '
						<div class="input-box">';
						?>
						<?php
						$val_file= $customer[$attr['attribute_code']];
						$val_file_encode = Mage::helper('core')->urlEncode($val_file);

						$flag = 0;?>
						<?php
						if (file_exists(Mage::getBaseDir("media")."/customer".$val_file) && $val_file != "") {
							?>
						<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
							<td class="value"><strong>
							<a href="<?php echo $this->getUrl('customfield/index/viewfile', array('file'=>$val_file_encode)) ?>"><img alt="Download" title="Download" src="<?php echo $this->getSkinUrl('images/customfield/fam_bullet_disk.gif')?>" class="v-middle wk_download_link" style="float: left;width: 22px;"></a>
							<a href="<?php echo $this->getUrl('customfield/index/viewfile/', array('file'=>$val_file_encode))?>"><?php echo $this->__('Download') ?></a>

						<?php
						}
						echo '</strong></td>';
						break;

					case 'image':
						echo '
						<div class="input-box">';
						$val_file= $customer[$attr['attribute_code']];
						$val_file_encode = Mage::helper('core')->urlEncode($val_file);
						$flag = 0;
						if (file_exists(Mage::getBaseDir("media")."/customer".$val_file) && $val_file != "") {
							$path=Mage::getBaseDir("media")."/customer".$val_file;
							if (is_array(getimagesize($path))) {
								?>
							<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
							<td class="value"><strong>
								<a href="<?php echo $this->getUrl('customfield/index/viewfile', array('file'=>$val_file_encode)) ?>" style="display: inline-block;margin-bottom: 2px;text-decoration: none;vertical-align: middle;" target="_blank" >
									<img width="22" height="22" id="_accountimgs_image" class="small-image-preview v-middle" src="<?php echo Mage::getBaseUrl()?>customfield/index/viewfile/file/<?php echo $val_file_encode  ?>" title="View Full Size" alt="View Full Size">
								</a>
							<?php
							} else {
								?>
							<td class="label"><label><?php echo $attr['frontend_label']; ?></label></td>
							<td class="value"><strong>
								<a href="<?php echo $this->getUrl('customfield/index/viewfile', array('file'=>$val_file_encode)) ?>" target="_blank"><img alt="Download" title="Download" src="<?php echo $this->getSkinUrl('images/customfield/fam_bullet_disk.gif')?>" class="v-middle wk_download_link" style="float: left;width: 22px;"></a>
								<a href="<?php echo $this->getUrl('customfield/index/viewfile/', array('file'=>$val_file_encode))?>" target="_blank"><?php echo $this->__('Download') ?></a>
							<?php
							}
						} ?>
						<?php
						echo '</strong></td>';
						break;
					}
				break;
			}
	}
	echo'</tr>';
}
