<?php /** @var Mage_Checkout_Block_Cart_Crosssell $this */
if($this->getItemCount()):
# 2024-01-20 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `app/design/frontend/base/default/template/checkout/cart/crosssell.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/213
# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/checkout/cart/crosssell.phtml#L35
$_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()]));
?>
<div class="crosssell">
    <h2><?php echo $this->__('Based on your selection, you may be interested in the following items:') ?></h2>
    <ul id="crosssell-products-list">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item">
            <a
				class="product-image"
				href="<?php echo $_item->getProductUrl() ?>"
				title="<?php echo $this->escapeHtml($_item->getName()) ?>"
			><img
				alt="<?php echo $this->escapeHtml($_item->getName()) ?>"
<?php # 2024-01-20 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# https://github.com/thehcginstitute-com/m1/blob/2024-01-15-2/app/design/frontend/default/mobileshoppe/template/checkout/cart/crosssell.phtml#L40 ?>
				height="120" width="120"
				src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(120); ?>"
			/></a>
            <div class="product-details">
                <h3 class="product-name"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></h3>
                <?php echo $this->getPriceHtml($_item, true) ?>
				<button
					class="button btn-cart"
<?php # 2024-01-20 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `app/design/frontend/base/default/template/checkout/cart/crosssell.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/213
# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/checkout/cart/crosssell.phtml#L48-L51
# ?>
					onclick="customFormSubmit(
						'<?= $this->getAddToCartUrlCustom($_item, [], false) ?>'
						,'<?= $_params ?>'
						,'post')"
<?php # 2024-01-20 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `app/design/frontend/base/default/template/checkout/cart/crosssell.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/213
# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/checkout/cart/crosssell.phtml#L46 ?>
					title="<?= Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>"
					type="button"
				><span><span><?= $this->__('Add to Cart') ?></span></span></button>
                <ul class="add-to-links">
                    <?php if ($this->helper('wishlist')->isAllow()) { ?>
						<li>
<!-- 2024-01-21 Dmitrii Fediuk https://upwork.com/fl/mage2pro
1) "Port the `app/design/frontend/base/default/template/checkout/cart/crosssell.phtml` 1.9.1.0 → 1.9.4.5 changes
to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/213
2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/checkout/cart/crosssell.phtml#L57-L64
-->
							<a
								class="link-wishlist"
								href="#"
								onclick="customFormSubmit(
									'<?= $this->getAddToWishlistUrlCustom($_item, false) ?>'
									,'<?= $_params ?>'
									,'post'
								)"
							><?= $this->__('Add to Wishlist') ?></a>
						</li>
                    <?php
					}
					# 2024-01-20 Dmitrii Fediuk https://upwork.com/fl/mage2pro
					# 1) "Port the `app/design/frontend/base/default/template/checkout/cart/crosssell.phtml`
					# 1.9.1.0 → 1.9.4.5 changes to the `mobileshoppe` design theme":
					# https://github.com/thehcginstitute-com/m1/issues/213
					# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/checkout/cart/crosssell.phtml#L67-L79
					if ($_compareUrl = $this->getAddToCompareUrlCustom($_item, false)) { ?>
						<li>
							<span class="separator">|</span>
							<a
								class="link-compare"
								href="#"
								onclick="customFormSubmit(
									'<?= $_compareUrl ?>'
									,'<?= $_params ?>'
									,'post'
								)"
							><?= $this->__('Add to Compare') ?></a>
						</li>
                    <?php } ?>
                </ul>
            </div>
        </li>
    <?php endforeach ?>
    </ul>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
</div>
<?php endif ?>
