<?php # 2024-02-06 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
/** @var Mage_Bundle_Block_Adminhtml_Sales_Order_Items_Renderer $this */
$_item = $this->getItem();
$items = $this->getChilds($_item);
$_count = count ($items);
$_index = 0;
$_prevOptionId = '';
if($this->getOrderOptions() || $_item->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php foreach ($items as $_item): ?>
    <?php $this->setPriceDataObject($_item) ?>
    <?php if ($_item->getOrderItem()->getParentItem()): ?>
        <?php $attributes = $this->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
        <tr>
            <td><div class="option-label"><?php echo $this->escapeHtml($attributes['option_label']); ?></div></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="last">&nbsp;</td>
        </tr>
        <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr<?php echo (++$_index==$_count && !$_showlastRow)?' class="border"':'' ?>>
        <?php if (!$_item->getOrderItem()->getParentItem()): ?>
        <td><h5 class="title"><?php echo $this->escapeHtml($_item->getName()) ?></h5>
            <div>
                <strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong>
                <?php echo implode('<br />', Mage::helper('catalog')->splitSku($this->escapeHtml($_item->getSku()))); ?>
            </div>
        <?php else: ?>
        <td><div class="option-value"><?php echo $this->getValueHtml($_item)?></div></td>
        <?php endif; ?>
        <td class="a-right">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
                    <span class="price-excl-tax">
                        <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                            <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                        <?php endif; ?>
<!-- 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377 -->
						<?php echo $this->displayPrices($_item->getBasePrice(), $_item->getPrice()) ?>
<!-- 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377 -->
                    </span>
                    <br />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
                    <span class="price-incl-tax">
                        <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                            <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                        <?php endif; ?>
                        <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
                        <?php $_baseIncl = $this->helper('checkout')->getBasePriceInclTax($_item); ?>
<!-- 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377 -->
						<?php echo $this->displayPrices($_baseIncl, $_incl) ?>
<!-- 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377 -->
                    </span>
                <?php endif; ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="a-center">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $_item->getQty()*1 ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="a-right">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
                    <span class="price-excl-tax">
                        <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                            <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                        <?php endif; ?>
<!-- 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377 -->
						<?php echo $this->displayPrices($_item->getBaseRowTotal(), $_item->getRowTotal()) ?>
<!-- 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377 -->
                    </span>
                    <br />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceInclTax()): ?>
                    <span class="price-incl-tax">
                        <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                            <span class="label"><?php echo $this->__('Incl. Tax'); ?>:</span>
                        <?php endif; ?>
                        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
                        <?php $_baseIncl = $this->helper('checkout')->getBaseSubtotalInclTax($_item); ?>
<!-- 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377 -->
						<?php echo $this->displayPrices($_baseIncl, $_incl) ?>
                    </span>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <td class="a-right">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayPriceAttribute('tax_amount') ?>
            <?php else: ?>
                &nbsp;
                        <?php endif; ?>
        </td>
        <td class="a-right">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayPriceAttribute('discount_amount') ?>
            <?php else: ?>
                &nbsp;
                        <?php endif; ?>
        </td>
        <td class="a-right last">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php
# 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
				echo $this->displayPrices(
                    $_item->getBaseRowTotal() + $_item->getBaseTaxAmount() - $_item->getBaseDiscountAmount() + $_item->getBaseHiddenTaxAmount(),
                    $_item->getRowTotal() + $_item->getTaxAmount() - $_item->getDiscountAmount() + $_item->getHiddenTaxAmount()
                ) ?>
             <?php else: ?>
                 &nbsp;
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if($_showlastRow): ?>
    <tr class="border">
        <td>
            <?php if ($this->getOrderOptions()): ?>
                <dl class="item-options">
                <?php foreach ($this->getOrderOptions() as $option): ?>
                    <dt><?php echo $this->escapeHtml($option['label']) ?></dt>
                    <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                        <?php echo $option['value'];?>
                    <?php else: ?>
                        <?php echo Mage::helper('core/string')->truncate($option['value'], 55, '', $_remainder);?>
                        <?php if ($_remainder):?>
                            ... <span id="<?php echo $_id = 'id' . uniqid()?>"><?php echo $_remainder ?></span>
                            <script type="text/javascript">
                            $('<?php echo $_id ?>').hide();
                            $('<?php echo $_id ?>').up().observe('mouseover', function(){$('<?php echo $_id ?>').show();});
                            $('<?php echo $_id ?>').up().observe('mouseout',  function(){$('<?php echo $_id ?>').hide();});
                            </script>
                        <?php endif;?>
                    <?php endif;?>
                    </dd>
                <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php echo $this->escapeHtml($this->getItem()->getDescription()) ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>
