<?php
$item = $this->getItem(); /* @var Mage_Wishlist_Model_Item $item */
$product = $item->getProduct();
?>
<!-- 2024-01-22 Dmitrii Fediuk https://upwork.com/fl/mage2pro
1) "Port the `app/design/frontend/base/default/template/wishlist/item/column/info.phtml` 1.9.1.0 → 1.9.4.5 changes
to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/235
2) https://github.com/thehcginstitute-com/m1/blob/2024-01-15-2/app/design/frontend/default/mobileshoppe/template/wishlist/item/column/info.phtml#L31 -->
<div class="productdetailscell">
	<h3 class="product-name"><a href="<?php echo $this->getProductUrl($item) ?>" title="<?php echo $this->escapeHtml($product->getName()) ?>"><?php echo $this->escapeHtml($product->getName()) ?></a></h3>
	<div class="description std"><div class="inner"><?php echo $this->escapeHtml($this->stripTags($product->getShortDescription()));?></div></div>
	<textarea name="description[<?php echo $item->getWishlistItemId() ?>]" rows="3" cols="5" onfocus="focusComment(this)" onblur="focusComment(this)" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Comment')) ?>"><?php echo ($this->escapeHtml($item->getDescription() ? $item->getDescription() : $this->helper('wishlist')->defaultCommentString())) ?></textarea>
	<?php if($this->getSortedChildren()): ?>
		<div class="item-manage">
		<?php foreach($this->getSortedChildren() as $childName):?>
			<?php echo $this->getChildHtml($childName, false);?>
		<?php endforeach ?>
		</div>
	<?php endif ?>
<!-- 2024-01-22 Dmitrii Fediuk https://upwork.com/fl/mage2pro
1) "Port the `app/design/frontend/base/default/template/wishlist/item/column/info.phtml` 1.9.1.0 → 1.9.4.5 changes
to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/235
2) https://github.com/thehcginstitute-com/m1/blob/2024-01-15-2/app/design/frontend/default/mobileshoppe/template/wishlist/item/column/info.phtml#L42 -->
</div>
