<!-- 2024-01-22 Dmitrii Fediuk https://upwork.com/fl/mage2pro
1) "Port the `app/design/frontend/base/default/template/wishlist/item/column/remove.phtml` 1.9.1.0 → 1.9.4.5 changes
to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/236
2) https://github.com/thehcginstitute-com/m1/blob/2024-01-15-2/app/design/frontend/default/mobileshoppe/template/wishlist/item/column/remove.phtml#L28 -->
<p class="deletecell">
	<a href="#"
	   class="btn-remove btn-remove2"
	   title="<?php echo Mage::helper('core')->quoteEscape($this->__('Remove Item')) ?>"
	   onclick="if (confirmRemoveWishlistItem()) {
					customFormSubmit(
						'<?php echo $this->getItemRemoveUrlCustom($this->getItem(), false) ?>',
						'<?php echo $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()])) ?>',
						'post'
					)
				}">
		<?php echo $this->__('Remove item') ?>
	</a>
<!-- 2024-01-22 Dmitrii Fediuk https://upwork.com/fl/mage2pro
1) "Port the `app/design/frontend/base/default/template/wishlist/item/column/remove.phtml` 1.9.1.0 → 1.9.4.5 changes
to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/236
2) https://github.com/thehcginstitute-com/m1/blob/2024-01-15-2/app/design/frontend/default/mobileshoppe/template/wishlist/item/column/remove.phtml#L31 -->
</p>