<?php
 /**
 * @category   Webkul
 * @package    Webkul_CustomField
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */
$customerid = $this->getRequest()->getParam("id");
$collection = Mage::getModel("customfield/customfielddata")->getCollection()->addFieldToFilter("customer_id", $customerid);
if (count($collection)) {
    $customfields = array();
    foreach ($collection as $coll) {
        array_push($customfields, array($coll->getFieldId()));
    }
}        ?>

<div id="customer_info_tabs_customfield_content">
	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__("Custom Registration Fields Information") ?></h4>
		</div>
		<div id="_accountbase_fieldset" class="fieldset">
			<div class="hor-scroll">
				<table class="form-list" cellspacing="0">
					<tbody>

	<?php 
        $customerid=$this->getRequest()->getParam("id");
        $customer = Mage::getModel('customer/customer')->load($customerid);
            $collection = $this->getCollection();
            $store_id = Mage::app()->getStore()->getId();
            if (count($collection)) {
                foreach ($collection as $attribute) {
                    $attr = $attribute->toArray();
                    $attr['is_required']=$attr['note'];
                    if ($attr['is_required']) {
                        $var_attrs[] = $attr['attribute_code'];
                    }

                    $store_labels = $attribute->getStoreLabels();
                    $label = $store_labels[$store_id] ? $store_labels[$store_id] : $attr['frontend_label'];
                    echo '<tr>';

                    switch ($attr['frontend_input']) {
                        case 'text':
                            $vall="";
                            ?>
                            <?php foreach ($customer as $val) {
                                foreach ($val as $key=>$vl) {
                                    if ($attr['attribute_code']==$key) {
                                        $vall= $val[$key]; ?>                          
                                    <td class="label"><label for="<?php echo $attr['frontend_label']; ?>"><?php echo $attr['frontend_label'];
                                        if ($attr['is_required']) {
                                            ?><span class="required">*</span><?php 
                                        } ?></label></td>
                                    <td class="value"><div class="input-box">
                                        <input type="text" name="<?php echo $attr['attribute_code']; ?>" id="<?php echo $attr['attribute_code']; ?>" value="<?php echo $vall ?>" <?php if ($attr['is_required']) {
                                            ?> class="required-entry input-text <?php echo $attr['frontend_class']; ?>" <?php 
                                        } else {
                                            ?> class="input-text <?php echo $attr['frontend_class']; ?>"  <?php 
                                        } ?>/>
                                    </div></td>
                                    <?php

                                    }
                                }
                                break;
                            }
                            break;

                        case 'radio':
                            $valls="";
                            ?>
                            <?php foreach ($customer as $val) {
                                foreach ($val as $key=>$vl) {
                                    if ($attr['attribute_code']==$key) {
                                        $valls= $val[$key];
                                    }
                                }
                                break;
                            } ?>                            
                            <td class="label"><label for="<?php echo $attr['frontend_label'];?>"><?php echo $attr['frontend_label']; if ($attr['is_required']) {
                                ?><span class="required">*</span><?php 
                            }?></label></td>
                        <?php   foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                ?>

                            <td class="value"><div class="input-box">
                                 <input type="radio" name="<?php echo $attr['attribute_code']; ?>" class="<?php if ($attr['is_required']) {
                                    echo 'required-entry ';
                                } ?> "  id="<?php echo $attr['attribute_code']; ?>"  value="<?php echo $instance['value']; ?>"  <?php if ($instance['value']==$valls) {
                                    echo 'selected';
                                } ?> > <?php echo $instance['label']; ?></input>
                            </div></td>                           
                        <?php 
                            }
                            break;
                        case 'select':
                            $valls="";
                            ?>
                            <?php foreach ($customer as $val) {
                                foreach ($val as $key=>$vl) {
                                    if ($attr['attribute_code']==$key) {
                                        $valls= $val[$key];
                                    }
                                }
                                break;
                            } ?>                                                        
                                <td class="label"><label for="<?php echo $attr['frontend_label'];?>"><?php echo $attr['frontend_label']; if ($attr['is_required']) {
                                ?><span class="required">*</span><?php 
                            }?></label></td>
                                <td class="value">
                                    <div class="input-box">
                                    <select name="<?php echo $attr['attribute_code']; ?>" id="<?php echo $attr['attribute_code'];?>" class="<?php if ($attr['is_required']) {
                                echo 'required-entry ';
                            } ?>" >
                        <?php   foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                ?>

                                 <option value="<?php echo $instance['value']; ?>"  <?php if ($instance['value']==$valls) {
                                    echo 'selected';
                                } ?> > <?php echo $instance['label']; ?></option>
                        <?php 
                            }?>
                                    </select>
                                </div>
                            </td>
                        <?php 
                            break;
                            
                        case 'multiselect':
                            $vallm="";
                            foreach ($customer as $val) {
                                foreach ($val as $key=>$vl) {
                                    if ($attr['attribute_code']==$key) {
                                        $vallm= $val[$key];
                                    }
                                }
                                break;
                            }
                                $multi_values = explode(',', $vallm);?>
                             <td class="label"><label for="<?php echo $attr['frontend_label'];?>"><?php echo $attr['frontend_label']; if ($attr['is_required']) {
                                    ?><span class="required">*</span><?php 
                                }?></label></td>
                                <td class="value">
                                    <div class="input-box">
                                    <select name="<?php echo $attr['attribute_code']; ?>" id="<?php echo $attr['attribute_code'];?>" class="<?php if ($attr['is_required']) {
                                    echo 'required-entry ';
                                } ?>" >
                                    <?php
                                           foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                               echo '<option value="'.$instance['value'].'" '.  (in_array($instance['value'], $multi_values) ? 'selected' : '') .'>' . $instance['label'] . '</option>';
                                           }?>
                                            </select>
                                        </div>
                                    </td>
                                <?php

                            break;

                        case 'textarea':
                          $valla="";
                          foreach ($customer as $val) {
                              foreach ($val as $key=>$vl) {
                                  if ($attr['attribute_code']==$key) {
                                      $valla= trim($val[$key]); ?>
                                       
                                    <?php 
                                  }
                              }
                              break;
                          }?>
                            <td class="label"><label for="<?php echo $attr['frontend_label'];?>"><?php echo $attr['frontend_label']; if ($attr['is_required']) {
                              ?><span class="required">*</span><?php 
                          }?></label></td>
                                    <td class="value">
                                    <div class="input-box">
                                        <textarea  name="<?php echo $attr['attribute_code']; ?>" id="<?php echo $attr['attribute_code']; ?>" <?php if ($attr['is_required']) {
                              ?> class="required-entry <?php echo $attr['frontend_class'];
                              if ($attr['default_value']==1) {
                                  echo 'niceedits';
                              } ?>" <?php 
                          } else {
                              ?> class= "<?php if ($attr['default_value']==1) {
                                  echo 'niceedits';
                              } else {
                                  echo 'noedit';
                              } ?>" <?php 
                          }?> ><?php echo $valla ; ?></textarea>
                                    </div></td> 
                                <?php

                            break;
                            
                        case 'date':
                            $valld="";
                            foreach ($customer as $val) {
                                foreach ($val as $key=>$vl) {
                                    if ($attr['attribute_code']==$key) {
                                        $dformat=str_replace('yyyy', 'Y', strtolower(Mage::app()->getLocale()->getDateFormat(Mage_Core_Model_Locale::FORMAT_TYPE_SHORT)));
                                        $valld=new DateTime($val[$key]);
                                        echo $valld=$valld->format($dformat) ;
                                    }
                                }
                                break;
                            }
                            ?> <td class="label"><label for="<?php echo $attr['frontend_label'];?>"><?php echo $attr['frontend_label']; if ($attr['is_required']) {
                                ?><span class="required">*</span><?php 
                            }?></label></td>  
                                <td class="value">
                                    <div class="input-box">
                                        <input type="text" name="<?php echo $attr['attribute_code'] ?>" id="<?php echo $attr['attribute_code'] ?>" value="<?php echo $valld; ?>" <?php if ($attr['is_required']) {
                                ?> class="required-entry input-text <?php echo $attr['attribute_code'] ?>" <?php 
                            } else {
                                ?> class="input-text <?php echo $attr['attribute_code'] ?>"  <?php 
                            }?>   style="width:110px !important;" />
                                        <img style="cursor: pointer;display: inline;" title="<?php echo $this->__('Select Date'); ?>" id="<?php echo  $attr['attribute_code'].'_trig' ?>" <?php if ($attr['is_required']) {
                                ?> class="required-entry v-middle" <?php 
                            } else {
                                ?> class="v-middle"  <?php 
                            }?> alt="" src="<?php echo str_replace("base", "default", $this->getSkinUrl('images/grid-cal.gif', array('_area'=>'adminhtml'))); ?>" >
                                    </div><?php
                                    echo '<script type="text/javascript">
                                    Calendar.setup({
                                        inputField : "'.$attr['attribute_code'].'",
                                        ifFormat : "'.Varien_Date::convertZendToStrFtime(Mage::app()->getLocale()->getDateFormatWithLongYear(), true, false).'", 
                                        button : "'.$attr['attribute_code'].'_trig",
                                        showsTime: false,
                                        align : "Bl",
                                        singleClick : true
                                    });
                                </script>';?>
                                </td>   
                            <?php 

                            break;

                        case 'file':
                            ?>
                            <td class="label"><label for="<?php echo $attr['frontend_label'];?>"><?php echo $attr['frontend_label']; if ($attr['is_required']) {
                                ?><span class="required">*</span><?php 
                            }?></label></td> 
                            <td class="value">
                                    <div class="input-box">
                            <?php 
                            $val_file= $customer[$attr['attribute_code']];
                            $val_file_encode = Mage::helper('core')->urlEncode($val_file);
                            
                            $flag = 0;?>
                            <?php
                            if (file_exists(Mage::getBaseDir("media")."/customer".$val_file) && $val_file != "") {
                                ?>

                            
                                <a href="<?php echo $this->getUrl('customfield/index/viewfile', array('file'=>$val_file_encode)) ?>"><img alt="Download" title="Download" src="<?php echo $this->getSkinUrl('images/customfield/fam_bullet_disk.gif')?>" class="v-middle wk_download_link" style="float: left;width: 22px;"></a>
                                <a href="<?php echo $this->getUrl('customfield/index/viewfile/', array('file'=>$val_file_encode))?>"><?php echo $this->__('Download') ?></a> 

                            <?php $flag = 1;
                            } ?>
                                <div>
                                    <input type="file" name='<?php echo $attr['attribute_code']; ?>' id='<?php echo $attr['attribute_code']; ?>' <?php if ($attr['is_required']) {
                                ?> class="wk_filevalidate <?php if (!$flag) {
                                    echo 'required-entry';
                                } ?> input-text" <?php 
                            } else {
                                ?> class="wk_filevalidate input-text"  <?php 
                            }?>/>
                                    </div>
                            
                             <span class="wk_cf_hints">(<?php echo $this->__('Allowed Extensions are zip,pdf'); ?>)</span>
                            <?php
                            echo '</div></td>';
                            break;
                            
                        case 'image':
                        ?>
                            <td class="label"><label for="<?php echo $attr['frontend_label'];?>"><?php echo $attr['frontend_label']; if ($attr['is_required']) {
                            ?><span class="required">*</span><?php 
                        }?></label></td> 
                            <td class="value">
                                    <div class="input-box">
                        <?php
                            $val_file= $customer[$attr['attribute_code']];
                            $val_file_encode = Mage::helper('core')->urlEncode($val_file);
                            $flag = 0;
                            if (file_exists(Mage::getBaseDir("media")."/customer".$val_file) && $val_file != "") {
                                $path=Mage::getBaseDir("media")."/customer".$val_file;
                                if (is_array(getimagesize($path))) {
                                    ?>                                
                                    <a href="<?php echo $this->getUrl('customfield/index/viewfile', array('file'=>$val_file_encode)) ?>" style="display: inline-block;margin-bottom: 2px;text-decoration: none;vertical-align: middle;" target="_blank" >
                                        <img width="22" height="22" id="_accountimgs_image" class="small-image-preview v-middle" src="<?php echo Mage::getBaseUrl()?>customfield/index/viewfile/file/<?php echo $val_file_encode  ?>" title="View Full Size" alt="View Full Size">
                                    </a>
                                <?php 
                                } else {
                                    ?>                                
                                    <a href="<?php echo $this->getUrl('customfield/index/viewfile', array('file'=>$val_file_encode)) ?>" target="_blank"><img alt="Download" title="Download" src="<?php echo $this->getSkinUrl('images/customfield/fam_bullet_disk.gif')?>" class="v-middle wk_download_link" style="float: left;width: 22px;"></a>
                                    <a href="<?php echo $this->getUrl('customfield/index/viewfile/', array('file'=>$val_file_encode))?>" target="_blank"><?php echo $this->__('Download') ?></a>
                                <?php 
                                } ?>
                                <?php if (!$attr['is_required']) {
                                    ?>
                             <span style="color:red;margin-left:5px" title="<?php echo $this->__('For remove saved file.') ?>" ><input style="vertical-align: sub;" type="checkbox" name="remove[<?php echo $attr['attribute_code'] ?>]" value="1" /><?php echo $this->__('Remove') ?></span>

                                <?php 
                                }
                                $flag = 1;
                            } ?>
                            <div>
                                <input type="file" name='<?php echo $attr['attribute_code']; ?>' id='<?php echo $attr['attribute_code']; ?>' <?php if ($attr['is_required']) {
                                ?> class="wk_imagevalidate <?php if (!$flag) {
                                    echo 'required-entry';
                                } ?> input-text" <?php 
                            } else {
                                ?> class="wk_imagevalidate input-text"  <?php 
                            }?> value="<?php echo $val_file ?>"/>
                            <div>
                                <span class="wk_cf_hints">(<?php echo $this->__('Allowed Extensions are png,jpg,jpeg'); ?>)</span>
                            <?php 
                            echo '</strong></div></td>';
                            break;
                        }
                }
                echo'</tr>';
            }
?>

					</tbody>
					<tbody class="tr_store"></tbody>
				</table>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	if (typeof jQuery == "undefined") {
	document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
	}
</script>
<script src="http://js.nicedit.com/nicEdit-latest.js" type="text/javascript"></script>
<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>
<script type="text/javascript">

	var $wk_jq = jQuery.noConflict();
   
              
	(function($wk_jq){
		/**
		*this function triggers the change event when document get ready.
		**/
		$wk_jq(function(){
			first_value = $wk_jq("#data_store_wise").find("option").eq(1).val();
			$wk_jq("#data_store_wise").val(first_value).trigger("change");
		});
	})(jQuery);

	/**
	*This calls the getstoreoption in controller and retrieve data according to store selection
	**/
	$wk_jq(".selectstore").change(function(){
		storeid = $wk_jq(this).val();
		customerid = $wk_jq(this).attr("data-id");
		$wk_jq.ajax({
			url: "<?php echo $this->getUrl('adminhtml/customfield_customfield/getstoreoption'); ?>",
			type:"GET",
			DataType:"text",
			data:{"storeid":storeid,"customerid":customerid},
			success: function(msg){
				$wk_jq(".tr_store").html(msg);
				$wk_jq("#customer_info_tabs_tabid_content").find(".select").trigger("change");
				validaterequired();
			}
		});
	});
	/**
	*This function add or remove validation class in fields
	**/
	$wk_jq("body").on('change','.custom_file',function(){
		console.log($wk_jq(this));
        this_this = $wk_jq(this);
        this_this.removeClass("validation-failed");
        this_this.nextAll(".validation-advice").remove();
        if(this_this.val() != ""){
            ext_arr = this_this.attr("data-allowed").split(",");
            if(ext_arr.indexOf(this_this.val().split("\\").pop().split(".").pop()) < 0){
                this_this.addClass("validation-failed");
                this_this.after("<div class='validation-advice'>Should have these extensions "+this_this.attr("data-allowed")+"</div>");
                this_this.val("");
                this_this.next('.validation-advice').fadeOut(2000);
                haserror = true;
            }
        }
    });
    /**
    *This function removed : required entry class : from dependent field and adds the : tmpreq class
    *clstmp calss is added to check required-entry class in dependant fields.
    */
    function validaterequired(){
    if($wk_jq('.valverify').val()==0) {
    	if ($wk_jq('.valverify').parents(".dependant").next(".dependant").find('.clstmp').hasClass("required-entry")) 
    		$wk_jq('.valverify').parents(".dependant").next(".dependant").find('.clstmp').removeClass("required-entry").addClass("tmpreq");
    	
			$wk_jq('.valverify').parents(".dependant").next(".dependant").hide();
		}
    }
    /**
	*This function is used to hide and show the dependent fields and along with 
	* add the required-entry class in dependent
	* field if it has : tmpreq class : added in : validaterequired function.
	*/
	function open_dependant(this_this){
		if($wk_jq(this_this).val() == 1)
		{
			if($wk_jq(this_this).hasClass('clstmp1'))
				$wk_jq(this_this).parents(".dependant").next(".dependant").find('.clstmp').addClass("required-entry");

			$wk_jq(this_this).parents(".dependant").next(".dependant").show();	

			if($wk_jq('.valverify').parents(".dependant").next(".dependant").find('.clstmp').hasClass("tmpreq"))
    		$wk_jq(this_this).parents(".dependant").next(".dependant").find('.clstmp').removeClass("tmpreq").addClass("required-entry");	
		}
		else
		{	
			if($wk_jq(this_this).parents(".dependant").next(".dependant").find('.clstmp').hasClass("required-entry"))
				{
					$wk_jq(this_this).addClass('clstmp1');
					$wk_jq(this_this).parents(".dependant").next(".dependant").find('.clstmp').removeClass('required-entry');
				}
			$wk_jq(this_this).parents(".dependant").next(".dependant").hide();
		}
	}
</script>

