<?php /** @var Mage_Catalog_Block_Product_View $this */
# 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
$_product = $this->getProduct();
if ($this->getParent()->getPriceType() != Mage_Bundle_Model_Product_Price::PRICE_TYPE_FIXED) {
    $_tierPrices = $this->getTierPrices($_product, $this->getParent());
}
$_finalPriceInclTax = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice(), true);
$_catalogHelper = Mage::helper('catalog'); /** @var $_catalogHelper Mage_Catalog_Helper_Data */
if (isset($_tierPrices) && count($_tierPrices) > 0) {
	?><ul class="<?= (
		$this->getInGrouped() ? 'tier-prices-grouped product-pricing-grouped' : 'tier-prices product-pricing'
	) ?>"><?php
	if ($this->getInGrouped()) {
		$_tierPrices = $this->getTierPrices($_product);
	}
}
foreach ($_tierPrices as $_index => $_price) {
	?><li class="tier-price tier-<?= $_index; ?>"><?php
		if ($_catalogHelper->canApplyMsrp($_product)) {
			if ($this->getInGrouped()) {
				echo $this->__('Buy %1$s for', $_price['price_qty']) ?>:<?php
			}
			else {
				echo $this->__('Buy %1$s', $_price['price_qty']);
			}
		}
		elseif ($this->helper('tax')->displayBothPrices()) {
			echo $this->__(
				'Buy %1$s for %2$s (%3$s incl. tax) each'
				, $_price['price_qty']
				, $_price['formated_price']
				, $_price['formated_price_incl_tax']
			);
		}
		elseif ($this->helper('tax')->displayPriceIncludingTax()) {
			echo $this->__('Buy %1$s for %2$s each', $_price['price_qty'], $_price['formated_price_incl_tax']);
		}
		else {
			echo $this->__('Buy %1$s for %2$s each', $_price['price_qty'], $_price['formated_price']);
		}
		if (!$this->getInGrouped()) { ?>
            <?php if(($_product->getPrice() == $_product->getFinalPrice() && $_product->getPrice() > $_price['price'])
            || ($_product->getPrice() != $_product->getFinalPrice() &&  $_product->getFinalPrice() > $_price['price'])) { ?>
                <?= $this->__('and') ?>&nbsp;<strong class="benefit"><?= $this->__('save')?>&nbsp;<span class="percent tier-fixed"><?= $_price['savePercent']?></span>%
            <?php } ?></strong>
        <?php } ?>

        <?php if ($_catalogHelper->isShowPriceOnGesture($_product)) {?>
            <?php $popupId = 'msrp-popup-' . $_product->getId() . $this->helper('core')->getRandomString(20); ?>
            <a href="#" id="<?=($popupId);?>"><?= $this->__('Click for price'); ?></a>
            <script type="text/javascript">
            <?php
                $addToCartUrl = $this->getProduct()->isSalable()
                    ? $this->getAddToCartUrlCustom($_product, array('qty' => $_price['price_qty']), false)
                    : '';
            ?>
            <?php if (!$this->getInGrouped()) { ?>
                var newLink = {
                    url: "<?= $addToCartUrl; ?>",
                    qty: "<?= $_price['price_qty']?>"
                }
            <?php } else { ?>
                var newLink = {
                    url: "<?= $addToCartUrl; ?>",
                    notUseForm: true
                }
            <?php } ?>
                Catalog.Map.addHelpLink(
                    $('<?= $popupId ?>'),
                    "<?= $_product->getName() ?>",
                    <?= json_encode($_price['real_price_html']) ?>,
                    "<?= $this->helper('core')->currency($_product->getMsrp(),true,false) ?>",
                    newLink
                );
            </script>
        <?php } else { ?>
            <span class="msrp-price-hide-message">
                <?= $_catalogHelper->getMsrpPriceMessage($_product) ?>
            </span>
        <?php } ?>


        </li>

    <?php } ?>
    </ul>
<?php }?>
