<?php # 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377 ?>
<?php $_product = $this->getProduct() ?>
<?php $_finalPrice = $_product->getFinalPrice() ?>
<?php $_finalPriceInclTax = $_product->getFinalPrice() ?>
<?php
$isMAPTypeOnGesture = Mage::helper('catalog')->isShowPriceOnGesture($_product);
$canApplyMAP  = Mage::helper('catalog')->canApplyMsrp($_product);
?>
<?php if ($_product->getCanShowPrice() !== false):?>
<div class="price-box">
    <p class="price-as-configured">
        <span class="price-label"><?php echo $this->helper('bundle')->__('Price as configured') ?>:</span>
        <?php if (!$this->getWithoutPrice()): ?>
        <span<?php if (!$isMAPTypeOnGesture && $canApplyMAP): ?> style="display:none"<?php endif ?> class="full-product-price">
        <?php if ($this->helper('tax')->displayBothPrices()): ?>
        <span class="price-tax">
            <span class="price-excluding-tax">
                <span class="label"><?php echo Mage::helper('tax')->__('Excl. Tax:') ?></span>
                <span class="price" id="price-excluding-tax-<?php echo $_product->getId() ?><?php echo $this->getIdSuffix() ?>">
                <?php if (!$canApplyMAP): ?>
                    <?php echo Mage::helper('core')->currency($_finalPrice,true,false) ?>
                <?php endif ?>
                </span>
            </span>
            <span class="price-including-tax">
                <span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax:') ?></span>
                <span class="price" id="price-including-tax-<?php echo $_product->getId() ?><?php echo $this->getIdSuffix() ?>">
                <?php if (!$canApplyMAP): ?>
                    <?php echo Mage::helper('core')->currency($_finalPriceInclTax,true,false) ?>
                <?php endif ?>
                </span>
            </span>
        </span>
        <?php else: ?>
        <span class="price" id="product-price-<?php echo $_product->getId() ?><?php echo $this->getIdSuffix() ?>">
            <?php if (!$canApplyMAP): ?>
                <?php echo Mage::helper('core')->currency($_finalPrice,true,false) ?>
            <?php endif ?>
        </span>
    <?php endif ?>
    </span>
    <?php endif ?>
    </p>
</div>
<?php endif ?>
<?php if($_product->isSaleable()): ?>
<script type="text/javascript">
document.observe("dom:loaded", function() {
    bundle.reloadPrice();
});
</script>
<?php endif ?>
