<?php /** @var Mage_Core_Block_Template $this */
# 2024-01-21 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# The file is identical to https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/default/iphone/template/persistent/remember_me_tooltip.phtml
?>
<div id="remember-me-popup" class="remember-me-popup" style="display:none;">
    <div class="remember-me-popup-body">
        <p>Checking &quot;Remember Me&quot; will let you access your shopping cart on this computer when you are logged out</p>
        <a href="#" class="remember-me-popup-close button" title="<?php echo $this->quoteEscape($this->__('Close')) ?>"><?php echo $this->__('Close') ?></a>
    </div>
</div>
<script type="text/javascript">
//<![CDATA[
    function toggleRememberMepopup(e){
        if($('remember-me-popup')){
            $('remember-me-popup').setStyle({'top' : e.pointerY() + 'px'}).toggle();
        }
        Event.stop(event);
    }

    document.observe("dom:loaded", function() {
        new Insertion.Bottom($$('body')[0], $('remember-me-popup'));

        $$('.remember-me-popup-close').each(function(element){
            Event.observe(element, 'click', toggleRememberMepopup);
        })
        $$('#remember-me-box a').each(function(element) {
            Event.observe(element, 'click', toggleRememberMepopup);
        });
    });
//]]>
</script>