<?php
use Ebizmarts_MailChimp_Helper_Data as H;
/**
 * 2024-04-14
 * @used-by hcg_mc_cfg_scope()
 * @used-by Ebizmarts_MailChimp_Block_Adminhtml_Customer_Edit_Tab_Mailchimp::makeHelper()
 * @used-by Ebizmarts_MailChimp_Block_Adminhtml_Mailchimpstores_Edit_Form::makeHelper()
 * @used-by Ebizmarts_MailChimp_Block_Adminhtml_Mailchimpstores_Edit::makeHelper()
 * @used-by Ebizmarts_MailChimp_Block_Adminhtml_Sales_Order_Grid_Renderer_MailchimpOrder::makeHelper()
 * @used-by Ebizmarts_MailChimp_Block_Adminhtml_Sales_Order_View_Info_Monkey::getMailChimpHelper()
 * @used-by Ebizmarts_MailChimp_Block_Adminhtml_System_Config_Fieldset_Mailchimp_Hint::makeHelper()
 * @used-by Ebizmarts_MailChimp_Block_Adminhtml_System_Config_Form_Field_Mapfields::makeHelper()
 * @used-by Ebizmarts_MailChimp_Block_Adminhtml_System_Config_Account::makeHelper()
 * @used-by Ebizmarts_MailChimp_Block_Adminhtml_System_Config_CreateMergeFields::makeHelper()
 * @used-by Ebizmarts_MailChimp_Block_Adminhtml_Notifications::makeHelper()
 * @used-by Ebizmarts_MailChimp_Block_Checkout_Success_Groups::__construct()
 * @used-by Ebizmarts_MailChimp_Block_Checkout_Subscribe::__construct()
 * @used-by Ebizmarts_MailChimp_Block_Customer_Newsletter_Index::__construct()
 * @used-by Ebizmarts_MailChimp_Block_Group_Type::__construct()
 * @used-by Ebizmarts_MailChimp_Adminhtml_EcommerceController::makeHelper()
 * @used-by Ebizmarts_MailChimp_Adminhtml_MailchimpController::preDispatch()
 * @used-by Ebizmarts_MailChimp_Adminhtml_MailchimperrorsController::makeHelper()
 * @used-by Ebizmarts_MailChimp_Adminhtml_MailchimpstoresController::getMailchimpHelper()
 * @used-by Ebizmarts_MailChimp_Adminhtml_MergevarsController::makeHelper()
 * @used-by Ebizmarts_MailChimp_CartController::loadcouponAction::loadquoteAction()
 * @used-by Ebizmarts_MailChimp_Helper_Mandrill::isMandrillLogEnabled()
 * @used-by Ebizmarts_MailChimp_Helper_Mandrill::isMandrillEnabled()
 * @used-by Ebizmarts_MailChimp_Helper_Mandrill::getMandrillApiKey()
 * @used-by Ebizmarts_MailChimp_Helper_Migration::__construct()
 * @used-by Ebizmarts_MailChimp_Helper_Webhook::__construct()
 * @used-by Ebizmarts_MailChimp_Model_Adminhtml_Includetaxes_Comment::getCommentText()
 * @used-by Ebizmarts_MailChimp_Model_Adminhtml_Resendecommercedata_Comment::setMcHelper()
 * @used-by Ebizmarts_MailChimp_Model_Adminhtml_Resendsubscribers_Comment::setMcHelper()
 * @used-by Ebizmarts_MailChimp_Model_Adminhtml_Reseterrors_Comment::setMcHelper()
 * @used-by Ebizmarts_MailChimp_Model_Adminhtml_Storeid_Comment::getCommentText()
 * @used-by Ebizmarts_MailChimp_Model_Api_Subscribers_InterestGroupHandle::__construct()
 * @used-by Ebizmarts_MailChimp_Model_Api_Subscribers_MailchimpTags::setMailChimpHelper()
 * @used-by Ebizmarts_MailChimp_Model_Api_Batches::__construct()
 * @used-by Ebizmarts_MailChimp_Model_Api_ItemSynchronizer::__construct()
 * @used-by Ebizmarts_MailChimp_Model_Api_Stores::makeHelper()
 * @used-by Ebizmarts_MailChimp_Model_Api_Subscribers::__construct()
 * @used-by Ebizmarts_MailChimp_Model_System_Config_Backend_Active::makeHelper()
 * @used-by Ebizmarts_MailChimp_Model_System_Config_Backend_Apikey::makeHelper()
 * @used-by Ebizmarts_MailChimp_Model_System_Config_Backend_Ecommerce::makeHelper()
 * @used-by Ebizmarts_MailChimp_Model_System_Config_Backend_List::getMailchimpHelper()
 * @used-by Ebizmarts_MailChimp_Model_System_Config_Backend_Mapfield::_afterLoad()
 * @used-by Ebizmarts_MailChimp_Model_System_Config_Backend_Store::makeHelper()
 * @used-by STUB()
 * @used-by STUB()
 * @used-by STUB()
 * @used-by STUB()
 * @used-by STUB()
 * @used-by STUB()
 * @used-by STUB()
 * @used-by STUB()
 * @used-by STUB()
 * @used-by STUB()
 * @used-by STUB()
 * @used-by STUB()
 * @used-by STUB()
 */
function hcg_mc_h():H {return Mage::helper('mailchimp');}