<?php
# 2024-09-16 Dmitrii Fediuk https://upwork.com/fl/mage2pro
use Mage_Adminhtml_Block_Sales_Order_Totals as B;
/** @var B $this */ $b = $this; /** @var B $b */
?>
<table cellspacing="0" width="100%">
	<col />
	<col width="1" />
	<?php $_totals = $b->getTotals('footer')?>
	<?php if ($_totals):?>
	<tfoot>
	<?php foreach ($b->getTotals('footer') as $_code => $_total): ?>
		<?php if ($_total->getBlockName()): ?>
			<?= $b->getChildHtml($_total->getBlockName(), false); ?>
		<?php else: ?>
		<tr class="<?= $_code?>">
			<td <?= $b->getLabelProperties()?> class="label">
				<strong><?= $b->escapeHtml($_total->getLabel()); ?></strong>
			</td>
			<td <?= $b->getValueProperties()?> class="emph">
				<strong><?= $b->formatValue($_total) ?></strong>
			</td>
		</tr>
		<?php endif ?>
	<?php endforeach ?>
	</tfoot>
	<?php endif ?>
	<?php $_totals = $b->getTotals('')?>
	<?php if ($_totals):?>
	<tbody>
	<?php foreach ($_totals as $_code => $_total): ?>
		<?php if ($_total->getBlockName()): ?>
			<?= $b->getChildHtml($_total->getBlockName(), false); ?>
		<?php else: ?>
		<tr class="<?= $_code?>">
			<td <?= $b->getLabelProperties()?> class="label">
				<?php if ($_total->getStrong()):?>
				<strong><?= $b->escapeHtml($_total->getLabel()); ?></strong>
				<?php else: ?>
				<?= $b->escapeHtml($_total->getLabel()); ?>
				<?php endif ?>
			</td>
			<?php if ($_total->getStrong()):?>
			<td <?= $b->getValueProperties()?> class="emph">
				<strong><?= $b->formatValue($_total) ?></strong>
			<?php else: ?>
			<td <?= $b->getValueProperties()?>>
				<?= $b->formatValue($_total) ?>
			<?php endif ?>
			</td>
		</tr>
		<?php endif ?>
	<?php endforeach ?>
	</tbody>
	<?php endif ?>
</table>