<table cellspacing="0" width="100%">
	<col />
	<col width="1" />
	<?php $_totals = $this->getTotals('footer')?>
	<?php if ($_totals):?>
	<tfoot>
	<?php foreach ($this->getTotals('footer') as $_code => $_total): ?>
		<?php if ($_total->getBlockName()): ?>
			<?= $this->getChildHtml($_total->getBlockName(), false); ?>
		<?php else: ?>
		<tr class="<?= $_code?>">
			<td <?= $this->getLabelProperties()?> class="label">
				<strong><?= $this->escapeHtml($_total->getLabel()); ?></strong>
			</td>
			<td <?= $this->getValueProperties()?> class="emph">
				<strong><?= $this->formatValue($_total) ?></strong>
			</td>
		</tr>
		<?php endif ?>
	<?php endforeach ?>
	</tfoot>
	<?php endif ?>
	<?php $_totals = $this->getTotals('')?>
	<?php if ($_totals):?>
	<tbody>
	<?php foreach ($_totals as $_code => $_total): ?>
		<?php if ($_total->getBlockName()): ?>
			<?= $this->getChildHtml($_total->getBlockName(), false); ?>
		<?php else: ?>
		<tr class="<?= $_code?>">
			<td <?= $this->getLabelProperties()?> class="label">
				<?php if ($_total->getStrong()):?>
				<strong><?= $this->escapeHtml($_total->getLabel()); ?></strong>
				<?php else: ?>
				<?= $this->escapeHtml($_total->getLabel()); ?>
				<?php endif ?>
			</td>
			<?php if ($_total->getStrong()):?>
			<td <?= $this->getValueProperties()?> class="emph">
				<strong><?= $this->formatValue($_total) ?></strong>
			<?php else: ?>
			<td <?= $this->getValueProperties()?>>
				<?= $this->formatValue($_total) ?>
			<?php endif ?>
			</td>
		</tr>
		<?php endif ?>
	<?php endforeach ?>
	</tbody>
	<?php endif ?>
</table>