<?php
$helper               = Mage::helper('magepsycho_storerestrictionpro');
$hideAddToCartText    = $helper->cfgH()->getAccessibleHideAddToCartText();
$hideAddToCartLink    = $helper->cfgH()->getAccessibleHideAddToCartLink();
$onclickAction        = '';
if (!empty($hideAddToCartLink)) {
    $hideAddToCartLink       = $this->getUrl(trim($hideAddToCartLink, '/'));
    $onclickAction           = sprintf('onclick="setLocation(\'%s\')"', $hideAddToCartLink);
}
?>
<?php if (!empty($hideAddToCartText)): ?>
<div class="add-to-cart">
    <button type="button" title="<?php echo $hideAddToCartText ?>" class="button btn-cart-restriction" <?php echo $onclickAction ?>><span><span><?php echo $hideAddToCartText ?></span></span></button>
</div>
<?php endif; ?>