<?php 
 /**
 * @category   Webkul
 * @package    Webkul_CustomField
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */ ?>
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('js').'calendar/calendar-win2k-1.css'; ?>" />
<script src="<?php echo Mage::getBaseUrl('js').'calendar/calendar.js'; ?>" type="text/javascript"></script>
<script src="<?php echo Mage::getBaseUrl('js').'calendar/calendar-setup.js'; ?>" type="text/javascript"></script>
<?php	
    if (!Mage::getSingleton('customer/session')->isLoggedIn()) {
        $collection = Mage::getModel("customfield/customfields")->getCollection();
        $DOB = array();
        $allAttrIds=array();
        foreach ($collection as $value) {
            $allAttrIds[]=$value->getCustomerAttributeId();
        }
        if ($collection->getSize()) {
            ?>
			<div class="fieldset" id="wkadditionalinfo">
				<h2 class="legend"><?php echo $this->__("Additional Information") ?></h2>
				<ul class="form-list">
<?php 
                    $var_attrs = array(); // will be used in JS
                    $model = 'customer/attribute_collection';
            $type='customer';
            $collection = Mage::getResourceModel($model)
                        ->setEntityTypeFilter(Mage::getModel('eav/entity')->setType($type)->getTypeId())
                        ->addVisibleFilter()
                        ->addFilter('is_user_defined', 1)->setOrder('sort_order', 'ASC');
                    
            $store_id = Mage::app()->getStore()->getId();
                
            foreach ($collection as $attribute) {
                $attr = $attribute->toArray();
                $customCollection=Mage::getModel('customfield/customfields')->getCollection()->addFieldToFilter('customer_attribute_id', $attr['attribute_id']);
                    
                $visibleInFormCheck=0;
                foreach ($customCollection as  $value) {
                    $d=$value->getData();
                    if ($d['viewinforms']) {
                        $forms=explode(',', $d['viewinforms']);
                        foreach ($forms as $key => $val) {
                            if ($val=='checkout_register') {
                                $visibleInFormCheck=1;
                            }
                        }
                    }
                }
                if ($visibleInFormCheck) {
                    if (in_array($attr['attribute_id'], $allAttrIds)) {
                        $attr['is_required']=$attr['note'];
                        if ($attr['is_required']) {
                            $var_attrs[] = $attr['attribute_code'];
                        }
                    

                        $store_labels = $attribute->getStoreLabels();
                        $label = $store_labels[$store_id] ? $store_labels[$store_id] : $attr['frontend_label'];
                    
                        echo '<li>';
                        $func = 'get'.  str_replace(' ', '', ucwords(str_replace('_', ' ', $attr['attribute_code'])));

                        echo '<label for="'. $attr['attribute_code'] .'" '. ($attr['is_required']?'class="required"><em>*</em>':'>') . $this->__($label) . '</label>';
                        
                        switch ($attr['frontend_input']) {
                        case 'text':
                        ?>
						<div class="input-box">
							<input type="text" name="<?php echo "billing[".$attr['attribute_code']."] "; ?>" id="<?php echo $attr['attribute_code']; ?>" value="" class="input-text <?php if ($attr['is_required']) {
                            echo 'required-entry ';
                        } echo $attr['frontend_class']; ?>" />
						</div>
                        <?php
                            break;
                    
                        case 'radio':
                            echo '
							<div class="input-box">';
                            foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                echo '<input type="radio"  name="'. "billing[".$attr['attribute_code']."] " .'" value="'.$instance['value'].'" '.  ($this->htmlEscape($this->getFormData()->$func()) == $instance['value'] ? 'selected' : '') .'>' . $instance['label'] . '</input>';
                            }

                            echo '
							</div>';
                            break;
                        
                        case 'select':
                            echo '
							<div class="input-box">';
                            echo '<select name="'. "billing[".$attr['attribute_code']."] " .'" id="'. $attr['attribute_code'] .'" >';
                            foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                echo '<option value="'.$instance['value'].'" '.  ($this->htmlEscape($this->getFormData()->$func()) == $instance['value'] ? 'selected' : '') .'>' . $instance['label'] . '</option>';
                            }
                            echo '</select>';

                            echo '
							</div>';
                            break;

                        case 'textarea':
                            if ($attr['default_value']==1) {
                                $niced = 'niceedits';
                            }
                            ?>
							<div class="input-box">
								<textarea name="<?php echo "billing[".$attr['attribute_code']."] "; ?>" id="<?php echo $attr['attribute_code']; ?>" class="<?php if ($attr['is_required']) {
                                echo 'required-entry ';
                            } echo $attr['frontend_class']; ?>" ><?php echo $this->htmlEscape($this->getFormData()->$func()); ?></textarea>
							</div>
                            <?php
                                break;

                        case 'multiselect':
                            echo '
							<div class="input-box">';
                            echo '<select name="'. "billing[".$attr['attribute_code']."] ".'[]" id="'. $attr['attribute_code'] .'" multiple="multiple"  >';
                            
                            $multi_values = explode(',', $this->htmlEscape($this->getFormData()->$func()));

                            foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                echo '<option value="'.$instance['value'].'" '.  (in_array($instance['value'], $multi_values) ? 'selected' : '') .'>' . $instance['label'] . '</option>';
                            }
                            echo '</select>';
                            break;
                            
                        case 'date':
                            echo '
							<div class="input-box">
								<input type="text" name="'."billing[".$attr['attribute_code']."] " .'" id="'. $attr['attribute_code'] .'" value="'. $this->htmlEscape($this->getFormData()->$func()) .'" class="input-text" style="width:110px !important;" />
								<img style="cursor: pointer;" title="'. $this->__('Select Date') .'" id="'.$attr['attribute_code'].'_trig" class="v-middle" alt="" src="'. str_replace("base", "default", $this->getSkinUrl('images/grid-cal.gif', array('_area'=>'adminhtml'))) .'">
							</div>';
                            echo '<script type="text/javascript">
									Calendar.setup({
										inputField : "'.$attr['attribute_code'].'",
										ifFormat : "'. Varien_Date::convertZendToStrFtime(Mage::app()->getLocale()->getDateFormatWithLongYear(), true, false) .'", 
										button : "'.$attr['attribute_code'].'_trig",
										showsTime: false,
										align : "Bl",
										singleClick : true
									});
								</script>';
                            break;

                        case 'file':
                            echo '
                            <div class="input-box">';
                            ?>
                            <input type="file" name='<?php echo "billing[".$attr['attribute_code']."]"; ?>' id='<?php echo $attr['attribute_code']; ?>' <?php if ($attr['is_required']) {
                                ?> class="wk_filevalidate required-entry input-text" <?php 
                            } else {
                                ?> class="wk_filevalidate input-text"  <?php 
                            }?>/>
                            <input type="hidden" value="" id="_accountfiles_value" name="account[files][value]">
                            <span class="wk_cf_hints">(<?php echo $this->__('Allowed Extensions are '). Mage::getStoreConfig('customfield/admin1/allowfiles')?>)</span>

                            <?php 
                            echo '
                            </div>';
                            break;

                         case 'image':
                            echo '
                            <div class="input-box">';
                            ?>
                            <input type="file" name='<?php echo "billing[".$attr['attribute_code']."]"; ?>' id='<?php echo $attr['attribute_code']; ?>' <?php if ($attr['is_required']) {
                                ?> class="wk_imagevalidate required-entry input-text" <?php 
                            } else {
                                ?> class="wk_imagevalidate input-text"  <?php 
                            }?>/>
                            <input type="hidden" value="" id="_accountfiles_value" name="account[files][value]">
                            <span class="wk_cf_hints">(<?php echo $this->__('Allowed Extensions are '). Mage::getStoreConfig('customfield/admin1/allowimages');?>)</span>

                            <?php 
                            echo '
                            </div>';
                            break;
                    }

                        echo '
						</li>';
                    }
                }
            } ?>
				</ul>
			</div>
			<!--<div class="buttons-set">
	            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	            <button type="submit" title="<?php echo $this->quoteEscape($this->__('Register')) ?>" class="button"><span><span><?php echo $this->__('Register') ?></span></span></button>
	        </div>-->
	        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
	            <input name="context" type="hidden" value="checkout" />
	        <?php endif ?>

<!-- 2023-11-21 Dmitrii Fediuk https://upwork.com/fl/mage2pro
1) "The «CONTINUE» button does not work on the «BILLING INFORMATION» screen on the `/checkout/onepage/`
in the «Checkout as Guest» scenario": https://github.com/thehcginstitute-com/m1/issues/13
2) This `</form>` tag seems to be wrong.
It breaks the code:
https://github.com/thehcginstitute-com/m1/blob/2023-01-16-1/app/design/frontend/default/mobileshoppe/template/magepsycho/customerregfields/checkout/onepage/billing.phtml#L221-L225
The form key becames outside of the form, Chrome ignores it, and Magento does not proceed without the key:
https://github.com/thehcginstitute-com/m1/blob/2023-01-16-1/app/code/core/Mage/Checkout/controllers/OnepageController.php#L370-L372
			</form>
-->
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if ($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif ?>
    //]]>
    </script>

			<script type="text/javascript">
				if(typeof jQuery == "undefined"){
					document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
				}
			</script>
			<script type="text/javascript">
				jQuery.noConflict();
				//<![CDATA[
				enUS = {"m":{"wide":["January","February","March","April","May","June","July","August","September","October","November","December"],"abbr":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]}}; // en_US locale reference
				Calendar._DN = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]; // full day names
				Calendar._SDN = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]; // short day names
				Calendar._FD = 0; // First day of the week. "0" means display Sunday first, "1" means display Monday first, etc.
				Calendar._MN = ["January","February","March","April","May","June","July","August","September","October","November","December"]; // full month names
				Calendar._SMN = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]; // short month names
				Calendar._am = "AM"; // am/pm
				Calendar._pm = "PM";

				// tooltips
				Calendar._TT = {};
				Calendar._TT["INFO"] = "About the calendar";

				Calendar._TT["ABOUT"] =
				"DHTML Date/Time Selector\n" +
				"(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" +
				"For latest version visit: http://www.dynarch.com/projects/calendar/\n" +
				"Distributed under GNU LGPL. See http://gnu.org/licenses/lgpl.html for details." +
				"\n\n" +
				"Date selection:\n" +
				"- Use the \xab, \xbb buttons to select year\n" +
				"- Use the " + String.fromCharCode(0x2039) + ", " + String.fromCharCode(0x203a) + " buttons to select month\n" +
				"- Hold mouse button on any of the above buttons for faster selection.";
				Calendar._TT["ABOUT_TIME"] = "\n\n" +
				"Time selection:\n" +
				"- Click on any of the time parts to increase it\n" +
				"- or Shift-click to decrease it\n" +
				"- or click and drag for faster selection.";

				Calendar._TT["PREV_YEAR"] = "Prev. year (hold for menu)";
				Calendar._TT["PREV_MONTH"] = "Prev. month (hold for menu)";
				Calendar._TT["GO_TODAY"] = "Go Today";
				Calendar._TT["NEXT_MONTH"] = "Next month (hold for menu)";
				Calendar._TT["NEXT_YEAR"] = "Next year (hold for menu)";
				Calendar._TT["SEL_DATE"] = "Select date";
				Calendar._TT["DRAG_TO_MOVE"] = "Drag to move";
				Calendar._TT["PART_TODAY"] = ' (' + "Today" + ')';

				// the following is to inform that "%s" is to be the first day of week
				Calendar._TT["DAY_FIRST"] = "Display %s first";

				// This may be locale-dependent. It specifies the week-end days, as an array
				// of comma-separated numbers. The numbers are from 0 to 6: 0 means Sunday, 1
				// means Monday, etc.
				Calendar._TT["WEEKEND"] = "0,6";

				Calendar._TT["CLOSE"] = "Close";
				Calendar._TT["TODAY"] = "Today";
				Calendar._TT["TIME_PART"] = "(Shift-)Click or drag to change value";

				// date formats
				Calendar._TT["DEF_DATE_FORMAT"] = "%b %e, %Y";
				Calendar._TT["TT_DATE_FORMAT"] = "%B %e, %Y";

				Calendar._TT["WK"] = "Week";
				Calendar._TT["TIME"] = "Time:";

				CalendarDateObject._LOCAL_TIMZEONE_OFFSET_SECONDS = -28800;
				CalendarDateObject._SERVER_TIMZEONE_SECONDS = 1411978594;

				//]]>

				 var imgreq = "<?php echo Mage::getStoreConfig('customfield/admin1/allowimages'); ?>"; console.log(imgreq);
					        imgarr = imgreq.split(',');
					        var filereq = "<?php echo Mage::getStoreConfig('customfield/admin1/allowfiles'); ?>"; 
					        fileimg = filereq.split(',');
					        console.log(imgreq);
					        jQuery("body").delegate('.wk_imagevalidate',"change",function(){
					            var ext = jQuery(this).val().split('.').pop().toLowerCase();
					            if(jQuery.inArray(ext, imgarr) == -1) {
					                jQuery(this).val('');
					                alert('<?php echo $this->__(" Invalid extension! Please upload an allowed extension file. ")?>');
					            }
					        });
					        
					        jQuery("body").delegate('.wk_filevalidate',"change",function(){
					            var ext = jQuery(this).val().split('.').pop().toLowerCase();
					            if(jQuery.inArray(ext, fileimg) == -1) {
					                jQuery(this).val('');
					                alert('<?php echo $this->__(" Invalid extension! Please upload an allowed extension file. ")?>');
					            }
					        });

				jQuery(document).ready(function(){
					// jQuery("#password").parents(".fieldset").after(jQuery("#wkadditionalinfo"));
					jQuery("#wkadditionalinfo").show();
					jQuery(".button").click(function(){
						haserror = false;
						jQuery(".additional_radio").each(function(){
							this_this = jQuery(this);
							this_this.removeClass("validation-failed");
							this_this.nextAll(".validation-advice").remove();
							if(this_this.hasClass("required-entry")){
								val = this_this.find("input[type='radio']:checked").val();
								if(typeof val == "undefined"){
									haserror = true;
									this_this.addClass("validation-failed");
									this_this.after("<div class='validation-advice'>This is a required field.</div>");
								}
							}
						});

						if(haserror == true && dataForm.validator.validate())
							return false;
					});
					jQuery("#form-validate").attr("enctype","multipart/form-data");
				});
				/**
				*This function show and hides the dependants.
				**/
				function open_dependant(this_this){
					if(jQuery(this_this).val() == 1)
						jQuery(this_this).parents(".field").next(".field").show();
					else
						jQuery(this_this).parents(".field").next(".field").hide();
				}
<?php             foreach ($DOB as $value) {
                ?>
					Calendar.setup({
						inputField : "dob-<?php echo $value; ?>",
						ifFormat : "%m/%d/%Y",
						button : "dob_trig-<?php echo $value; ?>",
						align : "Br",
						singleClick : true
					});
<?php 
            } ?>
			</script>
<?php 
        }
    }    ?>

