<!-- 
 /**
 * @category   Webkul
 * @package    Webkul_CustomField
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */  -->
<style type="text/css">
#wkadditionalinfo{
	/*display:none;*/
}
#wkadditionalinfo .input-box{
    width:100%;
}
.input-box img{
    display:inline-block;
}
.wk_cf_hints{
	color: #e11e1e;
    font-weight: bold;
    margin-left: 10px;
}
</style>
<div class="account-create">
    <div class="page-title">
        <h1><?php echo $this->__('Create an Account') ?></h1>
    </div>
    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->toHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" class="scaffold-form" enctype="multipart/form-data">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
<!-- 2023-01-16 Dmitrii Fediuk https://www.upwork.com/fl/mage2pro
"Make the `Webkul_CustomField` module compatible with the `MagePsycho_Customerregfields` module":
https://github.com/thehcginstitute-com/m1/issues/8 -->
            <h2 class="legend"><?php echo $this->__('Personal Information') ?></h2>
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            <ul class="form-list wkform">
                <li class="fields">
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
                </li>
                <li>
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                    <div class="input-box">
                        <input type="email" autocapitalize="off" autocorrect="off" spellcheck="false" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->quoteEscape($this->__('Email Address')) ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
<!-- 2023-01-16 Dmitrii Fediuk https://www.upwork.com/fl/mage2pro
1) "Make the `Webkul_CustomField` module compatible with the `MagePsycho_Customerregfields` module":
https://github.com/thehcginstitute-com/m1/issues/8
2) `MagePsycho_Customerregfields`
2.1)
https://github.com/thehcginstitute-com/m1/blob/2023-01-16-1/app/design/frontend/default/mobileshoppe/template/magepsycho/customerregfields/customer/form/register.phtml#L58-L77
2.2) @see MagePsycho_Customerregfields_Helper_Data::switchCustomerFormRegisterTemplateIf():
	if ($this->enabled()) {
		return 'magepsycho/customerregfields/customer/form/register.phtml';
	}
	else {
		return 'persistent/customer/form/register.phtml';
	}
https://github.com/thehcginstitute-com/m1/blob/2023-01-16-1/app/code/local/MagePsycho/Customerregfields/Helper/Data.php#L206-L213
2.3)
<customer_account_create>
	<reference name="customer_form_register">
		<action method="setTemplate" ifconfig="magepsycho_customerregfields/option/active">
			<template helper="magepsycho_customerregfields/switchCustomerFormRegisterTemplateIf" />
		</action>
	</reference>
</customer_account_create>
https://github.com/thehcginstitute-com/m1/blob/2023-01-16-1/app/design/frontend/default/mobileshoppe/layout/magepsycho_customerregfields.xml#L12-L18
3) `Webkul_CustomField`:
	<customer_account_create>
        <reference name="customer_form_register">
            <action method="setTemplate"><template>customfield/customfields.phtml</template></action>
        </reference>
https://github.com/thehcginstitute-com/m1/blob/2023-01-16-1/app/design/frontend/base/default/layout/customfield.xml#L11-L14
-->
			<li>
				<?=
					$this->getLayout()
						->createBlock('magepsycho_customerregfields/customer_widget_type')
						->setObject($this->getFormData())
						->setIsEditPage(false)
						->toHtml()
				?>
			</li>
			<li>
				<label for="telephone" class="required"><em>*</em><?= $this->__('Telephone') ?></label>
				<div class="input-box">
					<input
						type="text"
						name="telephone"
						id="telephone"
						value="<?= $this->escapeHtml($this->getFormData()->getTelephone()) ?>"
						title="<?= Mage::helper('core')->quoteEscape($this->__('Telephone')) ?>"
						class="input-text <?= $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>"
					/>
				</div>
			</li>
			<?php if ($this->isNewsletterEnabled()): ?>
				<li class="control">
					<div class="input-box">
						<input type="checkbox" name="is_subscribed" title="<?php echo $this->quoteEscape($this->__('Sign Up for Newsletter')) ?>" value="1" id="is_subscribed"<?php if ($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
					</div>
					<label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
				</li>
			<?php endif ?>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>

            <?php if ($this->getShowAddressFields()): ?>
                <li class="hidden">
                    <input type="hidden" name="create_address" value="1" />
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="company"><?php echo $this->__('Company') ?></label>
                        <div class="input-box">
                            <input type="text" name="company" id="company" value="<?php echo $this->escapeHtml($this->getFormData()->getCompany()) ?>" title="<?php echo $this->quoteEscape($this->__('Company')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                        <div class="input-box">
                            <input type="tel" name="telephone" id="telephone" value="<?php echo $this->escapeHtml($this->getFormData()->getTelephone()) ?>" title="<?php echo $this->quoteEscape($this->__('Telephone')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" />
                        </div>
                    </div>
                </li>
            <?php $_streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
                <li class="wide">
                    <label for="street_1" class="required"><em>*</em><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet(0)) ?>" title="<?php echo $this->quoteEscape($this->__('Street Address')) ?>" id="street_1" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
            <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                <li class="wide">
                    <label for="billing:street<?php echo $_i ?>"><?php echo $this->__('Street Address %s', $_i) ?></label>
                    <div class="input-box">
                        <input type="text" name="street[]" value="<?php echo $this->escapeHtml($this->getFormData()->getStreet($_i - 1)) ?>" title="<?php echo $this->quoteEscape($this->__('Street Address %s', $_i)) ?>" id="street_<?php echo $_i ?>" class="input-text <?php echo $_streetValidationClass ?>" />
                    </div>
                </li>
            <?php endfor; ?>
                <li class="fields">
                    <div class="field">
                        <label for="city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                        <div class="input-box">
                            <input type="text" name="city" value="<?php echo $this->escapeHtml($this->getFormData()->getCity()) ?>" title="<?php echo $this->quoteEscape($this->__('City')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('city') ?>" id="city" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="region_id" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                        <div class="input-box">
                            <select id="region_id" name="region_id" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="validate-select" style="display:none;">
                                <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                            </select>
                            <script type="text/javascript">
                            //<![CDATA[
                                $('region_id').setAttribute('defaultValue', "<?php echo $this->getFormData()->getRegionId() ?>");
                            //]]>
                            </script>
                            <input type="text" id="region" name="region" value="<?php echo $this->escapeHtml($this->getRegion()) ?>" title="<?php echo $this->quoteEscape($this->__('State/Province')) ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>" style="display:none;" />
                        </div>
                    </div>
                </li>
                <li class="fields">
                    <div class="field">
                        <label for="zip" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                        <div class="input-box">
                            <input type="text" name="postcode" value="<?php echo $this->escapeHtml($this->getFormData()->getPostcode()) ?>" title="<?php echo $this->quoteEscape($this->__('Zip/Postal Code')) ?>" id="zip" class="input-text validate-zip-international <?php echo $this->helper('customer/address')->getAttributeValidationClass('postcode') ?>" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="country" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                        <div class="input-box">
                            <?php echo $this->getCountryHtmlSelect() ?>
                        </div>
                    </div>
                </li>
                <li class="hidden">
                    <input type="hidden" name="default_billing" value="1" />
                    <input type="hidden" name="default_shipping" value="1" />
                </li>
            <?php endif; ?>
			</ul>
		</div>
<!-- 2023-01-16 Dmitrii Fediuk https://www.upwork.com/fl/mage2pro
"Make the `Webkul_CustomField` module compatible with the `MagePsycho_Customerregfields` module":
https://github.com/thehcginstitute-com/m1/issues/8 -->
		<div class="fieldset">
            <h2 class="legend"><?php echo $this->__('Login Information') ?></h2>
			<?= $this->getLayout()->createBlock('cms/block')->setBlockId('confirm_message')->toHtml() ?>
			<ul class="form-list">
                <li class="fields">
                    <div class="field">
                        <label for="password" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="password" id="password" title="<?php echo $this->quoteEscape($this->__('Password')) ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="confirmation" class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="confirmation" title="<?php echo $this->quoteEscape($this->__('Confirm Password')) ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>
			</ul>
		</div>
		<div class="fieldset">
			<ul class="form-list">
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>
            

<link rel="stylesheet" type="text/css" href="<?php echo Mage::getBaseUrl('js').'calendar/calendar-win2k-1.css'; ?>" />
<script src="<?php echo Mage::getBaseUrl('js').'calendar/calendar.js'; ?>" type="text/javascript"></script>
<script src="<?php echo Mage::getBaseUrl('js').'calendar/calendar-setup.js'; ?>" type="text/javascript"></script>
<?php	
        $collection = Mage::getModel("customfield/customfields")->getCollection()->addFilter('status', 1);
        $DOB = array();
        $allAttrIds=array();
        foreach ($collection as $value) {
            $allAttrIds[]=$value->getCustomerAttributeId();
        }
        if ($collection->getSize()) {
            ?>
			<div class="fieldset" id="wkadditionalinfo">
				<h2 class="legend"><?php echo $this->__("Additional Information") ?></h2>
				<ul class="form-list">
    <?php 
                    $var_attrs = array(); // will be used in JS
                    $model = 'customer/attribute_collection';
            $type='customer';
            $collection = Mage::getResourceModel($model)
                        ->setEntityTypeFilter(Mage::getModel('eav/entity')->setType($type)->getTypeId())
                        ->addFilter('is_user_defined', 1)->setOrder('sort_order', 'ASC');
            $collection->join(
                            array('customfields' => "customfield/customfields"),
                            'main_table.attribute_id=customfields.customer_attribute_id',
                            array('status','dependable_inputname','dependent_on')
                        )->addFilter('status', 1)
                        ->addFieldToFilter('dependent_on',array("null" => true));
            
            $store_id = Mage::app()->getStore()->getId();
                
            foreach ($collection as $attribute) {
                $attr = $attribute->toArray();
                if($attr['dependable_inputname']!="" && $attr['frontend_input']=="select"){
                    $attr['frontend_input']="dependable";
                }
                $customCollection=Mage::getModel('customfield/customfields')->getCollection()->addFieldToFilter('customer_attribute_id', $attr['attribute_id']);
                    
                $visibleInFormCheck=0;
                foreach ($customCollection as  $value) {
                    $d=$value->getData();
                    if ($d['viewinforms']) {
                        $forms=explode(',', $d['viewinforms']);
                        foreach ($forms as $key => $val) {
                            if ($val=='customer_account_edit') {
                                $visibleInFormCheck=1;
                            }
                        }
                    }
                }
                if ($visibleInFormCheck) {
                    if (in_array($attr['attribute_id'], $allAttrIds)) {
                        $attr['is_required']=$attr['note'];
                        if ($attr['is_required']) {
                            $var_attrs[] = $attr['attribute_code'];
                        }
                    
                        $store_labels = $attribute->getStoreLabels();
                        $label = $store_labels[$store_id] ? $store_labels[$store_id] : $attr['frontend_label'];
                    
                        echo '<li>';
                        $func = 'get'.  str_replace(' ', '', ucwords(str_replace('_', ' ', $attr['attribute_code'])));

                        echo '<label for="'. $attr['attribute_code'] .'" '. ($attr['is_required']?'class="required"><em>*</em>':'>') . $this->__($label) . '</label>';
                        
                        switch ($attr['frontend_input']) {
                            case 'text':
                            ?>
                            <div class="input-box">
                                <input type="text" name="<?php echo $attr['attribute_code']; ?>" id="<?php echo $attr['attribute_code']; ?>" value="" class="input-text <?php if ($attr['is_required']) {
                                echo 'required-entry ';
                            } echo $attr['frontend_class']; ?>" />
                            </div>
                            <?php
                                break;
                        
                            case 'radio':
                                echo '
                                <div class="input-box">';
                                foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                    echo '<input type="radio"  name="'. $attr['attribute_code'] .'" value="'.$instance['value'].'" '.  ($this->htmlEscape(Mage_Customer_Block_Form_register::getFormData()->$func()) == $instance['value'] ? 'selected' : '') .'>' . $instance['label'] . '</input>';
                                }

                                echo '
                                </div>';
                                break;
                            
                            case 'select':
                                echo '
                                <div class="input-box">';
                                echo '<select name="'. $attr['attribute_code'] .'" id="'. $attr['attribute_code'] .'" >';
                                foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                    echo '<option value="'.$instance['value'].'" '.  ($this->htmlEscape(Mage_Customer_Block_Form_register::getFormData()->$func()) == $instance['value'] ? 'selected' : '') .'>' . $instance['label'] . '</option>';
                                }
                                echo '</select>';

                                echo '
                                </div>';
                                break;

                            case 'textarea':
                                if ($attr['default_value']==1) {
                                    $niced = 'niceedits';
                                }
                                ?>
                                <div class="input-box">
                                    <textarea name="<?php echo $attr['attribute_code']; ?>" id="<?php echo $attr['attribute_code']; ?>" class="<?php if ($attr['is_required']) {
                                    echo 'required-entry ';
                                } echo $attr['frontend_class']; ?>" ><?php echo $this->htmlEscape(Mage_Customer_Block_Form_register::getFormData()->$func()); ?></textarea>
                                </div>
                                <?php
                                    break;

                            case 'multiselect':
                                echo '
                                <div class="input-box">';
                                echo '<select name="'. $attr['attribute_code'] .'[]" id="'. $attr['attribute_code'] .'" multiple="multiple"  class="'.($attr["is_required"]?"required-entry":"").'">';
                                
                                $multi_values = explode(',', $this->htmlEscape($this->getFormData()->$func()));

                                foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                    echo '<option value="'.$instance['value'].'" '.  (in_array($instance['value'], $multi_values) ? 'selected' : '') .'>' . $instance['label'] . '</option>';
                                }
                                echo '</select>';
                                break;
                                
                            case 'date':
                                echo '
                                <div class="input-box">
                                    <input type="text" name="'. $attr['attribute_code'] .'" id="'. $attr['attribute_code'] .'" value="'. $this->htmlEscape($this->getFormData()->$func()) .'" class="input-text validate-date '.($attr["is_required"]?"required-entry":"").'" style="width:110px !important;" />
                                    <img style="cursor: pointer;" title="'. $this->__('Select Date') .'" id="'.$attr['attribute_code'].'_trig" class="v-middle" alt="" src="'. str_replace("base", "default", $this->getSkinUrl('images/grid-cal.gif', array('_area'=>'adminhtml'))) .'">
                                </div>';
                                echo'<div class="validation-advice" id="advice-validate-date-'. $attr['attribute_code'] .'"  style="opacity: 0; display: none;">Please enter a valid date.</div>';
                                if($attr['is_required']){
                                    echo '<div class="validation-advice" id="advice-required-entry-'. $attr['attribute_code'] .'" style="opacity: 0; display: none;">This is a required field.</div>';
                                }
                                echo '<script type="text/javascript">
                                        Calendar.setup({
                                            inputField : "'.$attr['attribute_code'].'",
                                            ifFormat : "'. Varien_Date::convertZendToStrFtime(Mage::app()->getLocale()->getDateFormatWithLongYear(), true, false) .'", 
                                            button : "'.$attr['attribute_code'].'_trig",
                                            showsTime: false,
                                            align : "Bl",
                                            singleClick : true
                                        });
                                    </script>';
                                break;

                            case 'file':
                                echo '
                                <div class="input-box">';
                                ?>
                                <input type="file" name='<?php echo $attr['attribute_code']; ?>' id='<?php echo $attr['attribute_code']; ?>' <?php if ($attr['is_required']) {
                                    ?> class="wk_filevalidate required-entry input-text" <?php 
                                } else {
                                    ?> class="wk_filevalidate input-text"  <?php 
                                }?>/>
                                <input type="hidden" value="" id="_accountfiles_value" name="account[files][value]">
                                <span class="wk_cf_hints">(<?php echo $this->__('Allowed Extensions are '). Mage::getStoreConfig('customfield/admin1/allowfiles')?>)</span>

                                <?php 
                                echo '
                                </div>';
                                break;

                            case 'image':
                                echo '
                                <div class="input-box">';
                                ?>
                                <input type="file" name='<?php echo $attr['attribute_code']; ?>' id='<?php echo $attr['attribute_code']; ?>' <?php if ($attr['is_required']) {
                                    ?> class="wk_imagevalidate required-entry input-text" <?php 
                                } else {
                                    ?> class="wk_imagevalidate input-text"  <?php 
                                }?>/>
                                <input type="hidden" value="" id="_accountfiles_value" name="account[files][value]">
                                <span class="wk_cf_hints">(<?php echo $this->__('Allowed Extensions are '). Mage::getStoreConfig('customfield/admin1/allowimages');?>)</span>

                                <?php 
                                echo '
                                </div>';
                                break;

                            case 'dependable':
                                echo '
                                <div class="input-box">';
                                echo '<select class="dependable" name="'. $attr['attribute_code'] .'" id="'. $attr['attribute_code'] .'" >';
                                foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                    echo '<option value="'.$instance['value'].'" '.  ($this->htmlEscape(Mage_Customer_Block_Form_register::getFormData()->$func()) == $instance['value'] ? 'selected' : '') .'>' . $instance['label'] . '</option>';
                                }
                                echo '</select>';

                                echo '
                                </div>';
                                
                                //adsad
                                $dependentCollection = Mage::getResourceModel($model)
                                            ->setEntityTypeFilter(Mage::getModel('eav/entity')->setType($type)->getTypeId())
                                            ->addFilter('is_user_defined', 1)->setOrder('sort_order', 'ASC');
                                $dependentCollection->join(
                                                array('customfields' => "customfield/customfields"),
                                                'main_table.attribute_id=customfields.customer_attribute_id',
                                                array('status','dependable_inputname','dependent_on')
                                            )->addFieldToFilter('dependent_on',array("notnull" => true));
                                $dependentCollection->addFieldToFilter('attribute_code', $attr['dependable_inputname']);
                                
                                $attribute=$dependentCollection->getFirstItem();
                                $attr = $attribute->toArray();
                                $store_labels = $attribute->getStoreLabels();
                                $label = $store_labels[$store_id] ? $store_labels[$store_id] : $attr['frontend_label'];
                                
                                $attr['is_required']=$attr['note'];
                                echo '<li class="dependent">';
                                $func = 'get'.  str_replace(' ', '', ucwords(str_replace('_', ' ', $attr['attribute_code'])));

                                echo '<label for="'. $attr['attribute_code'] .'" '. ($attr['is_required']?'class="required"><em>*</em>':'>') . $this->__($label) . '</label>';
                                switch ($attr['frontend_input']) {
                                    case 'text':
                                    ?>
                                    <div class="input-box">
                                        <input type="text" name="<?php echo $attr['attribute_code']; ?>" id="<?php echo $attr['attribute_code']; ?>" value="" class="input-text <?php if ($attr['is_required']) {
                                        echo 'required-entry ';
                                    } echo $attr['frontend_class']; ?>" />
                                    </div>
                                    <?php
                                        break;
                                
                                    case 'radio':
                                        echo '
                                        <div class="input-box">';
                                        foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                            echo '<input type="radio"  name="'. $attr['attribute_code'] .'" value="'.$instance['value'].'" '.  ($this->htmlEscape(Mage_Customer_Block_Form_register::getFormData()->$func()) == $instance['value'] ? 'selected' : '') .'>' . $instance['label'] . '</input>';
                                        }

                                        echo '
                                        </div>';
                                        break;
                                    
                                    case 'select':
                                        echo '
                                        <div class="input-box">';
                                        echo '<select name="'. $attr['attribute_code'] .'" id="'. $attr['attribute_code'] .'" >';
                                        foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                            echo '<option value="'.$instance['value'].'" '.  ($this->htmlEscape(Mage_Customer_Block_Form_register::getFormData()->$func()) == $instance['value'] ? 'selected' : '') .'>' . $instance['label'] . '</option>';
                                        }
                                        echo '</select>';

                                        echo '
                                        </div>';
                                        break;

                                    case 'textarea':
                                        if ($attr['default_value']==1) {
                                            $niced = 'niceedits';
                                        }
                                        ?>
                                        <div class="input-box">
                                            <textarea name="<?php echo $attr['attribute_code']; ?>" id="<?php echo $attr['attribute_code']; ?>" class="<?php if ($attr['is_required']) {
                                            echo 'required-entry ';
                                        } echo $attr['frontend_class']; ?>" ><?php echo $this->htmlEscape(Mage_Customer_Block_Form_register::getFormData()->$func()); ?></textarea>
                                        </div>
                                        <?php
                                            break;

                                    case 'multiselect':
                                        echo '
                                        <div class="input-box">';
                                        echo '<select name="'. $attr['attribute_code'] .'[]" id="'. $attr['attribute_code'] .'" multiple="multiple"  class="'.($attr["is_required"]?"required-entry":"").'">';
                                        
                                        $multi_values = explode(',', $this->htmlEscape($this->getFormData()->$func()));

                                        foreach ($attribute->getSource()->getAllOptions((!$attr['is_required']), false) as $instance) {
                                            echo '<option value="'.$instance['value'].'" '.  (in_array($instance['value'], $multi_values) ? 'selected' : '') .'>' . $instance['label'] . '</option>';
                                        }
                                        echo '</select>';
                                        break;
                                        
                                    case 'date':
                                        echo '
                                        <div class="input-box">
                                            <input type="text" name="'. $attr['attribute_code'] .'" id="'. $attr['attribute_code'] .'" value="'. $this->htmlEscape($this->getFormData()->$func()) .'" class="input-text validate-date '.($attr["is_required"]?"required-entry":"").'" style="width:110px !important;" />
                                            <img style="cursor: pointer;" title="'. $this->__('Select Date') .'" id="'.$attr['attribute_code'].'_trig" class="v-middle" alt="" src="'. str_replace("base", "default", $this->getSkinUrl('images/grid-cal.gif', array('_area'=>'adminhtml'))) .'">
                                        </div>';
                                        echo'<div class="validation-advice" id="advice-validate-date-'. $attr['attribute_code'] .'"  style="opacity: 0; display: none;">Please enter a valid date.</div>';
                                        if ($attr['is_required']) {
                                            echo '<div class="validation-advice" id="advice-required-entry-'. $attr['attribute_code'] .'" style="opacity: 0; display: none;">This is a required field.</div>';
                                        }
                                        echo '<script type="text/javascript">
                                                Calendar.setup({
                                                    inputField : "'.$attr['attribute_code'].'",
                                                    ifFormat : "'. Varien_Date::convertZendToStrFtime(Mage::app()->getLocale()->getDateFormatWithLongYear(), true, false) .'", 
                                                    button : "'.$attr['attribute_code'].'_trig",
                                                    showsTime: false,
                                                    align : "Bl",
                                                    singleClick : true
                                                });
                                            </script>';
                                        break;

                                    case 'file':
                                        echo '
                                        <div class="input-box">';
                                        ?>
                                        <input type="file" name='<?php echo $attr['attribute_code']; ?>' id='<?php echo $attr['attribute_code']; ?>' <?php if ($attr['is_required']) {
                                            ?> class="wk_filevalidate required-entry input-text" <?php 
                                        } else {
                                            ?> class="wk_filevalidate input-text"  <?php 
                                        }?>/>
                                        <input type="hidden" value="" id="_accountfiles_value" name="account[files][value]">
                                        <span class="wk_cf_hints">(<?php echo $this->__('Allowed Extensions are '). Mage::getStoreConfig('customfield/admin1/allowfiles')?>)</span>

                                        <?php 
                                        echo '
                                        </div>';
                                        break;

                                    case 'image':
                                        echo '
                                        <div class="input-box">';
                                        ?>
                                        <input type="file" name='<?php echo $attr['attribute_code']; ?>' id='<?php echo $attr['attribute_code']; ?>' <?php if ($attr['is_required']) {
                                            ?> class="wk_imagevalidate required-entry input-text" <?php 
                                        } else {
                                            ?> class="wk_imagevalidate input-text"  <?php 
                                        }?>/>
                                        <input type="hidden" value="" id="_accountfiles_value" name="account[files][value]">
                                        <span class="wk_cf_hints">(<?php echo $this->__('Allowed Extensions are '). Mage::getStoreConfig('customfield/admin1/allowimages');?>)</span>

                                        <?php 
                                        echo '
                                        </div>';
                                        break;
                                }
                                //sad
                                break;

                        }

                        echo '
						</li>';
                    }
                }
            } ?>
				</ul>
			</div>
            <?php 
        }    ?>

			<div class="buttons-set">
	            <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>" class="back-link"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
	            <button type="submit" title="<?php echo $this->quoteEscape($this->__('Register')) ?>" class="button"><span><span><?php echo $this->__('Register') ?></span></span></button>
	        </div>
	        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
	            <input name="context" type="hidden" value="checkout" />
	        <?php endif; ?>
			</form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if ($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
</div>
			<script type="text/javascript">
				if(typeof jQuery == "undefined"){
					document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
				}
			</script>
			<script type="text/javascript">
				jQuery.noConflict();
				//<![CDATA[
				enUS = {"m":{"wide":["January","February","March","April","May","June","July","August","September","October","November","December"],"abbr":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]}}; // en_US locale reference
				Calendar._DN = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]; // full day names
				Calendar._SDN = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"]; // short day names
				Calendar._FD = 0; // First day of the week. "0" means display Sunday first, "1" means display Monday first, etc.
				Calendar._MN = ["January","February","March","April","May","June","July","August","September","October","November","December"]; // full month names
				Calendar._SMN = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]; // short month names
				Calendar._am = "AM"; // am/pm
				Calendar._pm = "PM";

				// tooltips
				Calendar._TT = {};
				Calendar._TT["INFO"] = "About the calendar";

				Calendar._TT["ABOUT"] =
				"DHTML Date/Time Selector\n" +
				"(c) dynarch.com 2002-2005 / Author: Mihai Bazon\n" +
				"For latest version visit: http://www.dynarch.com/projects/calendar/\n" +
				"Distributed under GNU LGPL. See http://gnu.org/licenses/lgpl.html for details." +
				"\n\n" +
				"Date selection:\n" +
				"- Use the \xab, \xbb buttons to select year\n" +
				"- Use the " + String.fromCharCode(0x2039) + ", " + String.fromCharCode(0x203a) + " buttons to select month\n" +
				"- Hold mouse button on any of the above buttons for faster selection.";
				Calendar._TT["ABOUT_TIME"] = "\n\n" +
				"Time selection:\n" +
				"- Click on any of the time parts to increase it\n" +
				"- or Shift-click to decrease it\n" +
				"- or click and drag for faster selection.";

				Calendar._TT["PREV_YEAR"] = "Prev. year (hold for menu)";
				Calendar._TT["PREV_MONTH"] = "Prev. month (hold for menu)";
				Calendar._TT["GO_TODAY"] = "Go Today";
				Calendar._TT["NEXT_MONTH"] = "Next month (hold for menu)";
				Calendar._TT["NEXT_YEAR"] = "Next year (hold for menu)";
				Calendar._TT["SEL_DATE"] = "Select date";
				Calendar._TT["DRAG_TO_MOVE"] = "Drag to move";
				Calendar._TT["PART_TODAY"] = ' (' + "Today" + ')';

				// the following is to inform that "%s" is to be the first day of week
				Calendar._TT["DAY_FIRST"] = "Display %s first";

				// This may be locale-dependent. It specifies the week-end days, as an array
				// of comma-separated numbers. The numbers are from 0 to 6: 0 means Sunday, 1
				// means Monday, etc.
				Calendar._TT["WEEKEND"] = "0,6";

				Calendar._TT["CLOSE"] = "Close";
				Calendar._TT["TODAY"] = "Today";
				Calendar._TT["TIME_PART"] = "(Shift-)Click or drag to change value";

				// date formats
				Calendar._TT["DEF_DATE_FORMAT"] = "%b %e, %Y";
				Calendar._TT["TT_DATE_FORMAT"] = "%B %e, %Y";

				Calendar._TT["WK"] = "Week";
				Calendar._TT["TIME"] = "Time:";

				CalendarDateObject._LOCAL_TIMZEONE_OFFSET_SECONDS = -28800;
				CalendarDateObject._SERVER_TIMZEONE_SECONDS = 1411978594;

				//]]>

				 var imgreq = "<?php echo Mage::getStoreConfig('customfield/admin1/allowimages'); ?>"; console.log(imgreq);
					        imgarr = imgreq.split(',');
					        var filereq = "<?php echo Mage::getStoreConfig('customfield/admin1/allowfiles'); ?>"; 
					        fileimg = filereq.split(',');
					        console.log(imgreq);
					        jQuery("body").delegate('.wk_imagevalidate',"change",function(){
					            var ext = jQuery(this).val().split('.').pop().toLowerCase();
					            if(jQuery.inArray(ext, imgarr) == -1) {
					                jQuery(this).val('');
					                alert('<?php echo $this->__(" Invalid extension! Please upload an allowed extension file. ")?>');
					            }
					        });
					        
					        jQuery("body").delegate('.wk_filevalidate',"change",function(){
					            var ext = jQuery(this).val().split('.').pop().toLowerCase();
					            if(jQuery.inArray(ext, fileimg) == -1) {
					                jQuery(this).val('');
					                alert('<?php echo $this->__(" Invalid extension! Please upload an allowed extension file. ")?>');
					            }
					        });

				jQuery(document).ready(function(){
					// jQuery("#password").parents(".fieldset").after(jQuery("#wkadditionalinfo"));
					jQuery("#wkadditionalinfo").show();
					jQuery(".button").click(function(){
						haserror = false;
						jQuery(".additional_radio").each(function(){
							this_this = jQuery(this);
							this_this.removeClass("validation-failed");
							this_this.nextAll(".validation-advice").remove();
							if(this_this.hasClass("required-entry")){
								val = this_this.find("input[type='radio']:checked").val();
								if(typeof val == "undefined"){
									haserror = true;
									this_this.addClass("validation-failed");
									this_this.after("<div class='validation-advice'>This is a required field.</div>");
								}
							}
						});

						if(haserror == true && dataForm.validator.validate())
							return false;
					});
                    jQuery(".dependable").each(function(){
                        if(jQuery(this).val()==0){
                            jQuery(this).closest("li").next(".dependent").hide();
                        }else{
                            jQuery(this).closest("li").next(".dependent").show();                            
                        }
                    });
					jQuery("#form-validate").attr("enctype","multipart/form-data");
                    jQuery(".dependable").change(function(){
                        if(jQuery(this).val()==0){
                            jQuery(this).closest("li").next(".dependent").hide();
                        }else{
                            jQuery(this).closest("li").next(".dependent").show();                            
                        }
                    });
				});
				/**
				*This function show and hides the dependants.
				**/
				function open_dependant(this_this){
					if(jQuery(this_this).val() == 1)
						jQuery(this_this).parents(".field").next(".field").show();
					else
						jQuery(this_this).parents(".field").next(".field").hide();
				}
<?php             foreach ($DOB as $value) {
                ?>
					Calendar.setup({
						inputField : "dob-<?php echo $value; ?>",
						ifFormat : "%m/%d/%Y",
						button : "dob_trig-<?php echo $value; ?>",
						align : "Br",
						singleClick : true
					});
<?php 
            } ?>
			</script>

