<!-- /**
/**
 * @category   Webkul
 * @package    Webkul_CustomField
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */   -->
<style type="text/css">
.wktermsprivacyli{
    list-style: none;
}
#wk_term_privacy_fade{
	background-color: #000000;
    display: none;
    height: 100%;
    left: 0;
    opacity: 0.7;
    position: fixed;
    top: 0;
    width: 100%;
    z-index: 1001;
}
#wk_term_privacy{
	background-color:<?php echo Mage::helper('customfield')->getBgColor();?> !important;
    border: 2px solid #cccccc;
    bottom: 15%;
    left: 15%;
    overflow: visible;
    padding: 10px;
    position: fixed;
    right: 15%;
    top: 15%;
    width: 68%;
    z-index: 65557;
    overflow: hidden;
    background: gainsboro;
}.wkbutton{
	float: right;
	color: <?php echo Mage::helper('customfield')->getButtonTextColor();?> !important;
	background-color:<?php echo Mage::helper('customfield')->getButtonColor();?> !important;
}.wk_heading{
	padding: 1%;
    background: gray;
	background-color:<?php echo Mage::helper('customfield')->getHeaderColor();?> !important;
}.wk_heading h1{	    	
	margin: 0 0 -0.3em !important;
    color: <?php echo Mage::helper('customfield')->getHeaderTextColor();?> !important;
}.wk_popup_content{
    color: <?php echo Mage::helper('customfield')->getContentTextColor();?> !important;
}.button_container{
    bottom: 5px;
    position: absolute;
    right: 5px;
}.wkcontent{
    overflow: auto;
    margin: 20px;
    max-height:335px;
}
</style>