<?php
 /**
 * @category   Webkul
 * @package    Webkul_CustomField
 * @author     Webkul Software Private Limited
 * @copyright  Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license    https://store.webkul.com/license.html
 */
 if (Mage::helper('customfield')->getEnableDisable()) {
     ?>
<li class=" wktermsprivacyli">
	<div class="field" id="wktermsprivacy">
		<div class="input-box">
			<input type="checkbox" class="required-entry" name="termsprivacy"/><span><a data='terms' class="wk_show_term_privacy_fade" href="#">Terms & Condition</a> And <a class="wk_show_term_privacy_fade" data='privacy' href="#">Privacy & Cookies</a></span>
		</div>
	</div>
	<div style="display: none;" id="wk_term_privacy" class="wkwebkul wk_popup_light">
        <div class="wk_heading">
        	<h1 class="termcontent"> <p> <?php if (Mage::helper('customfield')->getHeading()=='') {
         echo Mage::helper('customfield')->__('Terms & Conditions');
     } else {
         echo Mage::helper('customfield')->getHeading();
     } ?></p></h1>
        	<h1 class="privacycontent"> <p> <?php if (Mage::helper('customfield')->getHeading()=='') {
         echo Mage::helper('customfield')->__('Privacy & Cookies');
     } else {
         echo Mage::helper('customfield')->getPrivacyHeading();
     } ?></p></h1>
        </div>
        <div class="wk_popup_content termcontent">
            <div class="wkcontent">
                <p><?php echo Mage::helper('customfield')->getTermContent() ?></p></div>
        </div>
        <div class="wk_popup_content privacycontent">
            <div class="wkcontent" >
                <p><?php echo Mage::helper('customfield')->getPrivacyContent() ?></p></div>
        </div>
        <div class="button_container">
        	<button  name="wkbutton" class="wkbutton button" ><span><span><?php if (Mage::helper('customfield')->getButtonText()=='') {
         echo Mage::helper('customfield')->__('I Agree');
     } else {
         echo Mage::helper('customfield')->getButtonText();
     } ?></span></span></button>
        </div>
    </div>
    <div style="display: none;" id="wk_term_privacy_fade" class="wkwebkul wk_popup_fade" ></div>
</li>
<script type="text/javascript">
	if(typeof jQuery == "undefined"){
		document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
	}
</script>
<script type="text/javascript">
	var $wk_jq=jQuery.noConflict();
	(function($wk_jq){
		$wk_jq(function(){
			$wk_jq('.account-create').find('.form-list.wkform').append($wk_jq('.wktermsprivacyli'));
			$wk_jq('.wktermsprivacyli').show();
			$wk_jq('.wk_show_term_privacy_fade').on('click',function(){	

				if($wk_jq(this).attr('data')=='terms')
				{
					$wk_jq('.termcontent').show();
					$wk_jq('.privacycontent').hide();
				}else if($wk_jq(this).attr('data')=='privacy'){
					$wk_jq('.privacycontent').show();
					$wk_jq('.termcontent').hide();
				}
				$wk_jq('.wkwebkul').show();
			});
			$wk_jq('.wkbutton').on('click',function(event){
				event.preventDefault();
				$wk_jq('.wkwebkul').hide();
			});
		});
	})($wk_jq);
</script>
<?php 
 }?>