<?php # 2024-02-06 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
$_item = $this->getItem();
$isVisibleProduct = $_item->getProduct()->isVisibleInSiteVisibility();
$canApplyMsrp = Mage::helper('catalog')->canApplyMsrp($_item->getProduct(), Mage_Catalog_Model_Product_Attribute_Source_Msrp_Type::TYPE_BEFORE_ORDER_CONFIRM);
# 2024-01-20 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `app/design/frontend/base/default/template/checkout/cart/item/default.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/212
# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/checkout/cart/item/default.phtml#L31-L32
$_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()]));
$_deleteUrl = $this->getDeleteUrlCustom(false);
?>
<tr>
    <td><?php if ($this->hasProductUrl()):?><a href="<?php echo $this->getProductUrl() ?>" title="<?php echo $this->escapeHtml($this->getProductName()) ?>" class="product-image"><?php endif ?><img src="<?php echo $this->getProductThumbnail()->resize(75); ?>" width="75" height="75" alt="<?php echo $this->escapeHtml($this->getProductName()) ?>" /><?php if ($this->hasProductUrl()):?></a><?php endif ?></td>
    <td>
        <h2 class="product-name">
        <?php if ($this->hasProductUrl()):?>
            <a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->escapeHtml($this->getProductName()) ?></a>
        <?php else: ?>
            <?php echo $this->escapeHtml($this->getProductName()) ?>
        <?php endif ?>
        </h2>
        <?php if ($_options = $this->getOptionList()):?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif ?>><?php echo $_formatedOptionValue['value'] ?>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="truncated_full_value">
                    <dl class="item-options">
                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                    </dl>
                </div>
                <?php endif ?>
            </dd>
            <?php endforeach ?>
        </dl>
        <?php endif ?>
        <?php if ($messages = $this->getMessages()): ?>
        <?php foreach ($messages as $message): ?>
            <p class="item-msg <?php echo $message['type'] ?>">* <?php echo $this->escapeHtml($message['text']) ?></p>
        <?php endforeach ?>
        <?php endif ?>
        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock): ?>
            <?php echo $addInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif ?>
    </td>
    <td class="a-center edititem">
        <?php if ($isVisibleProduct): ?>
        <a
			href="<?= $this->getConfigureUrl() ?>"
<?php # 2024-01-20 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `app/design/frontend/base/default/template/checkout/cart/item/default.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/212
# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/checkout/cart/item/default.phtml#L74 ?>
			title="<?= Mage::helper('core')->quoteEscape($this->__('Edit item parameters')) ?>"
		><?= $this->__('Edit') ?></a>
        <?php endif ?>
    </td>
    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
    <td class="a-center wishlistitem">
        <?php if ($isVisibleProduct): ?>
            <a href="<?php echo $this->helper('wishlist')->getMoveFromCartUrl($_item->getId()); ?>" class="link-wishlist use-ajax"><?php echo $this->__('Move'); ?></a>
        <?php endif ?>
    </td>
    <?php endif ?>

    <?php if ($canApplyMsrp): ?>
        <td class="a-right"<?php if ($this->helper('tax')->displayCartBothPrices()): ?> colspan="2"<?php endif ?>>
            <span class="cart-price">
                <span class="cart-msrp-unit"><?php echo $this->__('See price before order confirmation.'); ?></span>
                <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                <a id="<?php echo $helpLinkId ?>" href="#" class="map-help-link"><?php echo $this->__("What's this?"); ?></a>
                <script type="text/javascript">
                    Catalog.Map.addHelpLink($('<?php echo $helpLinkId ?>'), "<?php echo $this->__("What's this?") ?>");
                </script>
            </span>
        </td>
    <?php else: ?>

        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td class="a-right">
			<span class="cart-price">
				<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
            </span>
        </td>
        <?php endif ?>
        <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <td>
            <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
			<span class="cart-price">
				<?php echo $this->helper('checkout')->formatPrice($_incl) ?>
			</span>
        </td>
        <?php endif ?>
    <?php endif ?>
    <td class="a-center qtybox">
		<input
			class="input-text qty"
<?php # 2024-01-20 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `app/design/frontend/base/default/template/checkout/cart/item/default.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/212
# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/checkout/cart/item/default.phtml#L183-L185 ?>
			data-cart-item-id="<?= $this->jsQuoteEscape($_item->getSku()) ?>"
			maxlength="12"
			name="cart[<?= $_item->getId() ?>][qty]"
			size="4"
			title="<?= $this->__('Qty') ?>"
			value="<?= $this->getQty() ?>"
		/>
    </td>
    <?php if (($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td class="a-right itemwisetotal">
		<span class="cart-price">
            <?php if ($canApplyMsrp): ?>
                <span class="cart-msrp-subtotal">--</span>
            <?php else: ?>
				<?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
            <?php endif ?>
        </span>
    </td>
    <?php endif ?>
    <?php if (($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()) && !$_item->getNoSubtotal()): ?>
    <td class="finaltotal">
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
		<span class="cart-price">

            <?php if ($canApplyMsrp): ?>
                <span class="cart-msrp-subtotal">--</span>
            <?php else: ?>
				<?php echo $this->helper('checkout')->formatPrice($_incl) ?>
            <?php endif ?>

        </span>
    </td>
    <?php endif ?>
    <td class="a-center removeitem">
<!-- 2024-01-20 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `app/design/frontend/base/default/template/checkout/cart/item/default.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/212
# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/checkout/cart/item/default.phtml#L283-L288 -->
		<a href="#"
			title="<?= Mage::helper('core')->quoteEscape($this->__('Remove Item')) ?>"
			class="btn-remove btn-remove2"
			onclick="customFormSubmit('<?= $_deleteUrl ?>', '<?= $_params ?>', 'post')">
			<?= $this->__('Remove Item') ?>
		</a>
	</td>
</tr>
