<?php # 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
$_item = $this->getItem()?>
<tr>
    <td><h3 class="product-name"><?php echo $this->escapeHtml($this->getProductName()) ?></h3>
        <!-- item custom options -->
        <?php if ($_options = $this->getOptionList()):?>
        <dl class="item-options">
            <?php foreach ($_options as $_option) : ?>
            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
            <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif ?>><?php echo $_formatedOptionValue['value'] ?>
                <?php if (isset($_formatedOptionValue['full_view'])): ?>
                <div class="truncated_full_value">
                    <dl class="item-options">
                        <dt><?php echo $this->escapeHtml($_option['label']) ?></dt>
                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
                    </dl>
                </div>
                <?php endif ?>
            </dd>
            <?php endforeach ?>
        </dl>
        <?php endif ?>
        <?php if ($links = $this->getLinks()): ?>
        <dl class="item-options">
            <dt><?php echo $this->escapeHtml($this->getLinksTitle()); ?></dt>
            <?php foreach ($links as $link): ?>
                <dd><?php echo $this->escapeHtml($link->getTitle()); ?></dd>
            <?php endforeach ?>
        </dl>
        <?php endif ?>
        <!-- EOF downloadable -->
    </td>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
		<div class="cart-price">
			<?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
        </div>
    </td>
    <?php endif ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <?php $_incl = $this->helper('checkout')->getPriceInclTax($_item); ?>
		<div class="cart-price">
			<?php echo $this->helper('checkout')->formatPrice($_incl) ?>
        </div>
    </td>
    <?php endif ?>
    <td class="a-center"><?php echo $_item->getQty() ?></td>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td class="a-right">
		<div class="cart-price">
			<?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
        </div>
    </td>
    <?php endif ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
		<div class="cart-price">
			<?php echo $this->helper('checkout')->formatPrice($_incl) ?>
        </div>
    </td>
    <?php endif ?>
</tr>
