<?php /** @var Mage_Checkout_Block_Cart $this */ ?>
<div class="cart">
    <?php echo $this->getChildHtml('form_before') ?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php if(!$this->hasError() && count($this->getItems()) > 1): ?>
        <ul class="checkout-types">
        <?php foreach ($this->getMethods('methods') as $method): ?>
            <?php $methodHtml = $this->getMethodHtml($method); ?>
            <?php if ($methodHtml): ?>
            <li><?php echo $methodHtml; ?></li>
            <?php endif ?>
        <?php endforeach ?>
        </ul>
    <?php endif ?>
    <form
<?php # 2024-01-21 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `app/design/frontend/base/default/template/checkout/cart.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/217
# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/checkout/cart.phtml#L49 ?>
		action="<?= $this->getFormActionUrl() ?>"
		method="post"
	>
        <fieldset>
            <table id="shopping-cart-table" class="data-table cart-table">
                
                <tbody>
                <?php foreach($this->getItems() as $_item): ?>
                    <?php echo $this->getItemHtml($_item) ?>
                <?php endforeach ?>
                </tbody>
            </table>
            <div class="chk_cartbtn">
                          <button type="submit" name="update_cart_action" value="update_qty" title="<?php echo $this->__('Update Shopping Cart'); ?>" class="button btn-update"><?php echo $this->__('Update Shopping Cart'); ?></button>
                            <!--<button type="submit" name="update_cart_action" value="empty_cart" title="<?php echo $this->__('Clear Shopping Cart'); ?>" class="button btn-update" id="empty_cart_button"><?php echo $this->__('Clear Shopping Cart'); ?></button>-->
                     
                </div>
        </fieldset>
    </form>
    <div class="cart-collaterals">
            <div class="collat-wrap">
                <div class="grid_4"><?php echo $this->getChildHtml('coupon') ?></div>
                <div class="grid_4"><?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif ?></div>
                <div class="totals grid_4">
                    <?php echo $this->getChildHtml('totals'); ?>
                    <?php if(!$this->hasError()): ?>
                    <ul class="checkout-types">
                    <?php foreach ($this->getMethods('methods') as $method): ?>
                        <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                        <li><?php echo $methodHtml; ?></li>
                        <?php endif ?>
                    <?php endforeach ?>
                    </ul>
                    <?php endif ?>
                </div>
            </div>
			<div class="crosssell-wrap">
                <?php echo $this->getChildHtml('crosssell') ?>
            </div>
    </div>
</div>
