<?php
# 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
/** @var Mage_Catalog_Block_Product_Abstract $this */
$_coreHelper = $this->helper('core');
$_taxHelper = $this->helper('tax');
/* @var $_coreHelper Mage_Core_Helper_Data */
/* @var $_taxHelper Mage_Tax_Helper_Data */

$_product = $this->getProduct();
$_storeId = $_product->getStoreId();
$_store = $_product->getStore();
$_id = $_product->getId();
$_simplePricesTax = ($_taxHelper->displayPriceIncludingTax() || $_taxHelper->displayBothPrices());
$_minimalPriceValue = $_product->getMinimalPrice();
$_minimalPriceValue = $_store->roundPrice($_store->convertPrice($_minimalPriceValue));
$_minimalPrice = $_taxHelper->getPrice($_product, $_minimalPriceValue, $_simplePricesTax);
$_convertedFinalPrice = $_store->roundPrice($_store->convertPrice($_product->getFinalPrice()));
$_specialPriceStoreLabel = $this->getProductAttribute('special_price')->getStoreLabel();
?>

<?php if (!$_product->isGrouped()): ?>
    <div class="price-box">
    <?php $_convertedPrice = $_store->roundPrice($_store->convertPrice($_product->getPrice())); ?>
    <?php $_price = $_taxHelper->getPrice($_product, $_convertedPrice); ?>
    <?php $_regularPrice = $_taxHelper->getPrice($_product, $_convertedPrice, $_simplePricesTax); ?>
    <?php $_finalPrice = $_taxHelper->getPrice($_product, $_convertedFinalPrice) ?>
    <?php $_finalPriceInclTax = $_taxHelper->getPrice($_product, $_convertedFinalPrice, true) ?>
    <?php if ($_finalPrice >= $_price): ?>
        <?php if ($_taxHelper->displayBothPrices()): ?>
			<span class="price-excluding-tax">
				<span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
				<span class="price" id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php if ($_finalPrice == $_price): ?>
						<?php echo $_coreHelper->formatPrice($_price, false) ?>
					<?php else: ?>
						<?php echo $_coreHelper->formatPrice($_finalPrice, false) ?>
					<?php endif; ?>
				</span>
			</span>
			<span class="price-including-tax">
				<span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
				<span class="price" id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
					<?php echo $_coreHelper->formatPrice($_finalPriceInclTax, false) ?>
				</span>
			</span>
        <?php else: ?>
			<span class="regular-price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
				<?php if ($_finalPrice == $_price): ?>
					<?php echo $_coreHelper->formatPrice($_price, true) ?>
				<?php else: ?>
					<?php echo $_coreHelper->formatPrice($_finalPrice, true) ?>
				<?php endif; ?>
			</span>
        <?php endif; ?>
    <?php else: /* if ($_finalPrice == $_price): */ ?>
            <p class="old-price">
                <span class="price-label"><?php echo $this->__('Regular Price:') ?></span>
                <span class="price" id="old-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                    <?php echo $_coreHelper->formatPrice($_regularPrice, false) ?>
                </span>
            </p>

            <?php if ($_taxHelper->displayBothPrices()): ?>
                <p class="special-price">
                    <span class="price-label"><?php echo $_specialPriceStoreLabel ?></span>
                    <span class="price-excluding-tax">
                        <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
                        <span class="price"
                              id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                            <?php echo $_coreHelper->formatPrice($_finalPrice, false) ?>
                        </span>
                    </span>
                    <span class="price-including-tax">
                        <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
                        <span class="price"
                              id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                            <?php echo $_coreHelper->formatPrice($_finalPriceInclTax, false) ?>
                        </span>
                    </span>
                </p>
            <?php else: ?>
                <p class="special-price">
                    <span class="price-label"><?php echo $_specialPriceStoreLabel ?></span>
                <span class="price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                    <?php echo $_coreHelper->formatPrice($_finalPrice, false) ?>
                </span>
                </p>
            <?php endif; ?>

    <?php endif; /* if ($_finalPrice == $_price): */ ?>

    <?php if ($this->getDisplayMinimalPrice() && $_minimalPriceValue && $_minimalPriceValue < $_convertedFinalPrice): ?>

        <?php $_minimalPriceDisplayValue = $_minimalPrice; ?>

        <?php if ($this->getUseLinkForAsLowAs()): ?>
            <a href="<?php echo $_product->getProductUrl(); ?>" class="minimal-price-link">
        <?php else: ?>
            <span class="minimal-price-link">
        <?php endif ?>
        <span class="label"><?php echo $this->__('As low as:') ?></span>
        <span class="price" id="product-minimal-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                <?php echo $_coreHelper->formatPrice($_minimalPriceDisplayValue, false) ?>
            </span>
        <?php if ($this->getUseLinkForAsLowAs()): ?>
            </a>
        <?php else: ?>
            </span>
        <?php endif ?>
    <?php endif; /* if ($this->getDisplayMinimalPrice() && $_minimalPrice && $_minimalPrice < $_finalPrice): */ ?>
    </div>

<?php else: /* if (!$_product->isGrouped()): */ ?>
    <?php
    $showMinPrice = $this->getDisplayMinimalPrice();
    if ($showMinPrice && $_minimalPriceValue) {
        $_exclTax = $_taxHelper->getPrice($_product, $_minimalPriceValue);
        $_inclTax = $_taxHelper->getPrice($_product, $_minimalPriceValue, true);
        $price = $showMinPrice ? $_minimalPriceValue : 0;
    } else {
        $price = $_convertedFinalPrice;
        $_exclTax = $_taxHelper->getPrice($_product, $price);
        $_inclTax = $_taxHelper->getPrice($_product, $price, true);
    }
    ?>
    <?php if ($price): ?>
        <div class="price-box">
            <p<?php if ($showMinPrice): ?> class="minimal-price"<?php endif ?>>
                <?php if ($showMinPrice): ?>
                    <span class="price-label"><?php echo $this->__('Starting at:') ?></span>
                <?php endif ?>
                <?php if ($_taxHelper->displayBothPrices()): ?>
                    <span class="price-excluding-tax">
                        <span class="label"><?php echo $this->helper('tax')->__('Excl. Tax:') ?></span>
                        <span class="price"
                              id="price-excluding-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                            <?php echo $_coreHelper->formatPrice($_exclTax, false) ?>
                        </span>
                    </span>
                    <span class="price-including-tax">
                        <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax:') ?></span>
                        <span class="price"
                              id="price-including-tax-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                            <?php echo $_coreHelper->formatPrice($_inclTax, false) ?>
                        </span>
                    </span>
                <?php else: ?>
                    <?php
                    $_showPrice = $_inclTax;
                    if (!$_taxHelper->displayPriceIncludingTax()) {
                        $_showPrice = $_exclTax;
                    }
                    ?>
                    <span class="price" id="product-minimal-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                    <?php echo $_coreHelper->formatPrice($_showPrice, false) ?>
                </span>
                <?php endif; ?>
            </p>
        </div>
    <?php endif; /* if ($this->getDisplayMinimalPrice() && $_minimalPrice): */ ?>
<?php endif; /* if (!$_product->isGrouped()): */ ?>
