<?php /** @var Mage_Catalog_Block_Product_List $this */
$_productCollection=$this->getLoadedProductCollection();
# 2024-02-14 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Upgrade Magento 1.9.4.5 to OpenMage LTS 19.5.2": https://github.com/thehcginstitute-com/m1/issues/34
$_productCollectionCount = count($_productCollection);
$_helper = $this->helper('catalog/output');
# 2024-01-19 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# 1) "Port the `app/design/frontend/base/default/template/catalog/product/list.phtml` 1.9.1.0 → 1.9.4.5 changes
# to the `mobileshoppe` design theme": https://github.com/thehcginstitute-com/m1/issues/209
# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/catalog/product/list.phtml#L37
$_params = $this->escapeHtml(json_encode(['form_key' => $this->getFormKey()]));
if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
    <?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar_top.phtml')->toHtml(); ?> 
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
		<?php # 2024-02-14 Dmitrii Fediuk https://upwork.com/fl/mage2pro
		# "Upgrade Magento 1.9.4.5 to OpenMage LTS 19.5.2": https://github.com/thehcginstitute-com/m1/issues/34 ?>
        <li class="item<?php if(++$_iterator === $_productCollectionCount): ?> last<?php endif ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(252); ?>" width="252" height="252" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->isSaleable()):
						# 2024-01-19 Dmitrii Fediuk https://upwork.com/fl/mage2pro
						# 1) "Port the `app/design/frontend/base/default/template/catalog/product/list.phtml`
						# 1.9.1.0 → 1.9.4.5 changes to the `mobileshoppe` design theme":
						# https://github.com/thehcginstitute-com/m1/issues/209
						# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/catalog/product/list.phtml#L62-L72
						# 2024-02-14 Dmitrii Fediuk https://upwork.com/fl/mage2pro
						# "Upgrade Magento 1.9.4.5 to OpenMage LTS 19.5.2":
						# https://github.com/thehcginstitute-com/m1/issues/34
						$_cartUrl = $this->getAddToCartUrlCustom($_product, [], false);
					?>
                        <p class="action">
							<button
								type="button"
								title="<?= $this->quoteEscape($this->__('Add to Cart')) ?>"
								class="button btn-cart"
								onclick="customFormSubmit('<?= $_cartUrl ?>', '<?= $_params ?>', 'post')"
							><span><span><?= $this->__('View Requirements') ?></span></span></button>
						</p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) {
							# 2024-01-19 Dmitrii Fediuk https://upwork.com/fl/mage2pro
							# 1) "Port the `app/design/frontend/base/default/template/catalog/product/list.phtml`
							# 1.9.1.0 → 1.9.4.5 changes to the `mobileshoppe` design theme":
							# https://github.com/thehcginstitute-com/m1/issues/209
							# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/catalog/product/list.phtml#L82-L91
							$_wishlistUrl = $this->helper('wishlist')->getAddUrlWithCustomParams($_product, [], false); ?>
							<li>
								<a
									class="link-wishlist"
									data-params="<?= $_params ?>"
									data-url="<?= $_wishlistUrl ?>"
									href="#"
									onclick="customFormSubmit('<?= $_wishlistUrl ?>', '<?= $_params ?>', 'post')"
								><?= $this->__('Add to Wishlist') ?></a>
							</li>
                        <?php
						}
						# 2024-01-19 Dmitrii Fediuk https://upwork.com/fl/mage2pro
						# 1) "Port the `app/design/frontend/base/default/template/catalog/product/list.phtml`
						# 1.9.1.0 → 1.9.4.5 changes to the `mobileshoppe` design theme":
						# https://github.com/thehcginstitute-com/m1/issues/209
						# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/catalog/product/list.phtml#L93-L102
						if ($_compareUrl = $this->getAddToCompareUrlCustom($_product, false)) { ?>
                            <li>
                                <span class="separator">|</span>
                                <a
									class="link-compare"
									href="#"
									onclick="customFormSubmit('<?= $_compareUrl ?>', '<?= $_params ?>', 'post')"
								><?= $this->__('Add to Compare') ?></a>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </li>
    <?php endforeach ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
		<?php $_iterator = 0; ?>
        <ul class="products-grid">    
		<?php $i=0; foreach ($_productCollection as $_product): ?>
            <li class="item">
                <div class="pro_topadst">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(252); ?>" width="252" height="252" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
                <div class="actions">
                    <?php if($_product->isSaleable()):
						# 2024-01-19 Dmitrii Fediuk https://upwork.com/fl/mage2pro
						# 1) "Port the `app/design/frontend/base/default/template/catalog/product/list.phtml`
						# 1.9.1.0 → 1.9.4.5 changes to the `mobileshoppe` design theme":
						# https://github.com/thehcginstitute-com/m1/issues/209
						# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/catalog/product/list.phtml#L130-L138
						# 2024-02-14 Dmitrii Fediuk https://upwork.com/fl/mage2pro
						# "Upgrade Magento 1.9.4.5 to OpenMage LTS 19.5.2":
						# https://github.com/thehcginstitute-com/m1/issues/34
						$_cartUrl = $this->getAddToCartUrlCustom($_product, [], false);
					?>
                        <button
							type="button"
							title="<?= $this->quoteEscape($this->__('View Requirements')) ?>"
							class="button btn-cart"
							onclick="customFormSubmit('<?= $_cartUrl ?>', '<?= $_params ?>', 'post')"
						><span><span><?php echo $this->__('View Requirements') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) {
							# 2024-01-19 Dmitrii Fediuk https://upwork.com/fl/mage2pro
							# 1) "Port the `app/design/frontend/base/default/template/catalog/product/list.phtml`
							# 1.9.1.0 → 1.9.4.5 changes to the `mobileshoppe` design theme":
							# https://github.com/thehcginstitute-com/m1/issues/209
							# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/catalog/product/list.phtml#L144-L153
							$_wishlistUrl = $this->helper('wishlist')->getAddUrlWithCustomParams($_product, [], false); ?>
                            <li>
                                <a
									class="link-wishlist"
									data-params="<?= $_params ?>"
									data-url="<?= $_wishlistUrl ?>"
									href="#"
									onclick="customFormSubmit('<?= $_wishlistUrl ?>', '<?= $_params ?>', 'post')"
								><?= $this->__('Add to Wishlist') ?></a>
                            </li>
                        <?php
						}
						# 2024-01-19 Dmitrii Fediuk https://upwork.com/fl/mage2pro
						# 1) "Port the `app/design/frontend/base/default/template/catalog/product/list.phtml`
						# 1.9.1.0 → 1.9.4.5 changes to the `mobileshoppe` design theme":
						# https://github.com/thehcginstitute-com/m1/issues/209
						# 2) https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/design/frontend/base/default/template/catalog/product/list.phtml#L155-L164
						if ($_compareUrl = $this->getAddToCompareUrlCustom($_product, false)) { ?>
							<li>
								<span class="separator">|</span>
								<a
									href="#"
									class="link-compare"
									onclick="customFormSubmit('<?= $_compareUrl ?>', '<?= $_params ?>', 'post')"
								><?= $this->__('Add to Compare') ?></a>
							</li>
						<?php } ?>
                    </ul>
                </div>
            </li>  
		<?php endforeach ?>
		</ul>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/toolbar_bottom.phtml')->toHtml(); ?>
    </div>
</div>
<?php endif ?>
