<?php # 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
$_item = $this->getItem();
$_quote = $this->getItem()->getQuote(); ?>
<tr>
    <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
        <strong style="font-size:11px;"><?php echo $this->htmlEscape($_item->getName()) ?></strong>
        <?php if ($this->getItemOptions()): ?>
        <dl style="margin:0; padding:0;">
            <?php foreach ($this->getItemOptions() as $option): ?>
            <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
            <dd style="margin:0; padding:0 0 0 9px;">
                <?php echo nl2br($this->escapeHtml($option['value'])) ?>
            </dd>
            <?php endforeach ?>
        </dl>
        <?php endif ?>
        <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
        <?php if ($addInfoBlock) :?>
        <?php echo $addInfoBlock->setItem($_item)->toHtml(); ?>
        <?php endif ?>
        <?php echo $this->escapeHtml($_item->getDescription()) ?>
    </td>
    <td align="left" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;"><?php echo $this->htmlEscape($this->getSku($_item)) ?></td>
    <td align="center" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;"><?php echo $_item->getQtyOrdered()*1 ?></td>
    <td align="right" valign="top" style="font-size:11px; padding:3px 9px; border-bottom:1px dotted #CCCCCC;">
        <?php if ($this->helper('tax')->displaySalesPriceExclTax($_quote->getStoreId()) || $this->helper('tax')->displaySalesBothPrices($_quote->getStore())): ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices($_quote->getStoreId())): ?>
            <span class="label"><?php echo Mage::helper('tax')->__('Excl. Tax'); ?>:</span>
            <?php endif ?>
			<?php echo Mage::app()->getLocale()->currency($_quote->getQuoteCurrencyCode())->toCurrency($_item->getRowTotal()) ?>
        <?php endif ?>


        <?php if ($this->helper('tax')->displaySalesPriceInclTax($_quote->getStoreId()) || $this->helper('tax')->displaySalesBothPrices($_quote->getStoreId())): ?>
        <?php if ($this->helper('tax')->displaySalesBothPrices($_quote->getStoreId())): ?>
            <br /><span class="label"><?php echo Mage::helper('tax')->__('Incl. Tax'); ?>:</span>
            <?php endif ?>
        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
        <?php echo Mage::app()->getLocale()->currency($_quote->getQuoteCurrencyCode())->toCurrency($_incl) ?>
        <?php endif ?>
    </td>
</tr>
<?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('giftmessage/message')->getGiftMessage($_item->getGiftMessageId())): ?>
<tr>
    <td colspan="4" style=" border-bottom:2px solid #CCCCCC; padding:3px 9px;">
        <strong style="color:#444444; font-size:11px;"><?php echo $this->__('Gift Message') ?></strong>
        <?php echo $this->__('From:'); ?> <?php echo $this->htmlEscape($_giftMessage->getSender()) ?><br />
        <?php echo $this->__('To:'); ?> <?php echo $this->htmlEscape($_giftMessage->getRecipient()) ?><br />
        <strong><?php echo $this->__('Message:'); ?></strong><br /><?php echo $this->htmlEscape($_giftMessage->getMessage()) ?>
    </td>
</tr>
<?php endif ?>
