<?php # 2024-02-06 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
$_item = $this->getItem();
$this->setPriceDataObject($_item) ?>
<tr<?php if ($this->canDisplayGiftmessage()): ?> class="border"<?php endif; ?>>
<td class="giftmessage-single-item">
    <?php if ($this->canDisplayContainer()): ?>
    <div id="<?php echo $this->getHtmlId() ?>" class="item-container">
        <?php endif; ?>
        <div class="item-text">
            <?php echo $this->getColumnHtml($_item, 'downloadable') ?>
        </div>
        <?php if ($this->canDisplayContainer()): ?>
    </div>
<?php endif ?>
</td>
<td class="a-center"><?php echo $_item->getStatus() ?></td>
<td class="a-right"><?php echo $this->displayPriceAttribute('original_price') ?></td>
<td class="a-right">
    <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
        <span class="price-excl-tax">
			<?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
				<span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
			<?php endif; ?>
			<?php echo $this->displayPrices($_item->getBasePrice(), $_item->getPrice()) ?>
		</span>
        <br/>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displaySalesPriceInclTax() || $this->helper('tax')->displaySalesBothPrices()): ?>
        <span class="price-incl-tax">
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax'); ?>:</span>
                <?php endif; ?>
				<?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getPriceInclTax($_item)); ?>
            </span>
    <?php endif; ?>
</td>
<td><?php echo $this->getColumnHtml($_item, 'qty') ?></td>

<td class="a-right">
    <?php if ($this->helper('tax')->displaySalesBothPrices() || $this->helper('tax')->displaySalesPriceExclTax()): ?>
        <span class="price-excl-tax">
                <?php if ($this->helper('tax')->displaySalesBothPrices()): ?>
                    <span class="label"><?php echo $this->__('Excl. Tax'); ?>:</span>
                <?php endif; ?>
<!-- 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377 -->
			<?php echo $this->displayPrices($_item->getBaseRowTotal(), $_item->getRowTotal()) ?>
<!-- 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377 -->
            </span>
        <br/>
    <?php endif; ?>

    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <span class="price-incl-tax">

                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax'); ?>:</span>
                <?php endif; ?>
<!-- 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
"Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377 -->
				<?php echo $this->displaySubtotalInclTax($_item); ?>

            <!--

                 <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                      <span class="label"><?php echo $this->helper('tax')->__('Incl. Tax'); ?>:</span>
                 <?php endif; ?>
                 <?php echo $this->displaySubtotalInclTax($_item); ?>
    -->
            </span>
    <?php endif; ?>
</td>
<td class="a-right"><?php echo $this->displayPriceAttribute('tax_amount') ?></td>
<td class="a-right"><?php echo $this->displayTaxPercent($_item) ?></td>
<td class="a-right"><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
<td class="a-right last">
    <?php
# 2024-02-05 Dmitrii Fediuk https://upwork.com/fl/mage2pro
# "Delete the unused `Mage_Weee` module": https://github.com/thehcginstitute-com/m1/issues/377
	echo $this->displayPrices(
        $_item->getBaseRowTotal() - $_item->getBaseDiscountAmount() + $_item->getBaseTaxAmount() + $_item->getBaseHiddenTaxAmount(),
        $_item->getRowTotal() - $_item->getDiscountAmount() + $_item->getTaxAmount() + $_item->getHiddenTaxAmount()
    ); ?>
</td>
</tr>
