<?php
$helper               = Mage::helper('magepsycho_storerestrictionpro');
$hideAddToCartText    = $helper->getConfig()->getAccessibleHideAddToCartText();
$hideAddToCartLink    = $helper->getConfig()->getAccessibleHideAddToCartLink();
$onclickAction        = 'javascript:void(0)';
if (!empty($hideAddToCartLink)) {
    $hideAddToCartLink       = $this->getUrl(trim($hideAddToCartLink, '/'));
    $onclickAction           = sprintf("%s", $hideAddToCartLink);
}
?>
<script type="text/javascript">
    Event.observe(window, 'load', function() {
        $$('.catalog-category-view .product-info .actions .button').each(function (el) {
            <?php if(empty($hideAddToCartText)): ?>
            el.remove();
            <?php else: ?>
            el.writeAttribute('title', '<?php echo $this->escapeHtml($hideAddToCartText) ?>');
            el.writeAttribute('href', "<?php echo $this->escapeHtml($onclickAction) ?>");
            el.update('<?php echo $this->escapeHtml($hideAddToCartText) ?>');
            <?php endif; ?>
        });

        // remove duplicate restricted price label
        if ($$('.price-info a').length > 1) {
            $$('.price-info a').slice(1).each(function (el) {
                el.remove();
            });
        }
    });

</script>